### ISSUE TITLE
"Form & Search History" not clearing whan I quit firefox

### ISSUE THREAD

**Issue by githubbmn** [Quicksaver/Tab-Groups#103]
I enable "Clear history when Firefox closes" on my firefox preferences page, also I checked the "Form & Search History" box on "Settings for Clearing History" windows.
Reference: [Settings for privacy, browsing history and do-not-track](https://support.mozilla.org/en-US/kb/settings-privacy-browsing-history-do-not-track)
So when I quit my firefox broswer, the Form & Search History SHOULD BE all cleared.

I find a problem when I use this addons on my firefox:
When I quit firefox and then restart my firefox, the Form & Search History is not clearing, they're still saved on the searchbar for firefox, and the text field on the webpage.

If I disable this addons, this problem does not occur.

So I guess that I find a bug for this addons, would you mind checking what is the happen please?

My english is not well, sorry for my poor english.

**Comment by Quicksaver** [comment]
I'm almost certain this isn't caused by the add-on itself, it touches nothing about history like that at all. I also can't reproduce this. What Firefox version are you on? And do you have enabled the checkbox titled "Remember search and form history" (just above "Clear history when Firefox closes")?

The first time the add-on is installed it flips the preference "When Firefox starts" to "Show my windows and tabs from last time" in Firefox's options, in order to remember groups after exiting Firefox. Have you tried switching that back and see if that helps?

**Comment by githubbmn** [comment]
This is config on my computer:
OS: Windows 7 Professional 64-bit
Firefox version: 44.0.2
The addons I use on my firefox:
[Adblock Plus](https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/)
[FireGestures](https://addons.mozilla.org/en-US/firefox/addon/firegestures/)
[Menu Wizard](https://addons.mozilla.org/en-US/firefox/addon/s3menu-wizard/)
[Right Links](https://addons.mozilla.org/en-US/firefox/addon/right-links/)
[Tab Groups](https://addons.mozilla.org/en-US/firefox/addon/tab-groups-panorama/)

Yes, I enable "Remember search and form history" checkbox on the "Privacy" page for my preference, but it just meaning "keep my search/form history BEFORE I quit my firefox".
When I quit and then restart firefox, the search/form history SHOULD be all cleared automatically that I also enable "Clear history when Firefox closes" checkbox.

My "When Firefox starts" is setting to "show a blank page", because I don't need firefox remember all the windows and tabs from my previous session.
I already checking my preferences page on my firefox, that homepage setting does not change.

To help you finding what is the happening, I leave some screencap about my firefox browser.
Sorry for my screencap is not english language because I am a Traditional Chinese user.

![1](https://cloud.githubusercontent.com/assets/17193735/13025725/7a3f87f2-d249-11e5-9d87-2468638220f8.png)
This is my Privacy setting for my firefox.
Reference: [Settings for privacy, browsing history and do-not-track](https://support.mozilla.org/en-US/kb/settings-privacy-browsing-history-do-not-track)


![2](https://cloud.githubusercontent.com/assets/17193735/13025728/861d46fe-d249-11e5-9434-5afa1ccd9ad7.png)
This is my setting for "Clear history when Firefox closes".
Reference: [How do I make Firefox clear my history automatically?](https://support.mozilla.org/en-US/kb/delete-browsing-search-download-history-firefox#w_how-do-i-make-firefox-clear-my-history-automatically)


![3](https://cloud.githubusercontent.com/assets/17193735/13025729/8d089f54-d249-11e5-9174-13c11c65a2f9.png)
This is my setting for "When Firefox starts".
Refernece:[Startup, home page, tabs, and download settings](https://support.mozilla.org/en-US/kb/startup-home-page-tabs-download-settings)
I DO NOT keep the windows and tabs when I close the firefox browser.

![4](https://cloud.githubusercontent.com/assets/17193735/13025763/533c671e-d24a-11e5-9dec-07f09b17c778.png)
When I open my firefox browser, the form and search history are still saved on my browser. However I setting to clear them all, what is the happen?
Sometime, the form and history is clear correctly If I close firefox browser, and then idle a LONG moment before I open firefox browser again.

I need your help to finding what is the happen. Is that a bug for this addons, or a bug for the firefox itself? Thank you for your help.

**Comment by Quicksaver** [comment]
Using those exact settings I can't reproduce this at all. I have tried a few different combinations as well, but as long as I leave "Clear history when Firefox closes", and of course its "Form and search history", checked then it never remembers those for me after quitting Firefox.

I'm also fairly certain it can't be Tab Groups causing this, it really goes nowhere near the parts of the application that deal with keeping/clearing history. As I mentioned, the add-on really only flips the "When Firefox starts" preference, and even then if there was a problem it would be with Firefox's session manager (as the add-on is just enabling it in that case).

Are you absolutely sure that if you disable Tab Groups your form and search history is cleared, and if you re-enable Tab Groups (and make sure the "When Firefox starts" preference is still set to load a blank page, then the problem comes back? Could it be one of your other add-ons?

[Could you also try in a clean profile?](https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles) It's possible, however unlikely, that it's corrupted somehow and not clearing that data when it should for some reason.

**Comment by Quicksaver** [comment]
> Could you also try in a clean profile? It's possible, however unlikely, that it's corrupted somehow and not clearing that data when it should for some reason.

By that I mean try with and without the Tab Groups add-on in a clean profile.

**Comment by githubbmn** [comment]
Sorry I don't want to try a clean profile for my firefox, because that is time consuming to setting my firefox and addons option.
However, now I am disable my "Tab Groups" addon again. I will make a longer time testing to make sure problem occur or not when I disable this addon. And I will let your know my testing result later.
![5](https://cloud.githubusercontent.com/assets/17193735/13027808/6fc8f41c-d298-11e5-827e-ae8e696e9eac.png)

**Comment by githubbmn** [comment]
Hmmm... one more thing, I find some firefox bug report that look similar to my case:
[Bug 1244525 - Failure to clear Forms and Search History on exit when configured to ](https://bugzilla.mozilla.org/show_bug.cgi?id=1244525)
[Bug 1244650 - Failure to clear Forms and Search Data on exit when configured to Since 46 ](https://bugzilla.mozilla.org/show_bug.cgi?id=1244650)
[Bug 1246491 - Firefox 44 do not correct delete form search history on exit ](https://bugzilla.mozilla.org/show_bug.cgi?id=1246491)
[Bug 1247766 - Login names are not erased when quitting Firefox, even if the security settings is set to erase history when quitting. ](https://bugzilla.mozilla.org/show_bug.cgi?id=1247766)

**Comment by Quicksaver** [comment]
> Sorry I don't want to try a clean profile for my firefox, because that is time consuming to setting my firefox and addons option.

The point of trying in a clean profile is to try it in a default state without all the configurations in your current profile, to see if any of them is causing it. Basically:
- create profile
- install Tab Groups add-on
- make sure these are enabled:
  - "When Firefox starts" to "Show blank tab"
  - "Use custom settings for remembering history"
  - "Clear history on exit"
  - "Form and search data"

> I find some firefox bug report that look similar to my case:

That's what I meant. This doesn't seem to be a problem with the add-on. If you are sure that the add-on is causing the problem for you please reopen the issue. Otherwise, I'll have to assume this is unrelated to the add-on.

**Comment by githubbmn** [comment]
I am back.
I disable "Tab Groups" addon a week ago, to make a longer time test to checking is the problem caused by this addon or not.
My conclusion is the problem is **NOT CAUSE BY** this addon. 

The problem is coming back again when I disable this addon no a long time, I feel this problem is a bug for the firefox itself.
And I guess this bug will have more opportunities to occur on a firefox profile that use many addons.
I have an another firefox profile that only use "Adblock plus" addon, something this bug is occur on this profile too. However, the number of bug occurrences is lessing than my main profile that use four addons.

My english is not well, sorry for my poor english.

**Comment by Quicksaver** [comment]
Thank you for letting me know. What you say is not surprising, after reading those bugs you listed before, there seem to be a few problems with that area in Firefox itself. Hopefully they'll be able to resolve everything soon.
