### ISSUE TITLE
Ability to press a key to define a shortcut instead of selecting from a menu

### ISSUE THREAD

**Issue by vovcacik** [Quicksaver/Tab-Groups#104]
Steps to reproduce:
- create new profile for Firefox 42.0.2 Czech language (I didn't try other versions or languages)
- install Tab Groups 1.0.2
- go to config and set Switch to the previous group and Switch to the next group to semicolon ";"

Expected: both functions are used with semicolon.
Actual: only Switch to the next group works, Switch to the previous group performs no action.

Other keys work as expected for Switch to the previous group, only semicolon is broken as far as I can tell. Semicolon is on the Czech keyboard on the same key as grave accent on English keyboard.

**Comment by Quicksaver** [comment]
That's because shift changes the input key to whatever that other character is on the czech keyboard (degree symbol?). But I could add support for that character and then it would work properly, if of course you configure it to use it instead of the semicolon.

**Comment by vovcacik** [comment]
That could explain it. If you have a patch for me, I could test it for you.

In my naivety I could assume that `charCode` property of events should give you code for semicolon `59` no matter what modification keys are pressed. And indeed the key [tester][] gives me `charCode=59` even with ctrl+shift combination pressed. But from your `Keysets.jsm` I can see it's not that easy.

[tester]: http://www.quirksmode.org/js/keys.html

**Comment by Quicksaver** [comment]
The Keysets module in the add-on doesn't use charCodes (or keyCodes for that matter), it's merely a front for Firefox's own keyboard shortcuts system. I'm not sure it will be possible to use that ring above character in them because it's considered a dead key and I can't find any references to it.

Could you please do something testing for me? Install a key modifier add-on like [Keybinder](https://addons.mozilla.org/firefox/addon/keybinder/) and try to change any shortcut to use that key. For instance, try changing "Reload current page" to something like ```Control + º``` and see if it successfully reloads a webpage.

**Comment by Quicksaver** [comment]
Actually, use [Dorando keyconfig](https://addons.mozilla.org/firefox/addon/dorando-keyconfig/?src=search), it'll be easier to extrapolate the values used later if necessary.

**Comment by Quicksaver** [comment]
Ok, there's a problem. It can't actually use that key right now because it's a dead key, and the current implementation of the keyboard shortcuts in the add-on can't really use those types of keys (with a few exceptions, that isn't one of them).

I will have to rewrite the whole shortcuts system to something like one of those two add-ons use, so that you can fully customize the shortcut key yourself instead of selecting it from a dropdown menu. But that won't happen any time soon as to be honest there's just a whole lot of other things that must take precedence.

I suggest that you use either one of those add-ons to override the shortcut to the one you want. Hopefully that should be enough for now.
