### ISSUE TITLE
Cannot disable remembering last tabs open

### ISSUE THREAD

**Issue by Jaguar83** [Quicksaver/Tab-Groups#111]
There doesn't seem to be an option to stop the addon remembering the tabs that were open in the last session.

**Comment by Quicksaver** [comment]
That's controlled by Firefox itself. You have to go to Firefox's option, and change the preference "When Firefox starts" to whatever you want. The add-on changes this the first time it is installed, so that groups are remembered across sessions, but if you change it back then it will stay as you want it.
