### ISSUE TITLE
Firefox Theme Integration.

### ISSUE THREAD

**Issue by Tisaku** [Quicksaver/Tab-Groups#112]
I use a dark theme because I like the colors, but more importantly, for improved visibility in low light environments. I have used it for so long that my eyes have adapted to reading on a dark background. As is, the tabs page and the settings are a blinding white with light grey text. It is literally painful to try to read anything on them. It's still better than loosing my groups, but not by much.
Either making the background transparent or forcing it to use the theme colors would be a massive improvement for me.

**Comment by Kasijjuf** [comment]
See also #67 and #86

**Comment by Quicksaver** [comment]
What @Kasijjuf said. And as a rule of thumb, theme issues are usually better fixed by the theme itself because the add-on doesn't just "know" what colors/shapes/shadows/etc to apply. FT DeepDark is an exception because I already know that its developer is extremely busy at the moment and has almost no availability to work on it, which is why I'm already planning to try to add some fixes for it on my side it.
