### ISSUE TITLE
Import old Bookmarked Tab Groups

### ISSUE THREAD

**Issue by stripTM** [Quicksaver/Tab-Groups#12]
In Nightly, now notifies of the end of Panorama and it offers the ability to save all tabs / tabs-groups in bookmarks, specifically under "Bookmarked Tab Groups" folder.

It would be desirable that the extension can import these bookmarks.

**Comment by the8472** [comment]
you can simply create a new group and then "open all in tabs" from the bookmarks manager

**Comment by poke** [comment]
It absolutely can!

Just open the extension settings, choose the tab on the far left (backup or something), and then you can import the file on your desktop.

Note that the current group is also imported, so you'll likely end up with a duplicate group. You can just delete one of them then.

**Comment by Quicksaver** [comment]
To clarify, the migration process in Firefox creates a backup file in your desktop, which you can load in the add-on's backup and restore pane (as poke mentioned, you can find it in the add-on's preferences) to import groups from it. :) From the add-on's homepage:
> - If you didn't install the add-on before updating to Firefox 45, don't despair. The backup file created in your desktop by Firefox is fully compatible with the add-on's backup and restore feature. With it, you can just import your groups back into the browser.

I won't be adding this feature simply because it would mean creating a whole new system for something that everyone would use exactly once, if at all.

> Note that the current group is also imported, so you'll likely end up with a duplicate group. You can just delete one of them then.

You can select which groups (and tabs!) you actually want to import. So you can just uncheck the ones you don't want, like the current group in this case. ;)
