### ISSUE TITLE
Option to save all tabs in a group to bookmark folder

### ISSUE THREAD

**Issue by Pheil** [Quicksaver/Tab-Groups#123]
Would be nice addition for a tab group that isn't needed anymore, but would still like to have the sites saved for future reference.  Could probably just have a right click option "Save tabs in this group to xxx. favorite folder" 

Wouldn't need to be based on closing the group, but could be.

**Comment by mgab** [comment]
There is a way to get this, although it may require a few extra clicks. You need to open any tab of a group, so that the tabs in the tab bar are the ones from that group. Then, you right-click any of them and choose `Bookmark all tabs...`, and you can choose the name of the bookmarks folder.
At least for me this only saves the tabs from the active group.

**Comment by maverick74** [comment]
Another good option would be the possibility to Archive this group for later restoration (e.g. sending it to a list of archived groups) - not to be confused whit the backup/restore function that backups all groups at once

**Comment by Quicksaver** [comment]
> Another good option would be the possibility to Archive this group for later restoration (e.g. sending it to a list of archived groups) - not to be confused whit the backup/restore function that backups all groups at once

Although it's not exactly the same thing,you could achieve the same goal with #77.

**Comment by maverick74** [comment]
yes, sort of... It's actually pretty close... i'll elaborate more on 77 ASAP :)

(Sorry, i'm a t work and not always i get time so search for bugs or elaborate my ideas...)

**Comment by Quicksaver** [comment]
> (Sorry, i'm a t work and not always i get time so search for bugs or elaborate my ideas...)

It's no problem of course. :)

**Comment by Quicksaver** [comment]
In [beta version 2b5](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b5) you can now right click a tab in groups view to access its context menu, and from there if you click "Bookmark all tabs", it will do that for all tabs in that group. Please give it a try and let me know if you find any problems.

Also note that there were a lot of changes in that beta since the last released version, so it's definitely worth it giving the "How To Use" page in the add-on's preferences a read, to get reacquainted with the basics.

**Comment by Pheil** [comment]
Wow, yeah lots of changes.  The bookmark option worked for me.
