### ISSUE TITLE
Incorrect display since Tab Groups became an extension

### ISSUE THREAD

**Issue by GrayFace** [Quicksaver/Tab-Groups#150]
Here's a screenshot: https://dl.dropboxusercontent.com/u/44735333/tmp/TabGroupsBug.png

**Comment by Quicksaver** [comment]
This seems like another add-on, theme or userstyle conflicting with the display. Can you try disabling all themes and extensions except for Tab Groups and see if it helps?

**Comment by Quicksaver** [comment]
It's extremely unlikely this is still an issue in [beta version 2b5](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b5). Please give it a try and let me know if you find any problems.

Also note that there were a lot of changes in that beta since the last released version, so it's definitely worth it giving the "How To Use" page in the add-on's preferences a read, to get reacquainted with the basics.
