### ISSUE TITLE
issues with firegestures and new tab context menu in tabview

### ISSUE THREAD

**Issue by mausalimi** [Quicksaver/Tab-Groups#183]
hello,

i tried the newest code, and it turned out there is a slight problem together with firegestures (https://addons.mozilla.org/de/firefox/addon/firegestures)

i need the right mouse button to draw a gesture, and i also do that to access groups view. now when i release the right mouse button, i get the groups view, but instantly the context menu from the tab where the mouse pointer sits pops up. also that tab gets active.

is there an easy way to fix this? maybe some short delay after switching to groups view?
or can i easily delete some of the new code to get rid of the context menu again (as i rarely use it anyway). that would be fine for me, as i might be the only one using that extension combination.

anyway, also something else i noticed: most of the time when i click to get the context menu in groups view, firefox fails to respond a few seconds (sometimes up to about 10!), which makes the whole thing even worse, of course.
but this might be a conflict with some other extension too, i need to check this by starting deactivating extension.

**Comment by Quicksaver** [comment]
> i need the right mouse button to draw a gesture, and i also do that to access groups view. now when i release the right mouse button, i get the groups view, but instantly the context menu from the tab where the mouse pointer sits pops up. also that tab gets active.

I'll see about fixing this, I'm sure it's annoying. :) I'll let you know as soon as I upload a new beta for you to try out.

> most of the time when i click to get the context menu in groups view, firefox fails to respond a few seconds

This is actually expected. Almost all of the actions in that context menu (including many from other add-ons that I can't predict), require the tabs bar to show only the tabs from the active group, in order for those actions to work correctly. For instance, when you click "Bookmark all tabs", it's supposed to only bookmark tabs from the active group (from the group to which the tab where you right click belongs).

Usually, the tabs bar only updates when you leave tab view, as in you can make many changes to your tabs and groups in groups view but those are only actually applied when you leave it. But since many of the actions in the context menu require an updated tab bar, that delay is because it is applying all necessary changes, so that the menu that appears works correctly.

I agree, it's not optimal as it is. I still want to try and improve performance there, but honestly I'm not sure there's much to be done. The more groups and tabs you have, the more it has to work. There's only so much I can improve there. :(

**Comment by mausalimi** [comment]
i see. on my older laptop i5 as said it takes really time to get the context menu. i tried in a clean profile with only 2 groups and few tabs, there it was really fast.

as for the firegesture problem, if it can fixed easily, fine. if not, i need to find myself some workaround. for now, i'm just using the code up to commit 14a27f889660b. which works really great, btw.

thanks a lot.

**Comment by mausalimi** [comment]
oh... just NOW i wanted to let you know to not bother any longer, as i simply removed the code that brings up the context menu (as said i don't need it in group view).

anyway, i will test it. there is still a chance  that other people use the same extension combination.

thanks!

**Comment by Quicksaver** [comment]
> anyway, i will test it. there is still a chance that other people use the same extension combination.

Exactly, not everyone can change the add-on's code for themselves. ;)

**Comment by mausalimi** [comment]
ok, it seems to work fine, no more "automatic selection".

**Comment by Quicksaver** [comment]
In [beta version 2b5](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b5) for whoever doesn't want to build from the code. :)
