### ISSUE TITLE
Reduce thumbnail footprint

### ISSUE THREAD

**Issue by the8472** [Quicksaver/Tab-Groups#185]
#47 already cut down most of the fat, but `<canvas>/`<img>` elements still seem a bit wasteful at the moment.

I think the lifecycle should be as follows:

- set the CSS to a white background, i.e. don't draw anything at all by default
- try to retrieve cached image and only show that if it exists
- only create canvas if the tab actually exists (about:blank -> no canvas!), discard `<img>` after canvas has been drawn, this allows the image memory to be unloaded.
- if a tab has not received any paint events for X minutes and has a canvas, convert the canvas into a jpeg + blob URI, discard canvas, create `<img>` again

The advantage of canvas is obviously that we can draw animated tabs with decent speed. But switching back to images allows the browser to handle their memory more efficiently because it can discaard the pixel data when the tab view has been closed because it can create them from the compressed representation.

**Comment by Quicksaver** [comment]
> - set the CSS to a white background, i.e. don't draw anything at all by default
> - try to retrieve cached image and only show that if it exists

This it already does, more or less. The background of both the canvas and the cached image is white. The cached image is only loaded if it exists of course. When there isn't a cached image for a tab, it just doesn't load anything (shows the blank square along with the usual image doesn't exist frame/icon).

**[Second read:]** On reading again what you wrote I probably misunderstood you at first. If you meant only actually create the ```<img>``` element when there is an image to show. That's a good optimization as well.

> only create canvas if the tab actually exists (about:blank -> no canvas!)

Does an empty canvas take up much memory? I never checked for this, but I doubt it's that much, especially because the canvas in this case has ```display:none;```. If an empty, non-displaying canvas is taking up much memory space, it's definitely worth more filing a bug for this to be fixed in Gecko itself (of course the add-on could still apply your suggestion in the meantime as a local fix).

**[Second read:]** I probably misunderstood you here as well. Creating the canvas only when it is actually needed can definitely help.

> discard <img> after canvas has been drawn, this allows the image memory to be unloaded

Good point.

> if a tab has not received any paint events for X minutes and has a canvas, convert the canvas into a jpeg + blob URI, discard canvas, create <img> again
> 
> The advantage of canvas is obviously that we can draw animated tabs with decent speed. But switching back to images allows the browser to handle their memory more efficiently because it can discaard the pixel data when the tab view has been closed because it can create them from the compressed representation.

I agree with the theory. But how much are you expecting to gain here? I'm sure that processing the image will take a lot more on the processor than holding the canvas; so in other words, would the gain from releasing that memory compensate the loss (higher requirements) in processing? I wouldn't want to slow down the browser unnecessarily, even if for just a second, to create that image. I believe holding a few extra kbs in memory for each canvas would be far better (**if** that was the case of course).

Note that I'm not discarding your suggestion at all. Canvases also take a larger toll on flexboxes, which is what it now uses to arrange tabs in a group. So that's yet another reason for having less of them! :) It's only this last point of going back and forth between canvases and images that worries me.

**Comment by iShyboy** [comment]
As a tab heavy user (~300+ ) I would like to see it.
If you could process the image only when needed (Like when you open single view, or stacked groups, show only what's needed). I don't think the load on computer would be great, but it's quite hard to restart the browser every now and then.
![ff](http://i.imgur.com/y1P0SBZ.png)
Browser is up for about 9 hours.

**Comment by the8472** [comment]
> I'm sure that processing the image will take a lot more on the processor than holding the canvas;

Hence the idea to only do it if it hasn't received any paint events for a while. That should make it a rare operation, thus limiting its potential CPU impact.

Alternatively we could skip the canvas-to-jpeg step and and use the cached image thumbnail, if present. In this case the drawback would be a stale thumbnail.

Also, according to [bug 817700](https://bugzilla.mozilla.org/show_bug.cgi?id=817700) the encoding happens on a separate thread, so it shouldn't affect responsiveness.

**Comment by Quicksaver** [comment]
> Also, according to bug 817700 the encoding happens on a separate thread, so it shouldn't affect responsiveness.

That's good!

@the8472, I'm actually about to start some enhancement work to the thumbnails on another matter (the ridiculous aspect ratio they have now for instance). But if you have any WIP on this, I'll do something else first as I'm sure one of use would have to re-do a lot afterwards. Otherwise, I'll tackle this at the same time. :)

**Comment by the8472** [comment]
It's all yours.

**Comment by Quicksaver** [comment]
> set the CSS to a white background, i.e. don't draw anything at all by default

After testing things a bit, I think this point is not worth pursuing (the ```<img>```'s background is already white, so visually there isn't any change at least).

Creating tab items and their thumbs come from either two general cases:
- during startup, where almost all tabs are not yet loaded, so more than likely we'll be using cached thumbs in those. The extra step of creating an empty background and then just adding an ```<img>```  on top or replacing it is unnecessary, might as well start with the ```<img>``` directly.
- when opening new tabs, where we're almost sure we'll be using a live thumb in a canvas as soon as the tab is loaded, if it isn't already. Skipping the cached thumb here could help. But it might be worth more showing a cached thumb while it fetches the live thumb into the canvas (which is never immediate). If the thumb exists, it will more than likely be similar enough to the live thumb, that you won't notice the difference, and it'll seem like it's just that much faster.

But!

> try to retrieve cached image and only show that if it exists

This actually doesn't seem possible. ```PageThumbs.getThumbnailURL(url);``` returns a "valid" thumb uri, regardless of if the thumb exists or not, and there's no way to know until the ```<img>``` actually loads or not.

So!

Since we can't seem to detect whether there actually is a stored thumb for the tab or not, it might not be worth skipping it in any case.

So for now I think it's fair to skip those two points.

**Comment by Quicksaver** [comment]
> only create canvas if the tab actually exists (about:blank -> no canvas!)

There are also add-ons and userstyles that customize about:blank pages, it'd be weird to not have the thumbnail reflect that. So skipping this part as well unless you disagree.

**Comment by Quicksaver** [comment]
Although you could make the case that those add-ons and userstyles could also customize the blank thumbs in the same way. But meh, why complicate I guess. :)

**Comment by the8472** [comment]
> After testing things a bit, I think this point is not worth pursuing (the <img>'s background is already white, so visually there isn't any change at least).

Yes, I meant that the background of the thumb should be white, so that it's always white even if no image is present. there shouldn't actually be any JS code setting background colors.

> returns a "valid" thumb uri, regardless of if the thumb exists or not

you can create the image element outside the DOM tree and await its load/error event and only insert it into the tree when it actually loads

> There are also add-ons and userstyles that customize about:blank pages,

Empty tabs generally use about:newtab now. about:blank is mostly, although not exclusively, used by lazy-loaded tabs after session restore. I guess we could be a little bit smarter and check if the tab URL mismatches the actual document url, i.e. detect whether it's a lazy tab and just avoid attempting to render the canvas for the lazy tab, because it won't work anyway.

We can still try fetching the thumbnail if we have one, but that only needs to be done once.

---

Anyway, my basic idea is to have a clean tri-state logic between which each tab can transition:

* empty
* img
* canvas

Combined with skipping about:blanks and discarding canvas when it doesn't receive any paint events this can cut down both on canvas update attempts (CPU load), calls to the thumbnail service and image data kept in memory.

Those may seem like edge-cases to you but I have lots of white tabs because the thumbnail service loses a lot of thumbnails for one reason or another and yet tab groups is constantly spinning at 100% CPU load attempting to render things.

**Comment by Quicksaver** [comment]
> you can create the image element outside the DOM tree and await its load/error event and only insert it into the tree when it actually loads

Good point!

> i.e. detect whether it's a lazy tab and just avoid attempting to render the canvas for the lazy tab, because it won't work anyway.

I may be missing something. In those lazy tabs, the canvas already isn't rendered at all, it just shows the cached thumb for whatever page it will open later. See:
https://github.com/Quicksaver/Tab-Groups/blob/master/resource/modules/TabItems.jsm#L720-L737
https://github.com/Quicksaver/Tab-Groups/blob/master/resource/modules/TabItems.jsm#L796-L804

**Comment by Quicksaver** [comment]
Unless I missed something or misunderstood your previous comment, with those two commits the first three points of your suggestion are done.

> - set the CSS to a white background, i.e. don't draw anything at all by default
> - try to retrieve cached image and only show that if it exists
> - only create canvas if the tab actually exists (about:blank -> no canvas!), discard <img> after canvas has been drawn, this allows the image memory to be unloaded.

Next up is:
> - if a tab has not received any paint events for X minutes and has a canvas, convert the canvas into a jpeg + blob URI, discard canvas, create <img> again

Do you have any suggestion for X? I was thinking 20 minutes, but I may be too biased by my own browsing habits there, so I'm open to suggestions.

**Comment by the8472** [comment]
> I may be missing something. In those lazy tabs, the canvas already isn't rendered at all,

Strange, I thought I saw trying to update tabs I hadn't touched. I guess i'll have to take another look at it with the debugger.

> Do you have any suggestion for X? I was thinking 20 minutes, but I may be too biased by my own browsing habits there, so I'm open to suggestions.

I think pacing, the pause between each canvas-to-image-conversion, is more important than the initial delay because we want this to happen when the tab view is closed to reduce memory footprint. It only has to happen once per tab as long as the view is closed. It should only transition back from image to canvas when it receives a paint event and the view gets opened, so there would be little risk of it switching back and forth too frequently, i think.

So I would say 5 minutes delay until conversion and at most one conversion per second or something like that?

**Comment by Quicksaver** [comment]
I found out something less than awesome... The add-on uses MozAfterPaint events to know when to update a canvas, which to be fair is probably the most reliable way to know when a tab has had some visual change.

Except those MozAfterPaint events fire on every loaded tab (even about:blank tabs) when leaving tab view, they fire in the background for pretty much every little thing... So it's just impossible to consider a tab "stale", because as long as the window is in view, they technically never are.

I'm against using something other than MozAfterPaint that isn't as visually accurate; for instance progress listeners as there are all sorts of ways to change the layout of a webpage without firing those. But I'm definitely open to suggestions that are at least comparably accurate!

I would say the best method would be to add an (auto) unload tab feature, which would also destroy its canvas in tab view. I've been considering adding this for a while, so it's just one more reason to do it at this point. (BTW I've seen the code of add-ons that unload tabs, and it's just not practical to follow their actions in here.)

**Comment by Quicksaver** [comment]
Of course, there's also a middle ground where the canvas can be discarded based on the last time the tab was actually selected. That may be worth pursuing, at least as a temporary measure until I get to the unload features (which to be realistic won't happen for a version 2 release).

**Comment by Quicksaver** [comment]
(Forgot to mention, which would bring back the canvas on location/state changes of course.)

**Comment by the8472** [comment]
Hrm, I would prefer to have canvas unload separate from tab unloading. Tab state is far more important to me than the tiny squiggles on the canvas.

Yeah, time-since-last select would be an easy approach. An alternative might be trying to filter out some paint events.

The question is whether some users do want background tabs to be continuously painted whenever they're updated. It might be useful for some kind of dashboard use-case where you want to see if something new happened on several tabs without actually touching all of them.

It's a difficult balance to strike.

Maybe just offering an option that allows the users to choose a liveness vs. memory tradeoff.

**Comment by the8472** [comment]
I think it might be as simple as starting to discard canvas elements one by one N minutes after the tab view has been closed. There's just no point in doing some fancy logic to keep the canvas elements around.

When the tab view wants to refresh a tile continuously, and it needs to be open for that, then we need a canvas, at all other times an image will do. The timeouts/pacing are only needed to keep it from flip-flopping between those states too much.

**Comment by Quicksaver** [comment]
> The question is whether some users do want background tabs to be continuously painted whenever they're updated. It might be useful for some kind of dashboard use-case where you want to see if something new happened on several tabs without actually touching all of them.

Exactly.

> I think it might be as simple as starting to discard canvas elements one by one N minutes after the tab view has been closed. There's just no point in doing some fancy logic to keep the canvas elements around.
> 
> When the tab view wants to refresh a tile continuously, and it needs to be open for that, then we need a canvas

This means that as soon as tab view opens, all those canvas need to be recreated. which as things stand means literally all loaded tabs. Right now it just has to repaint them, but re-creating them **could** in theory take a toll.

Doesn't hurt to try though.

**Comment by the8472** [comment]
Well, it should do so one by one, while also waiting on the thumbnail service. And I think the latter probably is the bottleneck since it actually has to touch all those huge tabs (as far as pixels go) and squeeze them into a much smaller canvas.

**Comment by Quicksaver** [comment]
> An alternative might be trying to filter out some paint events.

There isn't much to filter, other than timestamps [they don't really carry a whole lot of different info](https://developer.mozilla.org/docs/Web/Events/MozAfterPaint). :( It already filters out events that don't have any clientRects (no areas that were painted), although to be honest I've not yet seen an event that doesn't have at least one of those.

Otherwise you make very good points. While tab view is hidden, canvases don't really matter after all. In the latest commit I've implemented it exactly as you suggested:
- while tab view is hidden, the tab canvas is turned into an img and then destroyed;
- there is a maximum of 200ms operation limit at a time, which I've seen usually fit about 3 or 4, and as much as 11 canvases per cycle (it's the same limit for painting canvases, except it usually only paints one or two in that time), this will vary depending on the system of course, but mine's pretty low-end right now so I think it's a good number;
- seeing as how at least part of it happens off main-thread, the UI doesn't seem to lock at all at any point (yay!);
- I've set a 20s wait time between cycles (I actually did most testing with a 5s cycle with zero lag/lockups with a moderate amount of tabs in a busy system), together with the 200ms op limit, it should not impact browsing at all (for reference, painting canvases happens on a 200ms cycle);
- seeing as entering tab view can have a slightly larger impact now since it has to potentially create the canvases in addition to just painting them, the operation limit now also takes into account any async operation (which either was the original intention and I strongly believe it was a bug in the original code, or I just screwed up when first porting it); honestly I didn't really notice any practical difference myself on this point, probably because as above most of it happens off main-thread anyway.

What do you think? And most importantly, as the one of a thousand tabs, how does it feel? :)

**Comment by Quicksaver** [comment]
Bonus patch: destroy the cached thumb as well if it won't be shown ("no tab thumbnails" option).

**Comment by the8472** [comment]
Looks good. There are some amazing improvements to the responsiveness of the tab view.

Memory footprint is a bit harder to see in the task manager (usage easily swings by +-500MB for me), but based on about:memory stats it looks good, e.g. fewer MB in canvas pixels.

As far as steady-state memory usage and CPU load goes it looks like we have all low-hanging fruit plucked.

I think there might still be a few tiny leaks and some inefficiencies during startup/first load. I'll file issues or a PR once I get around to isolating them.
