### ISSUE TITLE
Text in Option Windows is to far...

### ISSUE THREAD

**Issue by mikhoul** [Quicksaver/Tab-Groups#2]
Small bug: Text in Option Windows is to far...

![http://i.imgur.com/682eiha.png](http://i.imgur.com/682eiha.png)

Also could you tell me if "**TabGroups Menu** " is or will be compatible it is VERY useful to swap quickly from one group to another. https://addons.mozilla.org/en-US/firefox/addon/tabgroups-menu/

Best Regards ! :smiley:

**Comment by Quicksaver** [comment]
That's not a bug, it's meant to be that far so that it's always out of the way when moving the mouse over preferences that have help texts. Notice that it starts roughly where the actual preferences area ends (at the limit of the text in the block "Keep Tab Groups across restarts" at the top). ;)

I don't know about TabGroups Menu as I haven't tested it. You could try it yourself and see. :) It *should* work though as my add-on keeps most of the front and backend from the native Firefox Tab Groups (for now at least). If it doesn't, then I'm sure adding compatibility between both add-ons shouldn't be too hard, although it might be necessary to make some changes to TabGroups Menu as well, so you might want to ask its author about it as well.

**Comment by mikhoul** [comment]
I tried the addon but sadly it don't work with TG :worried:

I tried few week ago to reach the dev but he did not answer, at least the code is open https://github.com/char101/tabgroupsmenu .

Regards !

**Comment by Quicksaver** [comment]
You could give [Simplified Tab Groups](https://addons.mozilla.org/firefox/addon/tab-groups/) a try. It's more recent and could not be perfect yet, and it's slightly different but should work in a similar way for that case.

Right now its current version 0.1.1 isn't compatible with this add-on, so you'd have to choose between one and the other, but its next version (0.2.0 or whatever it ends up being) should be fully compatible with Tab Groups, so you'll be able to use both at the same time when it's released.
