### ISSUE TITLE
Undo Close Tab no border in Single view

### ISSUE THREAD

**Issue by yfdyh000** [Quicksaver/Tab-Groups#205]
It is a style? I feel it is a rather vague concept, a flat group is a clickable button. Although the user can notice because just touch it, but a little perplexed, because they do not know it is a label/button/menu or something.

A background or border may be more clear, but may also undermine the flat style, especially the user has some kind of theme?

**Comment by Quicksaver** [comment]
The undo close tab button is actually the whole "group" button at the top. I've already fixed some of its styling, so that the words don't wrap so easily (I don't remember in which commit it was though, as it was part of something else).

I'll post a beta here when I upload it for you to try out and confirm it's more intuitive now.
