### ISSUE TITLE
Re-ordering tabs by directly dragging in tab bar not then reflected on tab group order menu

### ISSUE THREAD

**Issue by sugob** [Quicksaver/Tab-Groups#210]
Hi
GREAT add-on :-)
Small issue: if I re-order some tabs by directly dragging on the firefox tab bar, if I then click on the TabGroups icon and open the corresponding tab group lists the tabs in the original order [bug]. If now click 'Manage my groups' and then immediately click '-' to exit this menu, then going back into view the tab list it is now showing the new order. Add/deleting tabs directly on tab bar does seem to refresh the list correctly :-)

Using TabGroups v2b6 [with 6 groups], Firefox 45.1.1 Win7, TabMixPlus, SessionManager

P.S. Not entirely sure all that red on the 'Manage my groups' looks the best. Seems to be based on if tab contents loaded or not [?] - could instead base icon text on corresponding on each tab attributes/contents so would pickup that Tab Mix Plus has set the tab text font [i.e. colour, italics, bold] based on if tab is loaded etc

**Comment by Quicksaver** [comment]
> if I re-order some tabs by directly dragging on the firefox tab bar, if I then click on the TabGroups icon and open the corresponding tab group lists the tabs in the original order

Good catch. This should be fixed in [beta version 2b7](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b7).

> P.S. Not entirely sure all that red on the 'Manage my groups' looks the best. Seems to be based on if tab contents loaded or not [?] - could instead base icon text on corresponding on each tab attributes/contents so would pickup that Tab Mix Plus has set the tab text font [i.e. colour, italics, bold] based on if tab is loaded etc

I understand what you mean. At first it was a little weird for me as well, seeing all that color. But I believe that could be mostly because you're not used to it. Give it a few days and see how your eyes adapt, they're obviously used to seeing mostly a blank/blue color after all. If after a while you still believe this can be improved, just let me know and I'll be sure to see what I can do. :)

BTW, that's exactly what it does, it uses the color you set in TMP's settings for unloaded and unread tabs.
