### ISSUE TITLE
On 'Manage my groups', creating extra row in Tab Group just to show the tab add '+' icon  

### ISSUE THREAD

**Issue by sugob** [Quicksaver/Tab-Groups#212]
Hi

On 'manage my groups', if there are the correct [or should I say incorrect?!] number of tabs in Tab Group, then creates extra row in Tab Group just to show the tab add '+' icon [see attached image].  - another of my tab groups also has this issue & is 12 tabs wide so even more wasteful of screen space [especially on 'Grid Display' and 'Free Arrange' views]

![tab-groups_addtabissue](https://cloud.githubusercontent.com/assets/17132026/15275528/32fb8ac6-1a9c-11e6-8262-bb01f8100cfa.JPG)

I don't really need/like this '+' icon - I can easily add a tab by double clicking in tab bar. Could add a config option to always disable displaying this '+' [rather than only showing '+' when space on current line?] & default it to on for backwards compatibility? 

This is the Tab Add '+', not the TabGroup add '+' 

On '+' related issue, I noticed that in 'Manage my groups', the Tab add '+' icon always appears for the currently active tab group - if move mouse pointer to other groups it only appears whilst in them [and still shows in the active tab group so you see 2 '+' icons]

TabGroups v2b7 [thanks for fixing #210 :-)], Firefox 45.1.1, Win 7 [64 bit]

M

**Comment by Quicksaver** [comment]
As you've probably guessed, that is working as it's expected, it adds the extra row because it considers the new tab button another item like any other tab item.

I had thought about making the new tab button optional, decided against it because it's adding a degree of complexity for very little gain. It's very little often that you have the exact number of tabs (and keep them throughout a period long enough to make any difference) where this would save a line. And to be perfectly honest, if I were to add such an option it would be more because of the wasted space in groups with a low number of tabs like in #192, although it wouldn't help much there either.

> On '+' related issue, I noticed that in 'Manage my groups', the Tab add '+' icon always appears for the currently active tab group - if move mouse pointer to other groups it only appears whilst in them [and still shows in the active tab group so you see 2 '+' icons]

Also expected, to be more touchscreen friendly where you can't really move the cursor over anything.

**Comment by sugob** [comment]
Ok. Yes, it currently works perfectly well & my observation is a bit of an edge case - I should have put the word enhancement somewhere. I assumed the '+' icon always exists in each TabGroup [so the height of the TabGroup takes this into account] but hidden/unhidden with pointer focus moves out/in a TabGroup? I'll just keep one less tab in each group afflicted
I think it's more that I don't really like the '+' being there at all - when in 'Manage my groups', as I move the pointer around TabGroups  then the '+' unhiding/hiding is like a distracting flicker

Anyway, keep up the good work

M

**Comment by Quicksaver** [comment]
I will definitely try to work out some alternative ways to show the new tab button as part of #192, so hopefully they will address your issues at the time as well. :)
