### ISSUE TITLE
Undo Close Tab Button

### ISSUE THREAD

**Issue by tevi** [Quicksaver/Tab-Groups#223]
I see you can undo a close tab group but I don't see how to undo a single tab that was closed.

**Comment by Quicksaver** [comment]
There isn't a button in groups view for that because it's not Tab Groups handling that action at all. You can undo closing a tab using the [Ctrl+Shift+T shortcut](https://support.mozilla.org/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_windows-tabs) from within and outside groups view.

Maybe there's room to include this functionality within Tab Groups, but that requires quite a bit of work, and that just won't happen any time soon as there are a bunch of other features I'd rather give priority to (in addition to porting the add-on to a WebExtension).

(BTW, I think [Tab Mix Plus](https://addons.mozilla.org/firefox/addon/tab-mix-plus/) includes a toolbar button to undo a closed tab, as well as a dropdown menu in the tab context menu to restore one of the last X closed tabs. Might be worth checking out.)
