### ISSUE TITLE
Keeping tab groups acroos restarts

### ISSUE THREAD

**Issue by LAOMUSIC** [Quicksaver/Tab-Groups#227]
I would like to use this feature but it just crashes EVERYTIME ! Very unstable.
The option to "Show my windows and tabs from last time" is greyed out.
How to solve this ? 
![firefox option](https://cloud.githubusercontent.com/assets/1581277/15625468/cad52158-24a7-11e6-8a18-4fc0470264de.png)
![otiongrey](https://cloud.githubusercontent.com/assets/1581277/15625470/d57e1aba-24a7-11e6-8b81-830e7786ad98.png)

**Comment by Quicksaver** [comment]
> I would like to use this feature but it just crashes EVERYTIME ! Very unstable.

Do you mean that, using those settings to remember your windows and tabs, Firefox crashes? Can you please try in a [clean profile](https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles) and see if it also crashes there?

> The option to "Show my windows and tabs from last time" is greyed out.

That's because it's already remembering the session across restarts. That button is only a shortcut to changing the preference "When Firefox starts" to "Show my tabs and windows from last time". I've already changed the way in which this button is shown for the next version, to avoid confusions like these.

**Comment by Quicksaver** [comment]
Please reopen if this keeps happening and you have any more info.

**Comment by LAOMUSIC** [comment]
Solved ! Firefox people and their updates...
Thanks any way QuickSilver !
