### ISSUE TITLE
Tab groups stopped working with release 2

### ISSUE THREAD

**Issue by prd60** [Quicksaver/Tab-Groups#239]
I'm running ff 46.0.1 on Windows 7; earlier today, the browser was silently updated to Tab Groups version 2, and tab groups stopped working:

- no icon on the tool bar
- Shift Ctl E has no effect
- right clicking on a tab does not have the "move to group" menu item

I tried disabling all add-ons to no effect.

**Comment by iShyboy** [comment]
Can you try clicking on "reset to default" button on customize menu? The button reappeared here after I did this.

**Comment by prd60** [comment]
"Restore defaults" had no effect

**Comment by johnwalicki** [comment]
My Firefox 45 ESR browsers has the same problem.  Installed Tab Groups v2 and tab groups is not working.

**Comment by Quicksaver** [comment]
It's working just fine for me on 45 and 46. Are you sure the add-on is enabled in your add-ons manager? Have you tried downloading again? It could have failed to install properly for some reason.

**Comment by shelbyi** [comment]
Hi, I am running ff v. 45.1.1 on my mac. Experiencing the same issues as already described. If I close Firefox it is asking me if I really want to close all my open tabs, however, I cannot switch to different tab groups and the button to enter the "tab groups view" is gone.

**Comment by Quicksaver** [comment]
@shelbyi are you perhaps having the issue described in #230 instead? Can you use the keyboard shortcut (Ctrl+Shift+E) to enter groups view?

**Comment by gerhardh63** [comment]
Same here on WIN7 with FF ESR 45.1.1, groups not present anymore and (Ctrl+Shift+E) do nothing. Reset to default also doesn't help me too.

**Comment by Quicksaver** [comment]
Have you tried this:
> It's working just fine for me on 45 and 46. Are you sure the add-on is enabled in your add-ons manager? Have you tried downloading again? It could have failed to install properly for some reason.

**Comment by Quicksaver** [comment]
And have you also tried disabling all your other add-ons and see if it works then?

**Comment by QuantumDamage** [comment]
Hi,
I have the same problem with 46.0.1 and Windows 8.1. I restored plugin setting to default, and I removed it and installed again. Still no Icon, keyboard shortcut and tab groups.

**Comment by shelbyi** [comment]
@Quicksaver Enabled my other plugins, removed the "Tab Group" plugin, restarted ff and installed "Tab Group" again. Also enabled the other plugins and it is working again :+1:  ... I guess the old icon is gone, since now, I have a drop down menu instead which also includes the old icon though.

**Comment by gerhardh63** [comment]
Was enabled. Disable/enable, reinstall and ff restart doesn't help.
After disabling all other add-ons and ff restart it's back working.
After enabling "IBM 2.2.4 CCK - Customizations to enhance the browsing experience inside the IBM intranet" stops working again. All other add-ons I was able to re-enable without this problem.
Just to let you know, your older version worked fine also with this IBM add-on.

**Comment by Quicksaver** [comment]
@shelbyi as explained in the release notes, that is a new feature which can be disabled in the add-on's preferences if you want.

@gerhardh63 where can I find that add-on?

**Comment by gerhardh63** [comment]
I think this is just IBM internal, will life without it, was per default installed here at IBM.

**Comment by Quicksaver** [comment]
It may be worth giving its developers a heads-up then, if it worked before, I'm sure any compatibility fixes should be fairly minor.

**Comment by jmp242** [comment]
I'm having the same issue on ESR45.1.0 under Scientific Linux 7 at work. What's weird is I have a very similar setup at home, same OS, same Firefox, and Tab Groups 2 worked fine (except for ugly red tab outlines and needing to reset to the old prefs everything). At work, I've tried restarting firefox, disabling all extensions, uninstalling and re-installing Tab Groups 2. Nada. No button, keyboard shortcut doesn't work either. I can see prefs for the extension. Tab Groups button extension does let me access my tab groups anyway, but without that other extension I have NO access to tab groups on this PC.

I see the CCK which is a configuration extension. I use that also at work for configuration, it's a tool to provide policies to Firefox. It's not just IBM. The extension (which lets you build configs, it's not the same as the policy that is deployed exactly - but in FF45ESR and newer that deployment is autoconfig based, not actually a hidden system level extension. see:
https://mike.kaply.com/cck2/

I'm going to reach out to Mike as I believe I have a support contract, but it may be worth making a bare bones policy with that for testing with Tab Groups 2. v1 worked since FF45ESR came out with that extension however.

**Comment by Quicksaver** [comment]
Thank you for that link! I'll be sure to check it out as well, to see if I can fix it from my side.

**Comment by jmp242** [comment]
I don't know if you can see this without a contract, but here's my corresponding support request. I hope this can be fixed.
http://cck2.freshdesk.com/support/tickets/462

**Comment by mkaply** [comment]
If you have any questions about the CCK2 or need me to figure something out, let me know.

**Comment by rjameson3** [comment]
I happen to be on FF47, but the TG update just broke - I see an empty line where the group tabs should be, I can right click and see the add-on options to make new - but all groups are not showing up.  Cannot even add a new group.

**Comment by Quicksaver** [comment]
@rjameson3 I have no idea of what you mean. Could all of that come from another add-on?

**Comment by lucasvel** [comment]
I have the same issue with the "IBM 2.2.4 CCK - Customizations to enhance the browsing experience inside the IBM intranet". If I disable it, TG works again (and also other addons that stopped working with FF45)

**Comment by rjameson3** [comment]
Hi Luis…below you will see at the arrow – that is the tab groups area, no tab groups anymore.  I can right click to see menu, but when I manage the groups – there are none, when I try to add a group, it does not anymore.   This all started with the update that hit me today.   I will try to turn off all my add-on's, but it was all working fine last night.

Ron


[cid:image001.png@01D1BCC1.229846D0]

**Comment by Quicksaver** [comment]
Please don't attach images when replying directly to github e-mails, you'll have to post them directly in the issue otherwise it won't work. ;)

**Comment by rjameson3** [comment]
I am not getting this to work consistently…I disabled a bunch of extensions, then the TG bar shows my groups, then I re-enabled more to get TG bar to not show my groups, then back again – but when I thought I had it pinned down to one (about:addons-memory 2016) – then as I toggled it – TG would not work again.    I reopen FF several times then it would work.   Making no sense at the moment.

Stumped…

**Comment by Quicksaver** [comment]
Seriously, I need an answer to this: what groups bar? Does that come from [Tab Groups Helper](https://addons.mozilla.org/firefox/addon/tab-groups-helper/), which should be perfectly compatible with Tab Groups, or from another add-on?

**Comment by iShyboy** [comment]
It's just cck, with the mike one, just skipped everything and made a addon and installed it, after that TG vanished from sight. Didn't matter if I made any change it was the same.

**Comment by rjameson3** [comment]
When I say TG bar - I am referring to the Tab Groups themselves.   If that is controlled by the Tab Groups Helper...then is this a TGH issue?    I know long ago, we had to load the TGH in order for this to work.

**Comment by Quicksaver** [comment]
Yes it's probably a TGH issue (if it's not the same cck thing as for the others), but TGH was working just fine with Tab Groups 2 when I tried it. I'll be sure to take another look though.

**Comment by rjameson3** [comment]
Wow..sorry, I had that all totally flipped backwards...so "TG Helper" was my original app to group my hundreds of open tabs into groups (to replace the deprecated Tab Manager extension from years ago)...then at some FF update, I was required to load your TG extension to continue allowing it to work.   I will go to the TG Helper support and see what I can find...if I do, I will report back.

**Comment by Quicksaver** [comment]
@rjameson3 are you sure that Tab Groups Helper is also updated to the latest version? And that you're not having the same cck issue as above? I just heard from TGH's developer and everything works fine for him as well.

**Comment by czackwaltz** [comment]
Cross post from #267. IBM CCK 2.2.4 (updated 2015-12-22) seems to be the culprit. After I disable and restarted, I got the Tab Group icon back. If I reenabled IBM CCK 2.2.4, the Tab Group icon disappeared.

**Comment by prd60** [comment]
There have to be other reasons for this issue: I do not have IBM CCK 2.2.4 installed.

**Comment by Quicksaver** [comment]
@prd60 check my other comments. Is the add-on enabled? Have you tried re-downloading (corrupted installation file)? Does it work in a [clean proflie](https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles)?

**Comment by Quicksaver** [comment]
Can you access the add-on's preferences from the addons manager? If yes, is the shortcut active in there?

**Comment by iShyboy** [comment]
If the uncheck of those 2 options and tap "restore to defaults" in customize box, didn't work, you can try disabling every single addon except Tab Groups, and try again.
The Mike CCK that @jmp242  mentioned earlier hide the CCK as any other extension (of your choice), it can even be hided from addon manager and bundled in the FF directory.

**Comment by prd60** [comment]
It turns out my IT organization uses CCK2 to push certificates. I had to delete all CCK2 files/folders from the Mozilla Program Files folder before I could get Tab Groups to work.

**Comment by QuantumDamage** [comment]
@prd60 I also just found that I have CCK2 dir inside Firefox installation. Which files/dir did you deleted exactly? When I deleted CCK2 dir Firefox stopped to start, but I still had backup of this dir so I restored it and Firefox starts but as I can expect, without tab groups.

**Comment by vIr-s** [comment]
One way to disable CCK is to comment out the lines config lines in **autoconfig.js** (e.g. on Windows this file is in _C:\Program Files (x86)\Mozilla Firefox\defaults\pref\_ )

Reference: https://developer.mozilla.org/en-US/Firefox/Enterprise_deployment#Configuration

**Comment by QuantumDamage** [comment]
@vIr-s Another installation of Firefox helped. Thanks for hint ;)

**Comment by mkaply** [comment]
This is happenings because of the way the CCK2 blocks loading of certain files. I will fix in the CCK2, but this won't help until companies updated to that version. If you want to fix it in the extension, you can just make a local copy of chrome://browser/locale/browser.dtd and load it from your extension.

Nothing changed in the CCK2 around this so not sure why it just started happening.

**Comment by Quicksaver** [comment]
@mkaply that would mean this is the likely culprit: https://github.com/Quicksaver/Tab-Groups/commit/14a27f889660b80fb3060da37b4052f380ad92a0

I can't really create a local copy of that file (well I **can** but I wouldn't want to). That's being used to fill the context menu for text fields in groups view with the correct menu entries. A local copy would be subject to local localization as well, and it's an extra unnecessary burden on translators to translate something that already exists in the browser; possibly creating discrepancies with the originals.

For example, it would appear in english when the add-on doesn't have the locale of the browser. So (for the user) it would make no sense why those menus are in english and in their language throughout the rest of the browser.

Why is the CCK2 blocking this file in the first place?

**Comment by mkaply** [comment]
1. Text fields should get those menuitems for free. You shouldn't need to add the context menu yourself. If that wasn't happening, that's a different bug.
2. You're relying on a Firefox file that could change underneath you and break you again.

The CCK2 attempts to block users from loading system files in the browsers, otherwise you could type the URLs of XUL files to get into things that were blocked. I was clearly being overzealous in my blocking.

**Comment by Quicksaver** [comment]
> Text fields should get those menuitems for free. You shouldn't need to add the context menu yourself. If that wasn't happening, that's a different bug.

Absolutely agreed. And to be completely honest, I couldn't figure out exactly why the text fields in groups view didn't have this menu. I believe it is because groups view completely replaces the browser interface at almost the root level, and Firefox can only handle those context menus for text fields at a lower level somehow. Although that's barely more than speculation as I was not able to get at the root problem of this.

> You're relying on a Firefox file that could change underneath you and break you again.

True, but this is a locale file, which by tradition are kept unchanged in Firefox to avoid compatibility trouble and to facilitate their localization as well. As far as changing system files go, locale files should actually be the safest. And inside those, core strings for global things like "cut" and "paste" should probably be the safest of all. ;)

> The CCK2 attempts to block users from loading system files in the browsers, otherwise you could type the URLs of XUL files to get into things that were blocked. I was clearly being overzealous in my blocking.

Ah, that makes sense, I didn't realize that was the objective behind it. But yeah, a little bit I agree. :)

**Comment by jmp242** [comment]
I tested Mike's fix, which was a single file change in the CCK2 deployment, managed by Puppet here and a Firefox restart and now Tab Groups works again!

As he said, the companies managing the specific CCK2 policy will need to deploy this change, but it is pretty simple assuming they're managing the computer at all. That most of the users above even had permissions to disable CCK2 policy or delete the files implies that they're not really managed, so the users could make the change themselves 
https://github.com/mkaply/cck2wizard/pull/15/files
if they wanted to keep the policy for whatever reasons.

**Comment by Quicksaver** [comment]
Alright. First of all, everyone, I'm sorry I took so long to get to this.

I've tried CCK2.2 and it seems to work great together with Tab Groups now. @mkaply thanks for the fix!

For users of older versions, the next version of Tab Groups will apply the fix included in CCK2.2 in those older versions automatically, so that you don't need to wait for your distribution to be updated.

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) includes a fix for those older releases of CCK2, please everyone that had issues try it out and let me know how it works.
