### ISSUE TITLE
Website icons need to scale smaller

### ISSUE THREAD

**Issue by straitline** [Quicksaver/Tab-Groups#254]
The latest update has made the individual webpage icons larger, this takes up more space, making the tab groups less useful. If we could go back to the old size of icons that would be a step in the right direction. It would be even more ideal if the icons could scale even smaller so that more of them can fit in a smaller space before being scrunched into a single icon.

![screen shot 2016-06-02 at 7 35 33 am](https://cloud.githubusercontent.com/assets/10537209/15746639/a5570252-2894-11e6-9ecd-f10f25d8d2d6.png)

**Comment by Quicksaver** [comment]
By icon I assume you mean thumbnails. That's actually not possible, the thumbnails are already as small as possible. If they were made smaller, you could easily have inaccessible tab action buttons (like the mute button for tabs with sound), not to mention it would make the thumbnails so small they would barely be useful.

There are now other options to make better use of a group's space, like scrolling it instead of stacking the tabs, or hiding the thumbnails altogether.

**Comment by straitline** [comment]
Ok, well the icons were smaller before. Is there anyway to roll back to the previous version? It had a much cleaner interface overall and just worked.

**Comment by Quicksaver** [comment]
I can't recommend using the previous version, as it's full of problems (even if you're not aware of them). I **highly** recommend you give the new version a chance before deciding to downgrade.

If you absolutely want it, you can find it in the versions page of the [add-on's AMO homepage](https://addons.mozilla.org/firefox/addon/tab-groups-panorama/).

**Comment by straitline** [comment]
Ok, thanks for the help and quick responses.
