### ISSUE TITLE
Matching display aspect ratio wastes a lot of space on wide displays

### ISSUE THREAD

**Issue by mozbhearsum** [Quicksaver/Tab-Groups#258]
Ever since tab previews started using the same aspect ratio as the display, space has been effectively lost on widescreen displays in the "free arrange" view, because tabs are now wider. Having the previews wider doesn't really help readability (everything is too small anyways), so I'm struggling to see the benefit.

It would be nice to have an option to force them to squares, though I realize this might be a niche concern.

**Comment by Quicksaver** [comment]
I'm already considering ways to optimize the case for very wide screens. Although forcing them to be square I believe is a bit of an extreme measure, you would actually lose more information that way, as you wouldn't be able to see most of your tabs.

**Comment by FoxSox** [comment]
I certainly agree with this issue. I'd be perfectly happy for the thumbnails to be square (or for this to be an option) - after all they are only meant to give a flavour of what's on the page for quick recognition.

**Comment by bhearsum** [comment]
@Quicksaver Glad to here you're thinking about it! I agree that smushing them into a square is less than ideal, for sure. I wonder if cropping to a square might be better? That's still lossy, but it doesn't affect the content that would still be shown.

**Comment by Quicksaver** [comment]
> I wonder if cropping to a square might be better?

That was pretty much the previous behavior, it cropped the thumbnail to the top-left corner of the page. This was changed to show the full width of the page, because a corner is just not useful for many cases; easy one to picture are wikipedia articles, which have identifying photos and images on the right and not on the left, which would be cropped out completely.

**Comment by FoxSox** [comment]
IMO cropping to a square would be fine. For my purposes any picture which looks reasonably like the page is acceptable.

**Comment by Slater91** [comment]
The new behavior completely breaks the visual impact for me (29 groups open). Square previews are totally fine and are, in fact, preferable as they show you enough information without being too big. Groups which are shown with no stacking in version 1.x are suddenly stacked in version 2.x because of the lack of space introduced by same-aspect-ratio-as-monitor's previews.

**Comment by Sorunome** [comment]
I think this is related, when you have the developer console open the ratio of the visible area is way smaller and then the icons all looked squished when switching to the tab group view

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) now restricts tab thumbnails to show (roughly) the contents that would be shown on a 16:9 screen. This can be overridden with a constant ratio by setting the preference ```extensions.tabgroups.overrideViewportRatio``` to either a decimal number or a fraction in the form of ```[width]/[height]```, although I would argue it's not necessary with the automatic restriction at this point, but it's available nonetheless. Please give it a try and let me know how it works for you.
