### ISSUE TITLE
Some keys missing from the list when choosing shortcut modifiers

### ISSUE THREAD

**Issue by Aetf** [Quicksaver/Tab-Groups#26]
Great works! I was just worried about what alternatives I can use after the removal of builtin Tab Groups, right before I found your Add-on. Thank you very much!

However, I noticed that some keys are not available from the list when choosing shortcut modifiers.

- Ctrl+Alt+Shift: most complete list of keys, including letters, punctuation, function keys etc.
- Ctrl: some letters, punctuation, function keys
- Alt: only function keys
- Shift: only function keys
- Alt + Shift: only function keys

And even in the Ctrl+Alt+Shift case, there are some keys missing from the list.

I have seen [other add-on](https://addons.mozilla.org/en-US/firefox/addon/customizable-shortcuts/) that can actually use all possible key combinations without problems. So it should be possible to include all keys here. Is there any reason that not all keys are listed?

**Comment by Quicksaver** [comment]
First of all, you're very welcome. :)

The dropdown only shows you available key combinations. For instance, it will hide Ctrl+Shift+T because that's already being used as a shortcut to undo the last closed tab, but it will show you Ctrl+Alt+Shift+T because that's not used by anything (unless you have another add-on using that).

It's not a perfect system, there are some key combinations that are shown as available but are actually being used somewhere else. On the other hand, there may be some key combinations that are actually available but that are not in the dropdown (these should be rare though).

Most key combinations require Ctrl (Cmd on Mac) because:
- most of them serve a certain purpose by themselves;
- not to mention they actually input text, in many places even if you're not actually typing anywhere ("quick findbar" / "find as you type" comes to mind);
- Shift+Key usually only capitalizes characters so same thing as above;
- Alt+Key are typically reserved by the operating system.

**Comment by Aetf** [comment]
> * most of them serve a certain purpose by themselves;
* not to mention they actually input text, in many places even if you're not actually typing anywhere ("quick findbar" / "find as you type" comes to mind);
* Shift+Key usually only capitalizes characters so same thing as above;
* Alt+Key are typically reserved by the operating system.

Yes I agree with that, but still let me argue a little bit, just because I can't set my favorite keys (`Alt+Shift+E`) now :P

Using `Alt+Shift` as the modifier should be safe, as it won't trigger OS commands, won't input text, and there are few conflicts. I used `Alt+Shift+E` for a long time (by Customizable Shortcuts) and haven't notice a problem.

Could you consider mark `Alt+Shift` as safe and add the available keys to the list? Or would you accept such a pull request as I have read the relevant code, and the first impression is that should not be hard to implement?

**Comment by Quicksaver** [comment]
Hmm, maybe you are in another operating system, or using another locale that makes this key different from mine, but Alt+E (and Alt+Shift+E) opens the edit menu for me.

**Comment by Quicksaver** [comment]
Ah I see from your other thread that you are on linux, I wonder if those menus aren't triggered there using those shortcuts.

**Comment by Aetf** [comment]
`Alt+E` does open the Edit menu, but `Alt+Shift+E` doesn't.

**Comment by Quicksaver** [comment]
Weird, in my Ubuntu both of those work. I wonder if it's a limitation (feature?) of the Archlinux distro, where either the OS or Firefox in it don't recognize "e" and "E" as being the same in that case (because shift+e = E).

Please don't misinterpret my negativity, I would love to be able to give you the shortcut you want, but I can't make available shortcuts "to the wild" where they might conflict with some other effect other users might expect. You're welcome to try to write a patch for this, but I warn you I can't accept anything that "just" enables those shortcuts for that reason.

Maybe I'll add a "hidden" way to enable the keyboard shortcut selectors to show all possible combinations even if they aren't considered valid.

**Comment by Aetf** [comment]
> Please don't misinterpret my negativity

Of course not. :)

What about adding an option to show all possible combinations and a warning about possible conflicts if the option is enabled? Then normal users can still be protected from unexpected behaviors and others can get more combinations.

**Comment by Quicksaver** [comment]
That's what I was thinking. ;) It might even not need the warning, I might just make it a hidden preference in about:config, so that only those that really know what they're doing would use it.

**Comment by Aetf** [comment]
Yes that would be enough!

**Comment by Aetf** [comment]
OK, so I played around with the code, and added the preference and made Keysets skip validation and availability check based on the preference. But... you are right, it doesn't work. :-(

Even though `Alt+Shift+E` was successfully registered, it seems the menu bar has a higher priority. And `Alt+Shift+E` indeed opens the Edit menu in my system. It didn't work previously due to another add-on, Customizable Shortcuts, doesn't handle some legacy storage correctly and after clean that up, `Alt+Shift+E` works as expected.

After some investigation about why `Alt+Shift+E` works in CS but not Tab Groups, it turns out that CS implements shortcuts in a totally different way. It just listens to `keydown` event on each window and filters out all registered shortcuts event in the listener.

As I don't think it's necessary to introduce a new shortcut system just for this, so maybe I have to choose another shortcut and live with that. Anyway, thank you for keeping Tab Groups live. :)
