### ISSUE TITLE
Free arrange mode issues

### ISSUE THREAD

**Issue by halftone1** [Quicksaver/Tab-Groups#269]
In version 2.0 free arrange mode has several issues, both performance and usability wise:
1) "See all tabs in this stack" is very slow (I can see the blank window opening, getting bigger, and filling with the actual thumbnails in three separate steps, and when i move the mouse away first the thumbnails disappear and then the window closes), which is weird, because the new version doesn't even have the transparency anymore. Dragging and dropping groups also lags.
2) Relatedly, I just noticed that if I open a stack, close it, and then click the exit tab groups button it goes to the last group I looked at. I think it would make more sense if it brought me back to the tab I was using when I opened tab groups. 
3) Couldn't the groups be smaller? The smallest possible size for the thumbnails is ok, but the container is too big, and making it smaller would save a lot of space, especially at low resolutions. There's also empty space where it shouldn't be (see attached image).
![tabgroups](https://cloud.githubusercontent.com/assets/19715628/15759429/dc5a8de4-290e-11e6-9bb1-7f8e6cffb75f.png)

4) The aspect ratio of some thumbnails is wrong for me: they look widescreen while my monitor isn't (this happens in every mode).
5) This is more of a wish, but, I miss the transparency and being able to move groups all the way to the right, below the sidebar: any way we could have them back?

**Comment by iShyboy** [comment]
![weird](http://i.imgur.com/WK2F8Wz.png)
>and when i move the mouse away first the thumbnails disappear and then the window closes

I find this weird too, but didn't found no lag here while opening the stack

>2) Relatedly, I just noticed that if I open a stack, close it, and then click the exit tab groups button it goes to the last group I looked at.

True, it take the first tab of the opened stack. Bad deal.

>4) The aspect ratio of some thumbnails is wrong for me: they look widescreen while my monitor isn't (this happens in every mode).

This doesn't happen with me, my resolution is widescreen. I'm in with a option to change the thumbnails between squared and widescreen.

**Comment by Quicksaver** [comment]
> "See all tabs in this stack" is very slow (I can see the blank window opening, getting bigger, and filling with the actual thumbnails in three separate steps, and when i move the mouse away first the thumbnails disappear and then the window closes)

How slow? It's relatively faster for me, when compared to the previous version, in which I could also see those same steps you described even more clearly.

And the group had always collapsed for me when I moved the mouse away, that's actually one thing I considered removing but left as-was.

> the new version doesn't even have the transparency anymore

Do you mean in the background of the expanded group? Yeah, that's been changed to use a full color.

> Dragging and dropping groups also lags.

Same question, how much lag? It's much faster for me as well. Can you try disabling all other add-ons and themes and see if that helps at all?

> I just noticed that if I open a stack, close it, and then click the exit tab groups button it goes to the last group I looked at. I think it would make more sense if it brought me back to the tab I was using when I opened tab groups. 

Expanding a group selects it. There's really no way to avoid this, basically if you interact with a group, it assumes that's the group you want. Same as clicking virtually anywhere else on the group. (I seem to remember this particular case also worked exactly the same before? Perhaps I'm wrong there...)

> Couldn't the groups be smaller?

Not right now. In order to allow for the group's action buttons (close, options, etc...) to be fully accessible, the minimum size had to be increased. I'm considering ways to better take advantage of the available space for tabs, so that could change in the future.

> There's also empty space where it shouldn't be

That empty space is correct. Tabs don't stretch horizontally to fill the group.

> The aspect ratio of some thumbnails is wrong for me: they look widescreen while my monitor isn't

The aspect ratio is not defined by screen size, but by the available viewable area of the webpages (basically, browser dimensions). And the tab you highlighted there looks almost the same as the others to me, maybe a difference of a pixel or two. I don't see your point really.

> I miss the transparency

The transparent expanded groups brought no real use, and didn't fit in with the rest of the interface at all, it seemed like an appendix that was completely separate. Which is why I removed it, the expanded group is still the same group, which is what it should represent.

> and being able to move groups all the way to the right, below the sidebar

That's just not possible, the side area now has its own function for pinned tabs. That would just interfere badly.

**Comment by halftone1** [comment]
> How slow? It's relatively faster for me, when compared to the previous version, in which I could also see those same steps you described even more clearly.

Testing both the old and new version on a clean profile: the old version draws the thumbnails before the window, so it's almost immediately usable, while on the new version i have to wait longer before I can see/click. If I downgrade the extension on my usual profile and open the same stack a few times in a row sometimes the thumbnails open before the window, and sometimes they open at the same time. So I definitely have to wait longer.
Not sure about drag and drop.

>And the group had always collapsed for me when I moved the mouse away, that's actually one thing I considered removing but left as-was.

I actually have no problem with the collapsing, I just meant that I can see the discrete steps there as well (but they're faster).

>Expanding a group selects it. There's really no way to avoid this, basically if you interact with a group, it assumes that's the group you want. Same as clicking virtually anywhere else on the group. (I seem to remember this particular case also worked exactly the same before? Perhaps I'm wrong there...)

Checked it, and you're right. It might have been a conflict with a different extension, or I just remembered wrong.

>In order to allow for the group's action buttons (close, options, etc...) to be fully accessible, the minimum size had to be increased. I'm considering ways to better take advantage of the available space for tabs, so that could change in the future.

How about putting them vertically, where the pinned tabs used to be? That way it would be possible to recover the space and make the column narrower (which in turn would make it possible to shorten the rows and so on)... Or would it interfere with the scrollbar? They could be alternative settings.

>The aspect ratio is not defined by screen size, but by the available viewable area of the webpages (basically, browser dimensions).

Ok, I hadn't realized that. Being able to choose a fixed (narrower) aspect ratio could be useful though, and I see it's already marked as an enhancement.

**Comment by Quicksaver** [comment]
> Testing both the old and new version on a clean profile: the old version draws the thumbnails before the window, so it's almost immediately usable, while on the new version i have to wait longer before I can see/click. If I downgrade the extension on my usual profile and open the same stack a few times in a row sometimes the thumbnails open before the window, and sometimes they open at the same time. So I definitely have to wait longer.

This is completely unrelated to free arrange mode. Thumbnails are now drawn sequentially, instead of almost all at once like it happened before, which was a major source of lag and unresponsiveness in the previous version. Even though they may take a few extra moments to draw completely, you should be able to click tabs at will immediately. Basically, you don't need to wait for them all to paint.

I'm closing based on this, please let me know if I misunderstood or if this is not happening for you.

> How about putting them vertically, where the pinned tabs used to be?

Could interfere with the scrollbar, less space where to show tabs, doesn't really help much with the problem because it would still require the group to keep a larger minimum height (replacing width with height basically, which is hardly a global solution).
