### ISSUE TITLE
Layout for editing keyboard shortcuts (prefs) shifts when changed

### ISSUE THREAD

**Issue by Kinematics** [Quicksaver/Tab-Groups#27]
Each time you click one of the checkboxes (ctrl, alt, shift) when editing the prefs for the keyboard shortcuts, it causes varying shifts in the indentation of the rows.  Sometimes it shifts the row that you edited, and sometimes it shifts the *other* rows.

For example, if all three have Ctrl checked, and Alt and Shift blank, clicking Shift on the bottom row (switch to previous group) shifts the other two to the right; clicking Shift on the middle row shifts it to the left; and clicking Shift on the top row shifts it to the left *and* the other two to the right.

**Comment by Quicksaver** [comment]
That's expected. Every time you click one of those boxes, it updates what shortcuts are available in the dropdown. Some keys take up more space than others.

**Comment by Kinematics** [comment]
OK, I think I see what's happening.  If the dropdown's width changes size, all three rows are adjusted so that the very right edge of all the dropdowns line up together.  So if one of them shifts, the other two can end up moving to match (with allowance for indentation with the text space at the far left).

Would still say that that's bad form, in keeping the checkboxes bound to that adjustment.  The checkbox blocks will never change size, since it's the same text in all three rows, so they should always line up with each other.  The dropdowns can adjust so that their left block border is against the block with the checkboxes, and then you can keep the right margins lined up like current.

**Comment by Quicksaver** [comment]
I see your point about that being better form (although honestly I personally disagree, it's a matter of taste I guess).

Unfortunately I don't think I can do that, it would hardly be simple at least. To align the checkboxes like that they would have to be physically detached from the same node of the preference labels (e.g. "Enter and exit groups mode"). Then you couldn't highlight them as intended; try typing "enter" in the "Jump to" box at the bottom so you see what I mean.

The problem there is that those preference labels don't actually have a fixed width; they can't since in other locales their width will be completely different. Instead right now it's pulling the key dropdown selector and its checkbox away from the labels to align them on the right.
