### ISSUE TITLE
Increase height of field for tab group title

### ISSUE THREAD

**Issue by GaryKing** [Quicksaver/Tab-Groups#280]
In the single view, and probably the other views too, please increase the height of the field for entering a tab group's title. It's way too small. The size might have worked for the free arrange mode, but it seems small for the other new modes, especially when the size for the tabs in comparison are incredibly large. It just makes it more tedious to click on the small field for the tab group title.

**Comment by Quicksaver** [comment]
It's exactly the same size for all modes. I don't see how the size of tab thumbnails should play a role in the size of the group's title. Could it just be that it looks small because the groups themselves are bigger? That shouldn't really be a factor either, because in grid layout if you have more groups they'll become smaller as well. The group's title size shouldn't be "dynamic" like that either of course.

I don't see what you would gain from increasing it...

**Comment by GaryKing** [comment]
Right, I notice that it's the same size across all modes. It just seems so small compared to the other elements on the page. On the practical side of things, it's just so small that it makes it unnecessarily difficult to target it with the mouse.

**Comment by Quicksaver** [comment]
It's the same size as the other buttons next to it, 24px, which is actually a couple of pixels taller than it was before if I remember correctly. I'm sure this is just your impression, from not being used to the new design yet. But please do re-open if you can confirm that it's smaller than the other elements around it, as it's not supposed to be of course.
