### ISSUE TITLE
scroll-bar apparently resizes rather than scrolls

### ISSUE THREAD

**Issue by leggewie** [Quicksaver/Tab-Groups#282]
I just observed the following behaviour.  I have a tab group without thumbnails and set to scroll rather than stack.  There are about 40 tabs in it so the scroll-bar appears when in group view.  I grab the scroll-bar with the mouse and move it down to have a look at some of the tabs further down.  The group is then re-sized instead of scrolled through.  Clicking to page-down works.

**Comment by Quicksaver** [comment]
That's very weird. Can you get a recording of this? I assume this is on free arrange mode, does it also happen when you disable all your other add-ons?

Could it have been that your group was resized previously, by moving one or two other groups around or resizing the window? If that was the case, and the group now had enough space available to go back to its original size, certain interactions like those could cause it to resize back (one of the things that still makes free arrange hard to predict).

**Comment by leggewie** [comment]
I was unable to reproduce it now.

**Comment by iShyboy** [comment]
It does happen, all in all, it's just that the bar is so small that it get in the way with the resize 'button'
![1](http://i.imgur.com/W005J0y.png)

**Comment by Quicksaver** [comment]
Oh, that's a good catch, I hadn't considered that. Let me see if there's anything I can do about that, I'm not sure restricting the scrollbar to not go all the way down like that might be optimal though, but it's a possibility to resolve this.

**Comment by leggewie** [comment]
It happened for me on the upper right edge, though.

**Comment by Quicksaver** [comment]
> It happened for me on the upper right edge.

That... I have no clue. :/ Please do let me know if it happens again though. If it was a one-time thing then oh well, but if it keeps happening then I'll have to figure out something.

**Comment by iShyboy** [comment]
There's another strange [behavior](https://stats.waa.ai/scrollbar.mp4). It didn't resize, but move it arround.

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) should fix the issue with dragging the scrollbar occasionally moving the group. Also, the scrollbar should only extend to just above the resizer, so that it's never covered by it. Please give it a try and let me know if you still have any of these issues.

**Comment by Quicksaver** [comment]
Also, note that there is apparently a bug where if you left-mouse down on the resizer, but click with the right mouse button before you release the left mouse button, it will bring all sorts of crazy. Basically, the group will be left in a perpetual state of resize until you manage to click (and release!) the left mouse button again on its resizer. This is something that's caused by something deep within Firefox itself and its HTML5 resizer handlers, so there's not really anything I can do about it. So in short, don't do that. ;)
