### ISSUE TITLE
New Group Tabs won't let me drag tabs from one group to another

### ISSUE THREAD

**Issue by wordnerd411** [Quicksaver/Tab-Groups#284]
Sometimes I'll open an email, click on a link and want to keep that tab open.  But I want to keep it with similar topics not in my Command Central tab which has all my email accounts in it.  Other times I'm researching/fact checking and stumble on some fascinating site that is nothing to do with work.  So I want to keep it in my learning/entertainment group, not in my reference group.

It was so easy to drag tabs before and now I can't seem to do it.  The only thing I found was to work around it by copying the url, going to the tab where it 'belongs' and opening a new tab and pasting it in.  This is clunky and I know that my tabs will rapidly become completely disorganized if this is the only way to do it!

Hoping someone can help out!

**Comment by leggewie** [comment]
Not sure I understand your issue correctly.  But, are you aware of "Move to group" available when you right-click on the tab you want to move?

**Comment by Quicksaver** [comment]
Dragging tabs should work just like before. Dragging tabs in the new quick access panel won't work (yet), you'll have to enter groups view by clicking the "Manage my groups" button in that panel, or press Ctrl+Shift+E directly.

Note that, as explained in the release notes, you can disable the "Click to show the quick access panel" option in the add-on's preferences, so that clicking the button takes you directly to groups view and you can do this immediately like before, instead of going through the quick access panel if you don't want.

Does any of this help?
