### ISSUE TITLE
area to grab for resizing and moving is pretty small

### ISSUE THREAD

**Issue by leggewie** [Quicksaver/Tab-Groups#285]
I find it a bit hard to resize and move windows in free arrange mode.  The area to grab unto is pretty small (especially for moving the window).

**Comment by Quicksaver** [comment]
You can click and drag anywhere in the group that is not a button or a tab. Try grabbing from the title (while you're NOT! typing in it). Doesn't this work for you?

**Comment by leggewie** [comment]
OK, that works fine for me for moving.  Resizing still requires fine-motor skills.

**Comment by Quicksaver** [comment]
I'm sorry, I must have missed your second comment somehow. The resizer size is controlled natively by Firefox (and I think it varies with OS?). I was going to say you can control it with Stylish, but apparently that's not possible, or at least I'm not able to do it.

The only thing I could do would be to completely remove those and create my own resizers. I changed group resizing before to use HTML5 resizing because it's just so much easier to handle and it works far better than anything I could throw together in Javascript. It was using custom resizers before and it was a lot to maintain, I'd rather not go back to that.
