### ISSUE TITLE
'Session Manager' Load Session no longer works

### ISSUE THREAD

**Issue by AlfredTheorin** [Quicksaver/Tab-Groups#286]
Since Tab Groups became version 2, Load Session in 'Session Manager' no longer works.

Steps to repeat:
1. Create a clean firefox profile
2. Add 'Session Manager' and 'Tab Groups' plugins
3. Open up so that you have more than one tab group with at least one tab open in each tab group

At this point, Save / Load session in 'Session Manager' no longer works properly, for example,

4. Open 'Session Manager' options / General / Startup & Shutdown / At startup always load the following session / Select session / < Previous browsing session >
5. Close and re-open firefox

Behavior:
All tabs from all tab groups are shown

Expected behavior:
Only the tabs in the current tab group are shown

**Comment by Quicksaver** [comment]
I'll have to check it out, but last time I tried (with v2) it worked perfectly. Session Manager should work perfectly fine with the new version.

Could I also ask you to bring this up with the developers of Session Manager? I won't be able to look into this for at least the next couple of weeks, and if this is something that could be easily fixed on their side, they might be able to give you a more timely update.

**Comment by accedohk** [comment]
Same problem.

Can no longer reload a previous session.
The UI does not redraw to show the additional tabs.

**Comment by leggewie** [comment]
I'm also a heavy user of Session Manager.  I can semi-confirm this.  I believe that I saw all tabs from all groups on start-up a few times.  But IIRC, it either corrected itself after a few seconds or I was able to rectify the situation by going into groups view once with Ctrl-Shift+E.  I believe I've not experienced the problem anymore afterwards.  It seems that there were other small glitches like this in the transition to Group Tabs 2.  It appears to me that they self-corrected over time.

I've had one pretty major problem in that somehow Tab Groups apparently triggered Session Manager to run out of memory.  (There was still plenty of RAM, btw).  SM would then stop saving the session and it wasn't possible to explicitly save it either.  Any changes from the last time a session was saved would be lost.  I have to say that I am one of those people with well over a thousand, grouped tabs open at the same time.  I've now cut that to about 500 and the self-healing I mentioned has dramatically improved start-up times (used to be over 10 minutes!) and memory problems.  I'll keep an eye on this and open a ticket if this issue comes back.  I wanted to mention it here for references sake.

**Comment by WolfganP** [comment]
I need to test it further, but I didn't see any errors on reloading last session at startup with SM. What I did notice is that FF startup/auto restore last session time became longer and longer lately, without any dramatic increase on number of open tabs or tab groups (~300 tabs in 6 groups, not loaded by default BTW).

**Comment by Quicksaver** [comment]
Could everyone please try [beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) and let me know if it helps with any of these issues with Session Manager at all?

**Comment by Quicksaver** [comment]
Please re-open if you still have this issue with the latest version 2.1.
