### ISSUE TITLE
unhandy and laggy behaviour when resizing tab groups

### ISSUE THREAD

**Issue by Shorusai** [Quicksaver/Tab-Groups#288]
Maybe it's just me but resizing tab group became quite a hassle since it always needs to show the "open new tab" icon.
Here one tab group is using double the space just to show the "open new tab" icon
![ss 2016-06-04 at 11 47 39](https://cloud.githubusercontent.com/assets/19745542/15798900/63f83b0c-2a4a-11e6-9cca-1fc74f26d307.jpg)
if i want to resize it to just the size of those three tabs it immediately stacks them
![ss 2016-06-04 at 11 47 54](https://cloud.githubusercontent.com/assets/19745542/15798906/92562d24-2a4a-11e6-8888-8e84033421cd.jpg)
maybe an option for disabling this icon would be good, some people might need it, i dont. Just like in original firefox tab groups, on the right side its just resized to the amount of tabs:
![firefox-tabgruppe-erstellen_537cb445](https://cloud.githubusercontent.com/assets/19745542/15798912/b1a21bac-2a4a-11e6-8a33-afb1c7d8210a.jpg)
(btw. it seems that the preview of how the tab would be after resize is kinda laggy and faulty, sometimes it still shows me the thumbnail, but when I let the mouse button go, it suddenly stacks it instead)

also for resizing tabs to scroll view, sometimes it resizes it to scollables thumbnails, sometimes to a list. I couldnt find an option to resize it always to a minimum so it will always show at least thumbnails and never the list. Any help here?

I know you added this feature of being able to click anywhere to move a group, but I'm very used to just click a group anywhere and it would open (instead of double clicking it) Is it possible to implement a condition: if click+hold it moves, if click+release it opens. 
that would be great :+1: 

Thanks for your concern.

**Comment by Quicksaver** [comment]
> maybe an option for disabling this icon would be good, some people might need it

That will probably be changed in the next version, so it won't be a bother anymore. See #192.

> (btw. it seems that the preview of how the tab would be after resize is kinda laggy and faulty, sometimes it still shows me the thumbnail, but when I let the mouse button go, it suddenly stacks it instead)

The resizing of the tabs is not immediate, it happens on a delay while you resize, to make the interface more responsive. If you resize a group, stop moving the mouse but don't release the button for a moment, the tabs should be sized properly. Is this not happening?

> also for resizing tabs to scroll view, sometimes it resizes it to scollables thumbnails, sometimes to a list

When you set a group to scroll, if it can't show at least three columns of thumbnails, it will hide them because you get much more visual information that way. Otherwise, it would be very difficult to navigate only two or even one column of thumbnails in a group that has more tabs than it can show.

> I'm very used to just click a group anywhere and it would open (instead of double clicking it) Is it possible to implement a condition: if click+hold it moves, if click+release it opens. 

Wouldn't you also have to get used to that? And that would require two motions even, to bring your other hand to the keys necessary, press them, and then click with the mouse. Isn't a double-click still more practical than that?

**Comment by Shorusai** [comment]
> That will probably be changed in the next version, so it won't be a bother anymore. See #192.

Oh sorry then for the extra post, I didnt find this other post containing this issue.

> The resizing of the tabs is not immediate, it happens on a delay while you resize

Okay then it mustve been the delay because often the tabs (when making a group smaller) just jump down one row first
![bild 1](https://cloud.githubusercontent.com/assets/19745542/15806594/b0f0af1e-2b46-11e6-8da3-92d59c1bdd24.jpg)
then it updates and the tabs resize instead and jump the row up again
![bild 2](https://cloud.githubusercontent.com/assets/19745542/15806596/c35b4a88-2b46-11e6-9fd6-4b75a20bdf3a.jpg)

so the user kind of gets 1 wrong preview before it shows the actual one, but if this real time preview slowed the performance down so much i wouldnt know how to solve this issue. its still quite annoying though..

> Otherwise, it would be very difficult to navigate only two or even one column of thumbnails in a group that has more tabs than it can show.

Thats true, maybe this was half way connected to the update delay and the add tab icon, because sometimes resizing a group trying to get the smallest possible size before it turns into a list can be quite a hassle. Maybe that will solve with the update about the add-Tab icon, or maybe an option for being able to only resize to a minimum of 3 columns would help (but could come in unhandy in other situations for other users. not sure.)

> Wouldn't you also have to get used to that?

I thought of an answer like that to come already..talking about getting used

> And that would require two motions even, to bring your other hand to the keys necessary

I think you got me wrong here: It would be just a single click instead of two, quite practial for quickly switching between groups.
Wasnt it like that before you were able to move the groups by clicking and dragging anywhere?
But of course I agree this might just be personal preference again.

**Comment by Quicksaver** [comment]
> I think you got me wrong here: It would be just a single click instead of two, quite practial for quickly switching between groups.

You're right, I read your suggestions as Ctrl+click for some reason. I'm sorry for the confusion.

> Wasnt it like that before you were able to move the groups by clicking and dragging anywhere?

Yes it was, and this was an intended change. Of course this will highly depend on each user's habits, but before it would be extremely easy to click on a group by accident and enter it, while you actually wanted to do something else, especially in touchscreens or with trackpads. There was also no logic behind that behavior, say you wanted to make another group active (for whatever reason) but didn't want to focus a tab, So you click on it by reflex, because that's what you do with pretty much every other application out there. Then you had to go back to groups view.

The current single-click-to-select-and-double-click-to-open behavior is much more inline with what is "expected" by new users.

**Comment by Quicksaver** [comment]
> so the user kind of gets 1 wrong preview before it shows the actual one, but if this real time preview slowed the performance down so much i wouldnt know how to solve this issue. its still quite annoying though..

It's possible it's not resizing the tabs one final time before releasing the mouse button. I'll take a look and see if there's something I can do to optimize this.

**Comment by Quicksaver** [comment]
Could you try [beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) and let me know if you still have this issue? I haven't been able to reproduce it exactly, but I have made some adjustments to how resizing works.

**Comment by Quicksaver** [comment]
Please re-open if you still have this issue with the latest version 2.1.
