### ISSUE TITLE
Disappearing Icon

### ISSUE THREAD

**Issue by londis52** [Quicksaver/Tab-Groups#289]
The icon for switching between groups disappeared after the latest update.  I can still access the groups by Ctrl+Shift E.

I am running Firefox on Ubuntu14.04 on a Toshiba laptop

**Comment by Quicksaver** [comment]
The toolbar button now shows the name of the active group by default. Are you sure it is not there? It should appear as text instead of the previous icon. You can still restore the previous behavior by going to the add-on's preferences and disabling the option "Show the name of the active group" in the toolbar button, so that it always shows the icon as before.

If none of that helps, please try the suggestions at #230.

**Comment by londis52** [comment]
The active group name is not displayed on the toolbar.  I removed the 'show the name of the active group' from the preferences and the icon is back, and I'm very happy.

Thank you for responding so quickly.
