### ISSUE TITLE
Unable to Open Tab Groups

### ISSUE THREAD

**Issue by Gregoyle** [Quicksaver/Tab-Groups#291]
Since the last update I'm unable to open up the tab groups page to see my tab groups. This is since the last update and I've tried different shortcut keys and re-installing the addon.

I'm not too worried about losing my old tab groups but I would like to be able to use the addon again, my life just hasn't been the same since; if anyone could provide guidance on completely removing it and re-installing it (config files and all) that might work.

It might be a conflict with some other addon as well. Here is a list of the extensions I use currently:
![alt text](http://i.imgur.com/nMdhfCn.png "List of Addons").

**Comment by Quicksaver** [comment]
Can you not find the toolbar button anywhere? Remember it should now show the name of the active group (as text) instead of the icon, but you can change this by going to the add-on's preferences (in that screen) and disabling the option "Show the name of the active group" if you prefer.

Can you also not use the keyboard shortcut? By default it's Ctrl+Shift+E, unless you've changed it in the preferences as well.

If you still can't open it, please try disabling all your other add-ons except for Tab Groups and see if it works then.

If none of that helps, please check out #239 and try the suggestions there to see if it could be related to any CCK 2 release as well.

**Comment by Gregoyle** [comment]
Thanks Quick! Sorry for wasting your time. I tried disabling everything again and seeing if it would work, this time I did see the icon and it worked beautifully. I'll find the incompatible addon and get back to you. Thanks for thinking of me though.
