### ISSUE TITLE
Incompatible with Tab Deque addon

### ISSUE THREAD

**Issue by berkley4** [Quicksaver/Tab-Groups#294]
As noted in Tab Deque's readme, it's incompatible with Tab Groups. Perhaps a solution can be found here, or Tab Deque's functionality could be provided by Tab Groups.

https://github.com/sblask/firefox-tab-deque

**Comment by Quicksaver** [comment]
If I understand correctly how it works, that's just a matter of making the deques aware of what tabs are in which groups, and selecting the tabs appropriately. I'm all for introducing whatever changes are necessary to make this work, but this is not something I can do only within Tab Groups at all.

**Comment by Quicksaver** [comment]
(As in, I'm all for helping its developer do this, however I can, but it needs to be done in Tab Deque, as otherwise I'd simply be overriding tab deque's behavior completely - in other words, I'd be making my own implementation to replace it -, and that's not the most optimal way to do it.)

**Comment by berkley4** [comment]
I've just opened an issue with Tab Deque - https://github.com/sblask/firefox-tab-deque/issues/6

Thanks for the fast response, it would be great if the issues could be worked out.

**Comment by sblask** [comment]
I didn't try it out or look into your add-on's code, but I reckon if it doesn't work it must break `tabbrowser.selectTabAtIndex` (https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/tabbrowser#m-selectTabAtIndex) that I use here: https://github.com/sblask/firefox-tab-deque/blob/master/content/tabdeque.jsm#L231 or the tabbrowser's tab handling that I use here to get the tab index: https://github.com/sblask/firefox-tab-deque/blob/master/content/tabdeque.jsm#L444 Not sure why I would have to make my add-on group aware to make it work. All it does is keeping a list of tabs in selection order and select the appropriate one on certain actions...

**Comment by Quicksaver** [comment]
@sblask I just went by what you mention in Tab Deque's description:
> Tab Deque doesn't work well with Tab Groups. If the next tab in the deque is in another Tab Group it doesn't get selected on closing the current tab

What I meant was, if the next tab in the deque is in another group, it should be skipped until it found one in the current group, or if it's the last one show the new tab as usual. Is this not the incompatibility?

**Comment by sblask** [comment]
Ok, now I did a quick check for what doesn't work(according to how I think it should work). When I am in a tab in group A and then choose a tab in another group B and close that one, I should go back to the tab in group A, but I don't. I also could get the right tab order within one group. But I am not sure why. I guess you just change a lot of internal stuff to get it to work. And there is nothing much I can do about it.

If there should be some special handling with groups, like what you suggest, I think it should behave as if a group were a window, every group should have their own deque. When the last tab of a group is closed, it should just get back to the last used one of the last group. With separate windows it just works because of how Tab Deque is initialised. For groups, I think I'd need to hook into a lot of internals of your add-on to get it to work. So if at all, it should happen in a separate add-on that extends yours. I agree that you should not add it to Tag Groups directly as it's not what it's made for.

@berkley4 what exactly do you expect to happen?

**Comment by Quicksaver** [comment]
> I think it should behave as if a group were a window, every group should have their own deque.

Exactly my thinking.

> When the last tab of a group is closed, it should just get back to the last used one of the last group.

I disagree there, it shouldn't switch to a tab to another group. If I were to close the last visible tab, I would expect it to show me a new tab without changing groups. Isn't that what happens already when you don't have groups at all?

For example, say you have the following scheme:
- Group A
 - Tab 1
 - Tab 2
- Group B
 - Tab 3
 - Tab 4
So you start Firefox, it opens in Tab 1 in Group A (because let's say that's where you left it before). So because you're in Group A, only Tab 1 and Tab 2 are visible.

Now, you switch to Tab 3 in Group B. Tabs 3 and 4 are visible, tab 3 is selected, and tabs 1 and 2 are now hidden.

Now you close Tab 3. It shouldn't go to Tab 1 (the last selected tab), because that's in another group. So to stay in Group B, it selects Tab 4.

Now you close Tab 4. At this point I don't expect it to go to Tab 1 either (even if it's still technically the last selected tab in Tab Deque's order), because it's just not visible. I would expect Tab 4 to close and for the regular "New Tab" to be shown, still in Group B.

Is my logic wrong? Does Tab Deque always make all tabs visible, regardless of what group is active? (For example, through the deque, can you see all tabs 1, 2, 3 and 4 in that case?

**Comment by sblask** [comment]
I think Tab Deque simply doesn't work at all with Tab Groups and it's only the default behaviour I see.

In my opinion, if I activate tabs 1, 3, 2, 4 and then close one after another it should be 2, 3, 1 that get activated no matter what the groups are. That's what I created Tab Deque for, because I think it's the most transparent way to handle tabs and because I was used to it from Opera. I just hate the default tab ordering of Firefox.

I simply don't use Tab Groups, so I can't tell you what's best for it...

**Comment by berkley4** [comment]
@sblask - sorry for the late reply. Things work as expected only if there is one tab group. More than one group sees Tab Deque gradually stop working: clicking the current tab either activates the wrong tab or does nothing, instead of switching to the previous tab.

**Comment by berkley4** [comment]
Just to add my opinion on Tab Groups' desired behaviour, whether closing the tab switches to a new group or shows a blank tab isn't strictly the issue. With more than one tab group you can't even switch within one group in the fashion that Tab Deque allows.
