### ISSUE TITLE
In single view, when tab group is already selected, require only one click to open it

### ISSUE THREAD

**Issue by leodag** [Quicksaver/Tab-Groups#298]
In single view, if a tab group is already selected, IMO it would be more logical and convenient to require only one click to open it.

**Comment by Quicksaver** [comment]
I don't follow. Do you mean one click in an empty area of the group to go back to the selected tab?

**Comment by leodag** [comment]
No, on the tab group thumbnail itself. Currently if you double click it, you open the tab group on the last selected tab, wheter it was selected or not. I'm suggesting that this should happen with only one click if the tab is already selected.

**Comment by Quicksaver** [comment]
Oh. Actually that double-click behavior is a bit of a side-effect I didn't actually intend at the time, but didn't remove because it kind of falls in line with the rest of the double-click behavior.

But I disagree with single click as you suggest. It's inconsistent behavior, when you click something to select, it's expected it just selects that thing, even if it's already selected.

**Comment by leodag** [comment]
I get your reasoning. Thanks for the attention, and for the awesome addon!
