### ISSUE TITLE
Add shortcut keys for switching between tab groups

### ISSUE THREAD

**Issue by CIAvash** [Quicksaver/Tab-Groups#3]
Firefox's tab groups has `Ctrl`+`` ` `` and `Ctrl`+`Shift`+`` ` `` shortcut keys for going to next and previous tab groups.

**Comment by Quicksaver** [comment]
I assume those are not working for you. I can't really test them because I can't use that shortcut in my keyboard...

I'm willing to bet that's a key combination that other keyboard layouts won't have access to either. I think I will change it something else. What do you think about PageUp/PageDown and Ctrl+Left/Ctrl+Right?

**Comment by CIAvash** [comment]
They started working after I restarted Firefox. Maybe there was a conflict with the current tab groups in Firefox. I'm using Firefox 42.0. So this issue can be closed.

I don't think changing the shortcut keys is a good idea, since the users who use these shortcuts are already familiar with them. Maybe add the options to change them in the preferences, like `Ctrl`+`Shift`+`E`.

About the shortcut keys you mentioned, wouldn't they conflict with other shortcut keys? They can be useful in the panorama view, since they are not set to anything there.Or maybe that's what you meant? Because Ctrl+\` works like Ctrl+Tab outside panorama view.

**Comment by Quicksaver** [comment]
> They started working after I restarted Firefox. Maybe there was a conflict with the current tab groups in Firefox.

That's admittedly weird, the add-on completely disables the native Tab Groups, so there shouldn't be any conflict at all there. Please let me know if this ever happens again.

> I don't think changing the shortcut keys is a good idea, since the users who use these shortcuts are already familiar with them. Maybe add the options to change them in the preferences, like Ctrl+Shift+E.

That's a good point. I probably will do this. I'll leave this open to remind me to do this.

> About the shortcut keys you mentioned, wouldn't they conflict with other shortcut keys? They can be useful in the panorama view, since they are not set to anything there.Or maybe that's what you meant?

Yeah, only in groups mode. :)

**Comment by poke** [comment]
> Because Ctrl+` works like Ctrl+Tab outside panorama view.

TIL. I considered myself a Panorama power user, but I never knew about those shortcuts (not that I think they are particularly useful now that I know them).

But having a German keyboard layout, I can only use one of the shortcuts (since on the German keyboard layout, the backtick is already behind the shift key). So +1 for being able to change (and maybe deactivate) the keyboard shortcuts.

**Comment by sdar** [comment]
Ctrl+Shift+` doesn't work with some keyboards, not even in the original firefox tab groups, I've changed all of the shortcuts using customizable-shortcuts (https://addons.mozilla.org/en-US/firefox/addon/customizable-shortcuts/) but it does nothing for the addon version so now i can't go to previous group.

Also I was using Ctrl + E to open panorama instead of Ctrl + shift + E but it doesn't work with the addon so more options for the shortcuts and a prev/next group shortcut selector could be great.

**Comment by Quicksaver** [comment]
Ctrl+E is an existing shortcut that focuses the search bar, so you won't be able to use that unless you disable the original first. You could try disabling it in Customizable Shortcuts and then go to the add-on's preferences, it should let you use that one then.

**Comment by sdar** [comment]
I've already tried disabling Ctrl + E using customizable shortcuts that's how i used it with the original tab groups but it doesn't work with the addon :S

Still great to have the feature back I'm using ctrl + Q that is pretty similar and the only thing I'm missing is a way to set next/prev group cause ctrl + shift + ` doesn't work with my keyboard.

**Comment by Quicksaver** [comment]
I just figured out I misinterpreted you a little, you wanted the shortcuts outside of tab groups mode, not while in it, correct?

I ask because
- those shortcuts are actually working for me outside of tab groups, so before anything I'd like to find out why they aren't working for you; if you could please try disabling all your other add-ons to confirm that it's not a conflict somewhere I would appreciate it;
- you can just use the arrow keys in tab groups mode to switch between groups (granted this navigation could be improved a little, but it still works).

**Comment by CIAvash** [comment]
@Quicksaver Are you replying to me? Got a little confused :)

**Comment by Quicksaver** [comment]
Yes, sorry about that, should have poked you directly to make sure. :)

**Comment by CIAvash** [comment]
No problem.

> I just figured out I misinterpreted you a little, you wanted the shortcuts outside of tab groups mode, not while in it, correct?

Yes.

> those shortcuts are actually working for me outside of tab groups

As I mentioned they weren't working after I installed the add-on, but they started working after I restarted Firefox. So they are working now. Do you want me to uninstall and try again?

> you can just use the arrow keys in tab groups mode to switch between groups

If I'm not mistaken the arrow keys move between tabs. It wouldn't be a bad idea if you could move between groups too, with Ctrl+arrow keys like you suggested.

**Comment by Quicksaver** [comment]
@CIAvash you know what, no wonder you got confused, I'm the one making a huge mix-up. That's what happens when you're thinking about three different keyboard shortcut issues at once. I'm so sorry for the confusion. :)

To summarize, here's what I'm thinking about doing here: as I said, make those switch groups shortcuts customizable in the preferences (but default them to the current native shortcuts in Firefox). Bonus: see if they can also work while in Tab Groups mode, can't see why this would hurt.

**Comment by CIAvash** [comment]
@Quicksaver Yeah :)
Maybe it's better to close this issue and open new issues for those specific enhancements to prevent future confusion.

**Comment by Quicksaver** [comment]
I'm doing it right now already, so there's no use. :)
