### ISSUE TITLE
On Windows 7, FF 45.1.1 the Tab Group icon is not shown 

### ISSUE THREAD

**Issue by amontefusco** [Quicksaver/Tab-Groups#302]
... neither the keyboard shortcut seems able to show him.
Even the icon is not shown in the Customize menu.
It seems that the last update to 2.0.1 was the culprit.
There is a way to revert to a previous version ?

**Comment by Quicksaver** [comment]
Please try the suggestions at #239. If none of it helps (or you think CCK2 is not the reason), please re-open this issue.

**Comment by amontefusco** [comment]
Disabling IBM CCK partially worked: now I can open TabGroups using the shortcut but no joy with the icon.

**Comment by Quicksaver** [comment]
Please note that in the new version, the toolbar button shows the name of the active group (in text), rather than the icon. Are you sure it is not where it was before? (As explained in the release notes, you can disable this in the add-on preferences, look for the option "Show the name of the active group" in the toolbar button, and see if unchecking that helps.)

**Comment by amontefusco** [comment]
I had to remove completely the IBM CCK !
