### ISSUE TITLE
Multiprocess

### ISSUE THREAD

**Issue by storrgie** [Quicksaver/Tab-Groups#325]
With the release of 47 users can enable the multiprocess feature that has been in the beta channel for a while. I enabled and noticed that its being blocked from activation by an addon. I only use ublock origin and this addon, so, more of an informational issue:

 - Is this a known thing?
 - Is this why mozilla stopped its internal support for this feature?
 - Is it at all likely that this project would take on the burden of addressing the block?

**Comment by Quicksaver** [comment]
> Is this a known thing?

Multiprocess is only enabled for users without any addons, regardless if they're multiprocess compatible or not. So just by having any add-on you won't be able to use that.

> Is this why mozilla stopped its internal support for this feature?

Not directly. They dropped it because it was becoming a burden in maintaining it just to keep it working with the rest of the changes to the whole browser (including multiprocess, yes), while at the same time it hasn't received any actual development in a long time, which wasn't going to happen any time soon either.

> Is it at all likely that this project would take on the burden of addressing the block?

Tab Groups is already fully compatible with multiprocess Firefox. It is a safety measure on their side to not enable multiprocess in instances with add-ons, and that will be lifted in a later release (probably 49 or 50). [You can find more info and some links on this article.](http://arstechnica.co.uk/information-technology/2016/06/firefox-48-electrolysis-download-details/)
