### ISSUE TITLE
Tab Groups 2.0 apparently causes memory issues in Session Manager

### ISSUE THREAD

**Issue by leggewie** [Quicksaver/Tab-Groups#332]
Tab Groups 2.0 is a great improvement and generally awesome. I've had one pretty major problem ever since Tab Groups 2.0 came out in that somehow Tab Groups apparently triggered Session Manager to run out of memory. I have to say I'm a pretty heavy user of tabs and usually have more than one thousand tabs open.  But I am now seeing it with as "little" as 400 tabs.  The machine runs Ubuntu trusty and has 4GB RAM and 2GB swap.  Firefox uses between 1.5G and 2G real RAM and up to 1G of swap, but never really more.  With 400 tabs, FF is at 1G or RAM and 500MB of swap.

So, there should really be enough memory available, the machine never starts swapping heavily. SM eventually prints the following lines in its log

    Tue, 14 Jun 2016 04:25:28 GMT: out of memory
    Tue, 14 Jun 2016 04:25:28 GMT: EXCEPTION - {state is null} 

and auto-saving the session at that time and from then on will fail (even if reducing the number of tabs).  Saving it explicitly or even one window at a time will usually also fail. Any changes from the last time a session was saved would be lost.  This is of course an issue in Session Manager but it was triggered by the update to Tab Groups 2.0.  Never saw it before.

I've reported this to Session Manager at https://www.mozdev.org/bugs/show_bug.cgi?id=26241

**Comment by Quicksaver** [comment]
I doubt it's a "memory" issue because the structure of the groups data hasn't changed at all. There may be some incompatibility that appeared with the update, which is making Session Manager try to read some session data that apparently doesn't exist (i.e. the "state is null" message) and it apparently doesn't expect that.

I'll be sure to check it out when I can. I had never seen this before though, can you tell if this also happens when you disable all your other add-ons except for SM and Tab Groups?

**Comment by leggewie** [comment]
What can I do to troubleshoot this and provide meaningful information.  This is hurting BAD!

**Comment by Quicksaver** [comment]
For starters, you can try disabling all your other add-ons except for Tab Groups and Session Manager and see if that still happens.

**Comment by leggewie** [comment]
OK, I was able to reproduce the problem with just SM and TG2.0 enabled.  It would trigger much later, though, roughly at 1.000 tabs as compared to 500 before.  It seems also that having the computer sit idle for a few hours is often enough to push it over the edge.  Furthermore, it seems that FF cannot recover from this situation once it happened.  On the last observation, I went back to only 2 tabs after seeing the OOM condition: about:addons and about:memory.  The consumed RAM would remain at over 1GB and SM would continue to be unable to save the session, unable to grab the necessary memory.

**Comment by leggewie** [comment]
Unfortunately, this makes TG2.0 almost unusable for me as I have to have more than a few hundred tabs open.

**Comment by whismerhill** [comment]
Hi, I had exactly the same kind of error using Firefox 32 bit session manager & no tab groups addon(back then there was still tab groups within firefox) on windows x64.
Switching to Firefox 64 bit or Waterfox 64 bit solved the issue. How this relates to your problem you may ask ? well you didn't precise which version of FF you used & if ubuntu was 32 or 64 bit. So imho it could be part of the problem.

**Comment by leggewie** [comment]
Thank you, @whismerhill I am indeed using FF 32 bit.

This has become a tremendous pain.  I've experienced it the last few days several times when having a mere 3 tab groups with about 20 tabs each.  The fact that this type of problem means you essentially crash with all work lost since the last backup doesn't help.  After the memory problem occurs you usually cannot save the state of your open tabs anymore.

**Comment by Quicksaver** [comment]
First of all, I'm very sorry it took me this long to get to this.

Some general considerations.

I believe you misinterpreted [this reply in you SM's bug report](https://www.mozdev.org/bugs/show_bug.cgi?id=26241#c3). 32-bit applications are "typically" more limited in what memory they can access, regardless of if the operating system can actually access that memory or not. I seem to recall seeing somewhere that Firefox 32-bit does enforce some kind of limits like these, although I can't confirm it right now, so I could be completely wrong. But it's still something to consider.

Also, even if Firefox could access all the memory you have, at 2Gb that's already a lot. Even pretending the rest of the system is using no RAM at all (which I very much doubt), that doesn't mean that memory is not already reserved by something else, usually even system processes. Just because memory "is not in use", it doesn't necessarily mean "it's free".

That's just to say Firefox could indeed have no accessible memory available, even if it doesn't seem like it.

As far as Tab Groups memory consumption goes, of course it will always have its footprint, and the more tabs you have the more memory it will need. There are already many optimizations in place, but it's impossible to bring that to 0. You could start by not showing tab thumbnails in your groups (go to the add-ons preferences, disable "Show tab thumbnails" and click the "Set these options for all groups" button), and see if that helps at all. Thumbnails are definitely the biggest memory hog in the add-on (although it should be comparatively small as it is but it's still something of course), so disabling them could be of some help.

As for my honest opinion. 500 tabs on a 32bit system is a lot! To put it quite frankly, you're reaching your system's limits like that. I would love to try to bring the add-on's memory footprint down even further, and I'm always trying to find ways to improve that, but it can only go down so much before the only solution becomes to remove features.

And even more honestly, the fact that disabling your other add-ons effectively doubled the amount of tabs you had open tells me Tab Groups isn't really consuming all that much memory, at least in comparison.

You could try [add-ons that unload tabs without closing them](https://addons.mozilla.org/firefox/search/?q=unload) to try and save some resources in the long run. They should definitely help with memory issues. (I don't really know which one is best or works better, just try one and see how it works for you. Of course make a backup of your groups and tabs first, just to make sure.)

**Comment by claell** [comment]
This might be an issue of too much memory used, but normally then also swap would be used and everything would turn very slow because of that and one would notice it. Firefox should not crash because of this normally, right?

**Comment by Quicksaver** [comment]
I honestly don't know how Firefox works with swap... What you say is possible, but it's also possible that it tries to use swap and it crashes/runs out of memory anyway, because it's too slow to be usable.

**Comment by claell** [comment]
Yes, anyway this seems rather like a problem of Firefox and not of the addon.

**Comment by whismerhill** [comment]
it's just that for heavy tab usage, 64 bit is now the minimum, I easily reach above 3GB with firefox 64 nowadays. 
Just taking his base example : the limit of virtual memory addressable for a given 32bit process on a 32bit Operating system is 2GB unless the process has the LAA flag & the OS has the 3GB extended memory flag, in which case it can go up to 3GB max per process.
virtual memory = all memory including RAM & swap
so 1.5GB real ram + 0.5GB swap = ? we're already near break points and I'm not even considering the highest usage scenarios he mentioned.

if one wants to know more about his own process memory usage, fire up process explorer by mark russonovitch (program hosted at Microsoft) then watch the "peak working set" after a while of you having used the software in what you consider a typical usage scenario.

Also caching temporary results in memory that will be reused is much more intelligent than recalculating the results all the time. In the first case you use more memory, in the 2nd case you use more processing power.  memory is cheap nowadays, processors are not

And finally this issue should probably be closed, I don't think it belongs to tabgroups

**Comment by Quicksaver** [comment]
> And finally this issue should probably be closed, I don't think it belongs to tabgroups

I actually had meant to close it before.
