### ISSUE TITLE
Disable/Enable tab groups

### ISSUE THREAD

**Issue by bltnkl** [Quicksaver/Tab-Groups#335]
Hello, Luís. 
I appreciate your rewritten version of add-on.
In my opinion, it would be nice, if one could temporary enable or disable tab groups, 
so that one would not have to go thru hassle of scrolling all tab groups they did not need at the moment. 
For instance, programmers could benefit from disabling bank, gift, email tab groups (so that they do not appear while scrolling thru tab groups),
to focus on their programming-related tab groups, like doc, forum, search and the like.
Thanks.

**Comment by Quicksaver** [comment]
I'm already planning a subgroups feature, which should provide very similar benefits to this. After thinking about it a bit, I think that will turn out to be more powerful even in this case, because it'll still be easier to switch to other groups, while with this you'd have the added task of enabling/disabling them (somehow).

For now, you can also use [Session Manager](https://addons.mozilla.org/firefox/addon/session-manager/) to keep different sessions saved, and toggle between a programming session and any other misc sessions. That way, your tabs and groups are kept completely separate. I know it's not exactly the same as what you asked, but it's still similar so I thought I'd suggest it.
