### ISSUE TITLE
RFD: double ESC after tab search opens the tab

### ISSUE THREAD

**Issue by leggewie** [Quicksaver/Tab-Groups#343]
You are in single view and want to search for a tab. You type ABC but realize what you really want is XYZ. You are used to hitting ESC several times in a row to reset everything.  On the first hit of ESC you are taken out of search mode which is what you want.  The second hit takes you out of single view and opens the current tab which in my case is not what I (usually) want. I understand and appreciate that generally when you are in single view mode you'd want a single-press of ESC to bring you back into normal browsing mode.  Just wanted to put this out there for discussion as it decreases usability for me somewhat.  Maybe there's a better way.

**Comment by Quicksaver** [comment]
> You are used to hitting ESC several times in a row to reset everything.

That's the key sentence here. ;) You really shouldn't be doing that at all, it's bad practice to just jam on a key until "things work". I don't see how "pressing esc once" can't be seen as the desired or expected behavior, so much that it would need extra code to ignore further esc keypresses (which would also conflict with when you actually want to leave groups view that way).

Feel free to discuss further and try to convince me otherwise, but I very much doubt you'll be able to change my mind on this one.
