### ISSUE TITLE
new UI is a huge step down from original

### ISSUE THREAD

**Issue by autonome** [Quicksaver/Tab-Groups#357]
Unfortunately the new UI and the new features are a massive change from the original. You really should have released 2.0 as a separate add-on entirely. It's *far* too different to call it the same thing.

The visual design should be reverted back to the original styling.

**Comment by Quicksaver** [comment]
The old UI is all still there. As explained in the release notes, in the add-on description, and in the "How to use" page in the add-on's preferences, you can easily restore any previous behavior you want. You can disable the "Click to show the quick access panel" option in the add-on's preferences, so that clicking the button takes you directly to groups view, and you can still use the previous free arrange mode if you prefer it over the new interface.

**Comment by autonome** [comment]
Yes, I understand that. I feel that your decision to make the new changes
the default and to completely change the style is unfortunate.The design of
the new features is incredibly changed both in functionality and in visual
design from the original. People installed your add-on to begin with
because they *liked* the old functionality and old look and feel.

Really fantastic work on the original one, and I will forever be in your
debt for that.

**Comment by Quicksaver** [comment]
I change default behavior when I feel it will benefit the majority of users, and especially new users, which is the case. I provided the ability to have the previous behavior for those who still prefer it, but other than that, whether a feature is new or already exists should not play any part in what becomes default. Something shouldn't be default forever just because it's what came first.

**Comment by autonome** [comment]
Ok. Do you mind if I fork and release your previous addon as Tab Groups
Classic?

**Comment by Quicksaver** [comment]
I mind but I can't stop you from doing it. But why would you? As I said, all the previous interface, features and functionality are still there, and I'm already planning to make a few changes for the next update to bring it closer to what it was before. I don't see any gain from doing that; on the contrary, you would lose a bunch of bug fixes and compatibility fixes for other add-ons, not to mention updated code to work with newer Firefox versions.

**Comment by autonome** [comment]
As I said previously, I think it's quite confusing that you made this
add-on as the tab groups feature that was in Firefox, but as of your 2.0
release the default experience is no longer the original tab groups in any
way. The default experience is now extremely different in look, feel, and
behavior from the original. And it wasn't clear to me that I could change
it to look and behave the old way.

My trust as a user of your software has been lost by your judgement in the
2.0 release. I know it was hard work to make all those changes, but
unfortunately I think it's far off the mark from what users of the Tab
Groups wanted.

I think a better path would have been to respect the reason why users
installed your add-on in the first place, and leave the look and feel and
behavior as it was. You could've offered the behavior changes, the
additional functionality and the complete re-theming as a separate add-on,
or as an option to turn on, but not the default.

I know you disagree with my opinion. So we can agree to disagree, and
that's ok :)

**Comment by iShyboy** [comment]
Even the browser itself changed so much, I don't think TG it's in anyway worse, the old behavior it's all there, and improved at that, even if you don't bother to read the notes, with just a couple of glances you can do what you've always do. This diehard rule of 'aint broke dont fix' wont get anyone anywhere. Not few users asked for those changes, and even less so don't approve it (those who voiced it, though).

**Comment by autonome** [comment]
Great for them, and you. I'm not asking to prevent anyone from having the
new stuff :)

**Comment by Quicksaver** [comment]
> As I said previously, I think it's quite confusing that you made this add-on as the tab groups feature that was in Firefox

Because groups were removed from Firefox a bit abruptly, and I had very little time to get a "working" add-on version of that feature together. The goal was always to rewrite, revamp and enhance everything with time (which, by the way, was what was supposed to happen with the original feature in Firefox, but no one could/would have done that there, so they decided to remove it before it broke completely and hindered development of other things any further). The old code that was in Firefox was... awful. In every way I can think of.

> I think a better path would have been to respect the reason why users installed your add-on in the first place

You shouldn't assume your reasons are the same as others' either. Of course there are a few that prefer the old interface, but, again, that's why it's still there. ;) I can tell you from a lot of feedback that I've received, that almost all users installed it because of some aspect or functionality in groups they wanted (i.e. tab management), not because of the interface itself. But unfortunately it's human nature that discontent with lack of homeopathy will always be louder. :(

> I know you disagree with my opinion. So we can agree to disagree, and that's ok :)

That's the thing, I do disagree with your opinion but that's not what you're focusing on it seems. You asked to release an older version of the code as a forked add-on (which you're free to do), but so far I haven't seen any reasons that would bring anyone any benefit in doing it (which is why I said I mind). "Different default behavior" is hardly a reason to do that, especially since for new users the new interface is arguably simpler and easier to learn.

You could argue that there are a few differences indeed, and the experience isn't **exactly** the same as before no matter what settings or modes you use. That's absolutely true, and I wish I had had the chance to work on those before releasing it. But as I said, I already plan on addressing those issues and enhancing the classic things (free arrange and such) even further as soon as I can.

If that doesn't/won't address your issues with the new version, there's not really much I can do then, and your choice is to either use an older version or create a fork as you want. :)

**Comment by Slater91** [comment]
I find myself in accord to autonome's position, or at least to part of it. What I mean is that I found myself completely lost with the new version 2.0, mostly because I had all tabs organized visually to fit my particular usage of Firefox and of the Tab Groups add-on.
Seeing such drastic changes which are not only visual, but affect functionality too by a large amount, made me revert to the old 1.x version. Here is a practical example: the fact that groups and previews are now larger makes it impossible for me to work the same way I did before, because groups do not have the same space they had before and I cannot arrange them the way I like. 
Truth be told, that may actually be a nice chance to clean up the 200+ tabs, 25+ groups mess I made in Firefox, but I feel I should not be imposed to change my behaviour because of changes in an add-on.
I did not find a way to revert back to the 1.x behaviour (small groups with little square previews), so I got back to the old version altogether. Instead of replying a bit harshly to autonome's criticism, maybe this can be a starting point to make a few changes which can improve Tab Groups' behaviour for everyone.
