### ISSUE TITLE
Zoom In/Zoom Out/Reset on one tab affects others from same host

### ISSUE THREAD

**Issue by SteveChessin** [Quicksaver/Tab-Groups#381]
If I have a given URL open in more than one tab, and Zoom In (Command +) or Zoom Out (Command -) on it in one tab to make the type bigger, it gets bigger in the other tab, too. And if I have a different URL from the same host open in a third tab, that gets bigger, too! And a Reset (Command 0) in any of the three tabs will reset them all back to their original size. (The tabs can even be in different windows.)

For example, try these URLs:
http://legacy.cafebonappetit.com/print-menu/cafe/207/menu/123942/days/all/pgbrks/0/
(Cancel the print pop-up it produces.)
http://legacy.cafebonappetit.com/weekly-menu/123942

Open each of them in two tabs each (for a total of four tabs), then pick one, Zoom Out a few times to make the type smaller, then inspect the other three tabs. Then Reset in one of those other three and go back to the first tab.

This is with Tab-Groups on Firefox 47.0.1.

If it turns out to be a bug in base Firefox and not Tab-Groups, let me know and I'll file a bug there.

**Comment by Quicksaver** [comment]
> If it turns out to be a bug in base Firefox and not Tab-Groups, let me know and I'll file a bug there.

That's my question. Does that happen if you disable Tab Groups? It does sound a lot like a bug in Firefox.

**Comment by SteveChessin** [comment]
What will happen to all my tabs and tab groups if I disable Tab Groups?
I'm afraid of losing them.

**Comment by Quicksaver** [comment]
Well, to prepare for a worst case scenario, you can always make a backup (in the add-on's preferences) from which you can restore your tabs and groups later. :)

To answer your question, that depends on your Firefox options. By default, as long as you don't restart, everything will be there once you re-enable it. But you can also go to your Firefox options after disabling Tab Groups, and set "When Firefox starts" to "Show my windows and tabs from last time", so that if you do restart you Firefox for any reason with groups disabled, they will still be there when you re-enable them,

Having said that, I would still recommend you restart after disabling it while testing, since if something is wrong with the add-on then a restart will ensure nothing remains of the add-on enabled. (Set the option I mentioned above and create a backup, if you still fear losing your tabs when doing this.)

**Comment by iShyboy** [comment]
FF bug, go there to report, I just started FF 47 in Safe mode and confirmed it.

**Comment by SteveChessin** [comment]
Turns out this is a Feature (undocumented, of course!) of Firefox, not a Bug. See
https://bugzilla.mozilla.org/show_bug.cgi?id=964082
and the bugs it references. Setting browser.zoom.siteSpecific to false in about:config seems to fix the issue.

**Comment by iShyboy** [comment]
What a dumb feature to be defaulted, it should need at least a refresh to apply the zoom in other tabs of the domain. Anyway good thing to disable
