### ISSUE TITLE
Restore Fixed Tab Groups on Restart 

### ISSUE THREAD

**Issue by Mithras42** [Quicksaver/Tab-Groups#382]
I would like it if I could set up a standard set of tab groups/tabs and save that as my start session for firefox starts.

I don't really want all my tabs from my last session restored, but there are a set of web sites I want when I start my day.  Is that possible ?

**Comment by Quicksaver** [comment]
I don't believe adding this ability would bring enough benefit to be completely honest; I don't mean to you personally, of course I understand your case, but I mean to the add-on overall.

Having said that, there are a few ways through which you can do that already:
- simplest is use pinned tabs, they remain even across sessions (or they should at least);
- you can set up your "default groups", make a backup of them using the add-on and restore them at any time after you start Firefox again; it's not "automatic" but it should work;
- you can also set up your "default groups" and use [Session Manager](https://addons.mozilla.org/firefox/addon/session-manager/) to create a backup and have it load it automatically instead of loading a new session.

**Comment by zefilipe** [comment]
Hi !

I think that will be solved ... !
In the past it had this problem to restore tabs ... !

And now, with the lastest version of Firefox (48), sometimes it continues to show popup to restore tabs .. !

Im using Session Manager, before to install TabGroups ... !
Regards
