### ISSUE TITLE
Multiple Tab Selection

### ISSUE THREAD

**Issue by M-G-ARC** [Quicksaver/Tab-Groups#384]
Thanks for the great addon, I just recently discovered it. Could you please tell me how many hours you think it would take to create the ability to select multiple tabs just like in chrome? For example: "control-click" and select multiple tabs. Or another would be holding shift and clicking a range of tabs.

I really would like this feature in Firefox natively and multiple tab handler does provide this feature, but I do believe it eats up resources (firefox is faster without it enabled) and there are some bugs using it with your extension which are on the tracker. I will gladly donate whatever I can for the you think it will take. I'm sure there are plenty others who would like this feature.

**Comment by Quicksaver** [comment]
This is essentially the same as #55, because when I add the ability to select multiple tabs in groups view, I will of course also add it in the normal tab view. So I'll track it all there.

As for your questions, I'm not really sure how long it would take, because everything related to tab selection/moving/opening/closing is almost all done by Firefox itself, so there's a lot I'd have to re-do in that code. At this point it's more a question of my availability than anything else, as I'm having some trouble setting up my new work environment (I'm sure that once I do it'll be one of those D'oh! moments) and it's been a couple of very busy months for me, leaving me even less time to work on it.

But it is one of the things that I definitely want to add in a future version. :)
