### ISSUE TITLE
Ctrl not available on OSX for keyboard shortcuts

### ISSUE THREAD

**Issue by Osmose** [Quicksaver/Tab-Groups#39]
First, thanks for maintaining this add-on! It's great!

With the new preferences for configuring keyboard shortcuts, the old shortcuts stopped working for me. In particular, I used ``Ctrl+` `` for switching to the next group, but I can't select `Ctrl` as a prefix for my shortcut. It'd be great if it was included in the list.

Thanks!

**Comment by Quicksaver** [comment]
If you check the "command" box, won't it work for ctrl as well?

**Comment by Osmose** [comment]
Nope! And, I now realize after testing it, setting it to ``Command+` `` or `Command+~` doesn't work at all; I can't get the shortcut to trigger with either of those selected.

**Comment by Quicksaver** [comment]
You mean Command+` won't work (actually pressing the command key, not the control key)? Does for instance Command+Shift+E work to toggle in and out of groups mode? As that's a whole other thing, and much more serious too.

As for control not working as command, that's very unfortunate, I was under the impression that it would work, but I guess not... I'll have to see what's the best way to address this, it's not as simple as just adding the control checkbox in there because the system itself probably won't recognize it as it is now if it doesn't already.

I have used this system for a long time in all my add-ons and you're actually the first one to report this to me, I don't actually have a mac keyboard to test it on, I just went with assumptions and testing by other users.

**Comment by Osmose** [comment]
> You mean Command+` won't work (actually pressing the command key, not the control key)?

Correct. 

> Does for instance Command+Shift+E work to toggle in and out of groups mode?

It does, when I configure it. However, with that shortcut configured, Ctrl+Shift+E does not work. This seems like it might be an issue specifically with `/~ as the shortcut.

I tested with a few other keys, and I think the common pattern is that any shortcut that is already assigned to something else doesn't work. I suspect that Command+` doesn't work because that is being consumed by the OSX "switch between windows within the current app" shortcut. 

> I have used this system for a long time in all my add-ons and you're actually the first one to report this to me, I don't actually have a mac keyboard to test it on, I just went with assumptions and testing by other users.

I'm happy to test any PRs that anyone submits to fix this. For the record, I'm on OSX 10.10.5 and Firefox 44.

**Comment by Quicksaver** [comment]
> I suspect that Command+` doesn't work because that is being consumed by the OSX "switch between windows within the current app" shortcut.

This will always be true. An add-on (or even Firefox itself) doesn't know of what keyboard shortcuts exist outside of it. I can't hardcode them either because I'm sure most of them will depend on the OS localization as well (this is true for Windows at least, but I'm sure OSX will act similarly).

I'm leaving those defaults as they are now because that's the same shortcuts in Firefox's native Tab Groups, to ease the transition process for most users. I will change those defaults sometime in the future though, I'm not a fan of them anyway. ;)

As for the rest, if I understand you correctly, it should be sufficient for your use-case to show a "Ctrl" checkbox in the shortcut in the preferences, so that you can define the ctrl key specifically for shortcuts in OSX. Let me know if that's not correct or optimal.

**Comment by Osmose** [comment]
> As for the rest, if I understand you correctly, it should be sufficient for your use-case to show a "Ctrl" checkbox in the shortcut in the preferences, so that you can define the ctrl key specifically for shortcuts in OSX. Let me know if that's not correct or optimal.

Correct, that sounds great!

**Comment by Quicksaver** [comment]
If you don't mind temporarily installing an unsigned beta version, can you please try [v1.0.2b1](https://github.com/Quicksaver/Tab-Groups/releases/tag/v1.0.2b1) and see how it works for you?

**Comment by Osmose** [comment]
It works great! Checkbox is present and binds properly, and my old shortcut is working again. Thanks a ton!

**Comment by Quicksaver** [comment]
I'm glad to hear it. :)

**Comment by andrewr01** [comment]
I use Ctrl + ` in Windows and want to use the same in Mac OSX. However, when I sync Firefox, the Ctrl tickbox in Windows gets added as Command in Mac OSX. Which means in OSX I get Command + Ctrl + `.

**Comment by Quicksaver** [comment]
The shortcuts you want to define are different. Command in mac is equivalent to control in windows, so the add-on syncs it as such. You have to not sync those shortcuts, by going to about:config and toggling to false those preferences you don't want to sync, and define the shortcuts you want yourself in the add-on's preferences in each system.

This is actually easier than it sounds. The preferences you're looking for start with ```services.sync.prefs.sync.extensions.tabgroups.```

There are three shortcuts:
- ```tabView``` - main shortcut to enter and leave groups mode
- ```nextGroup``` - switch to the next group
- ```previousGroup``` - switch to the previous group

Each of those has five controllers:
- ```Keycode``` - the key defined to do the action
- ```Shift``` - shift
- ```Alt``` - alt in windows and linux, option in mac
- ```Accel``` control in windows and linux, command in mac
- ```Ctrl``` - control in mac (ignored in other systems)

For example, if you don't want it to sync the command/control key for the main shortcut, you should toggle to false the following preferences in your systems:
- ```services.sync.prefs.sync.extensions.tabgroups.tabViewAccel```
- ```services.sync.prefs.sync.extensions.tabgroups.tabViewCtrl```

They won't be sync'ed and will stay as you define them in each system.

**Comment by andrewr01** [comment]
@Quicksaver - Awesome! Thanks for that fix. Really helpful. 

Cheers
