### ISSUE TITLE
Feature request: auto backup tabs with user controlable options

### ISSUE THREAD

**Issue by sakura26** [Quicksaver/Tab-Groups#392]
It just happens again, close Firefox normally, and after restart, all tabs lost.
All the auto backup is too old so I lost all the data of my work.
Its really a bad experience.

If there is a option I can set auto backup hourly or something, I think it will help alot.
Thanks.

**Comment by Quicksaver** [comment]
You can use an add-on like [Session Manager](https://addons.mozilla.org/firefox/addon/session-manager/) to set automatic backups of your session, and so much more. There's no need to implement the same functionality in Tab Groups, as both add-ons should work just fine together.

Have you checked your Firefox preferences:
- "When Firefox starts" should be set to "Show my tabs and windows from last time";
- In the privacy page, Firefox should be set to "Remember history".

When you lose your tabs, have you tried going to the History menu and clicking on "Restore previous session"?

**Comment by sakura26** [comment]
thanks for advice, I will try session manager now.

Of course I checked those preferences, but its not always working right.
Sometime after restart, only about:blank page shows and the "restore previous session" gray and  disabled.
It means the tabs data lost, right?

**Comment by Quicksaver** [comment]
Unfortunately yes, that's usually the case. It happens most often during crashes, where Firefox actually crashes on shutdown rather than shut down correctly (even if it doesn't tell you about it). Sometimes you can still restore them from a couple of backups still, did you try going to the Backup and Restore page in Tab Groups' preferences and see if you could restore your tabs from any of the "Session Recovery" options? They exist specifically for the purpose of restoring your session in case of crashes, but if you have been using a new session for too long, they will have been overwritten already most likely; doesn't hurt to still check though.

And Session Manager will definitely give you a better chance to restore things should it happen again.

**Comment by sakura26** [comment]
Session Manager is great! Thanks very much!

Yes I go to the "Session Recovery" options at first time, but the "previous" and "recovery" data is too old, just before I install the tab groups extension. (really strange...)
There is some other firefox upgrade backup, but its too old too.

Anyway, I am very glad to know 2 awesome extension today.
Thanks so much, It makes my day :)

**Comment by stukdev** [comment]
Useful tips, i suggest show this tips in the backup session.
"If you want backup automatic try session manager"

**Comment by Quicksaver** [comment]
Yeah, I need to add a more detailed note about Session Manager somewhere, it truly is awesome for session-related things like these.
