### ISSUE TITLE
Tab Groups button disappears after installing the add-on

### ISSUE THREAD

**Issue by AeroS1** [Quicksaver/Tab-Groups#4]
As the title says and the button is not under the customize section for FF42 either.

**Comment by Quicksaver** [comment]
That's weird, the add-on should place its own button in the same place where you previously had the Tab Groups button (in fact you shouldn't even be able to tell something happened there, as the two buttons look exactly the same).

What operating system are you using? And could you try with all your other add-ons disabled? Perhaps there's a conflict that's preventing Tab Groups from initializing properly.

**Comment by klonamy** [comment]
Is it disappeared or is the an empty space, where the icon should be?

OOT: I am a Firefox 43b7 user at the moment and it is functioning without problems.

**Comment by AeroS1** [comment]
My OS is Windows 8.1. I tried out disabling every add-on except tab groups but it still didn't reappear. It isn't an empty space, the tabs moved into the free space that it left behind.

**Comment by Quicksaver** [comment]
I'm assuming if you disable the Tab Groups add-on, the native Firefox button for tab groups reappears where it was?

**Comment by AeroS1** [comment]
It reappears in the customization screen but not in the location I originally had it, I have to move it back.

**Comment by Quicksaver** [comment]
Hmm, it's possible something moved the native button out of its place during the first initialization (I can assure you it wasn't this add-on as it does not touch that button at all).

Could you enable this add-on again and check if its button in the customization area as well, or anywhere in sight?

**Comment by AeroS1** [comment]
Did that and It isn't anywhere I can see it. I also seem to have made a mistake in my last post, the icon doesn't move at all, it does just disappear from the original spot, so I'm not sure why I saw it in the icon section when I first disabled the add-on.

**Comment by Quicksaver** [comment]
I'm sorry ahead for the trouble, but I'm going to need you to follow a few steps for me, to find out what's happening. First, please disable the Tab Groups add-on and restart the browser (just in case).

Then go to the add-ons manager and prepare to enable the add-on, so that all that's left to do is click its enable button (but don't click it just yet). Then open the browser console (Ctrl+Shift+J) and clear it.

Now enable the add-on, and see if any errors or messages appeared in the console.

**Comment by AeroS1** [comment]
This is what is marked as an error.

[CustomizableUI] "TypeError: aContainer is undefined -- resource:///modules/CustomizableUI.jsm:1155"

**Comment by Quicksaver** [comment]
Well that's just weird, it means Firefox's customization system is failing to place the button where it should be, but that error should never happen at all...

Ok, let's start with where that is. Again in the browser console with the add-on enabled (you don't need to follow all the instructions above, just open it right now as long as the add-on is still enabled, otherwise enable it first), paste this in it:
```JavaScript
CustomizableUI.getPlacementOfWidget('tabGroups-tabview-button') 
```

It should return either "null" or something like "Object { area: "something" position: 12 }". Could you paste the result here please?

(If you don't have a place where to type in the console, you'll have to open an "about:config" tab and enable the preference "devtools.chrome.enabled". You can disable it again after we figure this whole thing out.)

**Comment by AeroS1** [comment]
Here you go

Object { area: "TabsToolbar", position: 6 }

**Comment by Quicksaver** [comment]
So it should be right up there at the top after the tabs. Can you attach here a screenshot of your window please?

**Comment by AeroS1** [comment]
This is how it looks like with the add-on enabled

![firefox window](https://cloud.githubusercontent.com/assets/16116365/11539336/6653bb2a-98db-11e5-834c-5bd149910d93.jpg)

**Comment by Quicksaver** [comment]
Hmm, I wonder if it's because you have your tabs at the bottom (even though it shouldn't really matter). Is that an add-on doing it?

Either way, let's try resetting it. In the browser console paste this:
```JavaScript
CustomizableUI.removeWidgetFromArea('tabGroups-tabview-button')
```
It may give you some error because the button isn't really there, but it doesn't matter, just confirm that its placement information was removed by pasting the following again and checking if it returns "null":
```JavaScript
CustomizableUI.getPlacementForWidget('tabGroups-tabview-button')
```

Then restart the browser and see if the button is in the customization area. If it is, try placing it anywhere you want, and see if it stays there after another browser restart and after disabling and re-enabling the add-on.

**Comment by AeroS1** [comment]
I use tab mix plus to have my tab bar there. The reset works and the icon appears in the customization area without having to restart firefox but when I go to place it where I want it, it ends up force scrolling the tab bar (even if there is just one tab open) then after that it doesn't appear in the spot and it isn't in the customization area anymore; restarting does nothing either.

**Comment by Quicksaver** [comment]
Ok, so the problem really is TMP's tab bar on bottom feature. If you notice, you're not able to move any other button there either, at least I can't. Can you confirm this? And if so, I advise you to take this to TMP's developers as I'm sure they'll want to fix it.

**Comment by klonamy** [comment]
@AeroS1 Did you try out the TMP beta?

**Comment by Quicksaver** [comment]
@klonamy at least for me the latest dev version doesn't help at all. I opened a thread at TMP's support forums: http://tmp.garyr.net/forum/viewtopic.php?f=2&t=19417

**Comment by Quicksaver** [comment]
[Tab Mix Plus 0.4.2.0pre.151212a1](https://addons.mozilla.org/firefox/addon/tab-mix-plus/versions/0.4.2.0pre.151212a1) should fix this.
