### ISSUE TITLE
Update tabs when start firefox

### ISSUE THREAD

**Issue by stukdev** [Quicksaver/Tab-Groups#407]
1. Open Firefox
2. Switch to group
3. The tab is open but is not update i've to hit F5 for refresh! 

Typical example is a homepage of a newspaper

**Comment by Quicksaver** [comment]
I'm missing something. When you first start Firefox, the tabs should be unloaded even (blank), until you switch to them. The currently active tab should automatically be refreshed (because it's unloaded so it loads that first time as well). Is this not happening?

I'm not aware of any Firefox preference that makes it start with preloaded/cached pages like that, rather than refreshing immediately upon being loaded. Does that happen in a clean profile with only TG installed? Does that happen if you disable all your other add-ons except for TG in your current profile?

**Comment by stukdev** [comment]
I've to try on a clean up profile, at the moment when i start firefox it reload the page from cache, i don't know why...

**Comment by Quicksaver** [comment]
Please re-open if you can give me the info I asked.
