### ISSUE TITLE
constantly losing all tab groups on restart

### ISSUE THREAD

**Issue by w-barath** [Quicksaver/Tab-Groups#410]
Basically, every time I restart my laptop I am afraid I will lose all my tabs.  It's happened more times than I can count.  Making a manual backup every time I shut down is not an option - that is far too disruptive and will affect my productivity far too much.

What options are there to make the tab saving / recovery options more robust?

**Comment by Quicksaver** [comment]
In your Firefox options, do you have "When Firefox starts" set to "Show my tabs and windows from last time" and in the Privacy page, is Firefox set to remember history?

**Comment by w-barath** [comment]
Yes.

I think the problem is that I have multiple windows open and the Tab 
Groups only associates itself with a single window.   Then saving them 
appears to depend on the order the windows are closed, ie it forgets all 
tabs from the window with Tab Groups if that window is closed before the 
others.  The order the windows are closed in is beyond my control 
sometimes.  The battery runs low, the laptop signals the desktop to shut 
down, the close order is random.

**Comment by Quicksaver** [comment]
As long as the session itself is restored, when you restart Firefox and it restores the "wrong" window (whenever you close a window actually), you should be able to go to the History menu/button and restore the window with the tabs and groups you want from there. Could you give it a try and see if that's helpful to you?

**Comment by Quicksaver** [comment]
Also, if you want to be sure it restores all windows, instead of closing your windows one by one, you should actually exit Firefox, by either going to its File menu - Exit, or opening its main menu (the three bars button at the top right) clicking on the "Exit Firefox" button (the power button at the bottom right corner of that panel), or simply right-clicking the Firefox icon in the taskbar and click on "Close all windows".

If none of that is helpful to you, please let me know.
