### ISSUE TITLE
Just a simple question :)

### ISSUE THREAD

**Issue by mikhoul** [Quicksaver/Tab-Groups#413]
It's not an issue but just a simple question.

Those days I try to remove addons/Userscripts that I don't use often to speed up Firefox a bit since I use a lot of addons + Usersrcipt + Userstyles 🙀

My question is does I have a real advantage in using _Session Manager_ addon https://addons.mozilla.org/en-US/firefox/addon/session-manager/  with _Tab-Groups_ at this point :question: 

I'm under the impression that it's a little bit of overkill.  😱

___________________________________________________________________________________

Also I was reading an article today about `browser.sessionstore.interval` internal session backup:  https://www.servethehome.com/firefox-is-eating-your-ssd-here-is-how-to-fix-it/

I was not sure but I think I read somewhere here that _Tab-Groups_ use the internal mechanism of Firefox session restore , if it is correct you will be interested to follow the bug about it on bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1304389

I was asking to myself could it be possible to integrate to _Tab-Groups_ a better backup mechanism that don't rely on the Firefox one ? 

This way it could be more effective and up to date than using one that wrote over 20 GIG of data each day on idle.

Let me know what is your take about it after reading the article and the bug on bugzilla. :smile:  

Regards :octocat:

**Comment by Quicksaver** [comment]
Thank you for the links. I will read that article and bug, unfortunately I can't do it right now, but I'll leave this open to make sure I don't forget. :)

> does I have a real advantage in using Session Manager addon with Tab-Groups at this point?

That's up to you. Both work perfectly fine with each other, and of course without each other. If you want the features Session Manager provides (auto-backups, ability to switch sessions easily, etc), then keeping it doesn't hurt. But if you don't then TG is perfectly capable of keeping its groups data on its own.

> I was asking to myself could it be possible to integrate to Tab-Groups a better backup mechanism that don't rely on the Firefox one ? 

It's not using a Firefox backup mechanism, it's using its session. I haven't read the article yet, but basically a session is... well a session. It's the tabs you have open. Groups need to be associated with those tabs and vice-versa, especially so that they are remembered when you close Firefox. The only way to do this reliably is to integrate them into the session as well. Whatever Firefox does plays no part in TG, other than backing up the groups info as well at the same time.

Firefox's session mechanism, despite that bug I didn't know about and probably a couple of others, is still far better than anything I could ever come up with on my own. :)
