### ISSUE TITLE
[ESC] escape key should return to previous tab

### ISSUE THREAD

**Issue by NiklasGollenstede** [Quicksaver/Tab-Groups#416]
__Current behaviour__:
Pressing the `esc`ape key while in the groups view does the same thing as pressing `enter`: It switches to the tab that is currently focused in the tab view.

__Expected behaviour__:
Escape should close the group view without changing the active tab. / It should return to the tab that was selected before the group view was opened.

**Comment by Quicksaver** [comment]
There's all sorts of actions you can do that change the perception of what esc should do there. You can move tabs around, open and close groups... It's very hard to know automatically "which" tab to "go back to", and even more difficult keeping track of all possible actions that could change that perception.

For instance, say you go into groups view, and move the active tab from the current group to another. Then you press esc. What is it supposed to do then? Stay in that tab? It's not "going back" because you will change groups because it's now in another group. Stay in the same but load another tab? That's also not "going back" because that tab is not there anymore. What if before hitting esc you close the active tab, or even the active group? Esc won't be able to "go back" at all anymore.

I believe it's just much more intuitive to have esc always do the same thing.

**Comment by NiklasGollenstede** [comment]
I don't think "go back to the tab that was active before opening the view" (unless it was closed) is complicated (in understanding or implementation).

I thought this was simply an oversight, but I see you had your thoughts on this. That's all I wanted.

Thanks!
