### ISSUE TITLE
Groups disapearing

### ISSUE THREAD

**Issue by TheKrister2** [Quicksaver/Tab-Groups#419]
Can't say I have encountered this problem before, but I was restaring my computer and booting into Fedora. Opening firefox I found all my groups gone, the only thing I had were the automatic backups but the backup from the previous session is the same as the one I was in. Had to restore a session from over a week ago, going to make backups daily from now on.

Other than that if I open another window I can not access my groups from that window, this I believe is Linux regarding the opened window as its own process, seeing as I'm not running a experimental version of firefox.

The loss of groups makes no sense and is what I wanted to bring up.

**Comment by Quicksaver** [comment]
> Opening firefox I found all my groups gone, the only thing I had were the automatic backups but the backup from the previous session is the same as the one I was in.

It's possible that when Firefox started up it didn't restore your previous session for some reason. Did you try going to the History menu and clicking on "Restore previous session"?

If that was greyed out it's likely the session was restored properly, but instead of reopening the window it just opened a new one. Did you check if you could restore a closed window from the history menu as well?

(Even if you restored your tabs from a backup, it's possible either of those options are still available, so it doesn't hurt to check out, at least to confirm that's what happened, so you know what to do if it happens again.)

> Other than that if I open another window I can not access my groups from that window

Groups are not shared across windows at the moment. See #174.

**Comment by TheKrister2** [comment]
It is probably just a bug with Firefox not restoring my session. I just thought I should mention it if on the off chance that it was related to the addon you would at least know about it.

I was unable to restore my previous session, but I managed to recreate most of the things I had in groups by digging through my history log, although much was lost.

The addons "Load Groups and Tabs from..." did eventually work after a reboot, but it only contained some of what I had, most was recreated from manual reconstruction. However, it works, and that is what is important, and also shows that I should make backups more often.

Either way I don't think this will repeat itself until Firefox experiences a similar bug. I did not know the addon did not share between windows, that is nice to know. Thanks for the reply though it helped put things into perspective and I do have to say I really enjoy your addon.

**Comment by Quicksaver** [comment]
You're very welcome, I'm glad you're enjoying the add-on. It does sound like it was some issue with not having saved your session properly. Please do let me know if this starts happening with any sort of frequency, and try those steps I mentioned before; although hopefully this shouldn't happen again anyway.
