### ISSUE TITLE
Tab switching is completely broken, clash with other tab addons (like AutoUnloadTab) [under aurora (45.0a2 2015-12-20)]

### ISSUE THREAD

**Issue by grinapo** [Quicksaver/Tab-Groups#42]
Regardless of e10s it is impossible to switch tabs since yesterday's firefox update. Clicking tab selects it but the window content stays. Had to safe-mode disable it since preferences doesn't open in its tab either, and neither does add-on settings. Funny effect.

**Comment by poke** [comment]
Are you sure you’re on Nightly? Because I have version **46.0a1** 2015-12-20 on Nightly right now, and everything is working fine there.

**Comment by dgutov** [comment]
Works for me on 45.0a2 (2015-12-20) too.

**Comment by SophiesFan69** [comment]
@grinapo I am experiencing the exact same thing here - 45.0a2 2015-12-20.

**Comment by olichtne** [comment]
I have the same problem, but with version 43.0.1

**Comment by grinapo** [comment]
@poke You're right, the channels were messed up a while ago and I have moved over from "nightly" to "aurora" (which is now titles itself as "developer edition" instead, that's why I misreported it).

But to make amends I provide the reason for the problem (at least here around) by permutating installed addons:

It has been caused by "**Auto unload tab**" addon. By disabling the addon FireFox tabs are working again. (There may be other incompatibility by other tab handling addons and since tab grouping implies lots of tabs it's expected that people install tab related addons.) 

Unfortunately for me I need tab unloading/timeout much more than tab grouping (300+ opened tabs, memory usage approaches infinity without it) so for the time being I have to disable tab groups and go report this problem to AutoUnloadTab author as well.

But I hope there's a problem possible to fix, I dearly love tab groups, especially for selecting a tab from a huge mass of them.

**Comment by Quicksaver** [comment]
It seems like this is caused by Auto Unload Tab's rebinding of tabbrowser's xbl with its own. To be completely honest, I have no clue why this is causing any issues at all, xbl just sucks sometimes (this is not the first time I've ran into xbl-related weirdness).

Unfortunately I can't seem to be able to fix this on my side, this affects all my add-ons too, and not just Tab Groups. I've just e-mailed AUT's developers, proposing a very simple solution on their end that would solve everything. Hopefully they will be able to implement it soon. A little pressure from AUT's actual users might help speed it up, nudge nudge wink wink. ;)

**Comment by def00111** [comment]
fixed this in version https://addons.mozilla.org/firefox/addon/auto-unload-tab/versions/0.8.1.7

**Comment by Quicksaver** [comment]
I'm not sure why the lower version number (I'm sure it was meant to be 0.8.9.7), but yeah that fixes the issue. :)

**Comment by def00111** [comment]
sorry,
here is the new link with the correct version number :)
https://addons.mozilla.org/firefox/addon/auto-unload-tab/versions/0.8.9.8
