### ISSUE TITLE
On FF restart the 'Switch to next group' hot key stop working

### ISSUE THREAD

**Issue by White-Owl** [Quicksaver/Tab-Groups#428]
FF v 49.0.1, Tab Group v 2.0.1

I set up my hot keys to Ctrl+F1 for "switch to next group" and Ctrl+Shift+F1 for "switch to previous".
Once FF restarts, the Ctrl+F1 combination stop working at all, but Ctrl+Shift+F1 continues normally. Opening the options page for Tab-Groups and changing the Ctrl+F1 to something else and then back - fixes the issue of the hot key.... until next restart of FF.

**Comment by Quicksaver** [comment]
It seems to work fine for me, those shortcuts work right after starting up Firefox. Please try disabling all your other add-ons except for Tab Groups and see if that helps. It's possible something else is holding onto the Ctrl+F1 combination (for some reason?), so the add-on fails to register it at startup because it thinks it's not available.

**Comment by White-Owl** [comment]
Yes. found it.
Tab Mix Plus has Ctrl+F1 for something called "Save this window". 
Strange that even if Tab Groups does not react on the hot key, the Tab Mix Plus does not react either... If TG cannot take the hot key on the restart, I would expect the previous addon to continue working with it. But I do not see anything.

Just tried to remove this shortcut from TMP and failed - it is greyed out. But this is a problem for another bug-tracker :)

**Comment by Quicksaver** [comment]
Oh nice catch, I didn't know about those features. I'll fix this for the next update.

By the way, they are greyed out because they depend on you using TMP's session manager, you have to Disable "Use Firefox's built-in Session Manager feature" to be able to modify those two keys. I don't believe changing them there will help with this issue though, because at startup they will have the default value and only after TMP fully initializes will they turn to whatever value you set (much like only then are those keys disabled), which is the problem.

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) should now initialize that shortcut correctly when TMP is installed (and not using it of course). Please give it a try and let me know how it works for you.

**Comment by White-Owl** [comment]
Yes, with the Beta version 2.1b2 this hotkey does work properly.
Thank you.

**Comment by Quicksaver** [comment]
Great! Thanks for letting me know.
