### ISSUE TITLE
Current Session only cookies not being adhered to?

### ISSUE THREAD

**Issue by snowbound** [Quicksaver/Tab-Groups#43]
I had been using TMP and its session manager. When I shutdown firefox and left it closed for a while when I started FF up again I was required to log back in again to my gmail and other web email accounts. However since reverting back to Firefox built in session manager so I can use Tab-Groups I find that I am still logged into these email accounts hours after Firefox has been shutdown. Is this behavoir part of Tab-Groups or is it FFox Session manager not throwing away current session only cooklies? Yes I made sure that the email accounts is not selected to keep me logged in. This is happening on multiple computers here with FF 34 and Tab-Groups

**Comment by Quicksaver** [comment]
That is definitely not Tab Groups doing. All the add-on does is append the groups data together to whatever other session data Firefox is already saving. The add-on does not change the rest of the session data in any way.

You might want to check the settings in Firefox's options - Privacy pane. In particular, if you change the "Firefox will..." preference to "use custom settings for history" you may be able to configure it how you expect it to work (I'm not sure though as I've never tried configuring it as you mentioned).

But I'm sure from the other thread that by now you're already using the beta and the latest TMP dev build so that both work correctly already. ;)
