### ISSUE TITLE
Tab Mix Plus crash recovery losing groups

### ISSUE THREAD

**Issue by Scorpio3002** [Quicksaver/Tab-Groups#460]
The session manager preserves groups when I save them manually, but after a session crashes, the "restore crashed session" feature will almost never preserve the tab groups, resulting in lost tabs.

**Comment by Quicksaver** [comment]
That doesn't sound like a problem with Tab Groups, but with TMP's Session Manager feature. Tab Groups plays no part in saving sessions. Have you contacted TMP's devs about this?

**Comment by Scorpio3002** [comment]
Not yet. I figured I'd post here, since to my knowledge TMP does not claim to support compatibility with Tab Groups.

**Comment by Quicksaver** [comment]
Hmm it should, I just gave it a quick try and it saves the session correctly (it even gives you a little "More tabs restored into hidden groups" notification, never noticed that, nice!).

Since you say this only happens on crashes, maybe it's something in its crashed session code that's skipping/ignoring hidden tabs (from other groups) or even the groups data itself.

Either way, I don't believe it's something I can fix on my end, especially if it's on crashed sessions (I assume by this that you mean Firefox has crashed and you lose your session). There's simply nothing the add-on can do at this point, because Tab Groups already doesn't touch session saving code at all precisely so add-ons like those can do their thing in peace.

Please try contacting TMP's devs first and see what they say. I'll be glad to make any changes on my side if necessary of course. But the way you explained it, it doesn't sound like an issue in Tab Groups itself at all.
