### ISSUE TITLE
No support for multiprocess/electrolysis

### ISSUE THREAD

**Issue by sbasher314** [Quicksaver/Tab-Groups#465]
I'm not sure if it's even at all possible, but this addon disables multiprocessing windows. It would be nice to have support for it.

**Comment by Quicksaver** [comment]
The add-on is already fully multiprocess compatible and recognized as such by Firefox. I believe that currently, Firefox disables multiprocess if it finds any add-ons installed at all, this will be changed in a future release to allow multiprocess with add-ons, but it's completely out of the control of the add-on itself.

**Comment by sbasher314** [comment]
That's strange. AdBlock Plus is at least one example of an add-on enabled fine under multiprocess mode, so that would eliminate Firefox disabling it due to just being an add-on which is the confusing part for me. it could just be that this digs deeper into the metal than something higher level like abp and therefore is disabled for that reason, but I'm at a bit of a loss as far as that goes

**Comment by Quicksaver** [comment]
You're right of course. I did a little digging, turns out in 49 a few certain white listed extensions can be enabled with e10s (I didn't know this), then in Firefox 50 all add-ons marked as multiprocess compatible (like Tab Groups) will be enabled as well. Check out https://wiki.mozilla.org/Electrolysis#Schedule
