### ISSUE TITLE
Issue when closing last tab of group

### ISSUE THREAD

**Issue by valsamis-d** [Quicksaver/Tab-Groups#466]
Hi!

I'm testing TabGroups v2.1 with the latest Nightly and Developer's Edition Firefox and noticed that when closing the last tab of a group instead showing the home page (set in Tab Mix Plus options) I get the "Manage my groups" page. Has anyone had that problem?

Thanks
Dimitrios

**Comment by Quicksaver** [comment]
Yeah, with TMP the behavior is tricky to get right (you can see a full discussion on it at #354).

The intended behavior by default is that, if you close the last visible tab, you may or may not want to stay in that group, or in other words you may or may not want to go to groups view to choose another group.

Basically, this was an intended change to try to address as many scenarios as possible. In your case, because you set it to open the homepage, it will take you to groups view. I will probably add a preference in the future to better control this behavior, but for now if you don't want that you'll have to set it to open the "new tab" instead.

**Comment by valsamis-d** [comment]
Hi!

Thanks for the reply and sorry for the duplicate post (my bad I didn't search thoroughly).

Well, I tried your suggestion of setting TMP to open the "new tab" instead of the homepage but still the behavior is the same; i.e. I get to to "Manage my groups" page.

Anyway, I can wait for a new release.

Thanks
Dimitrios

**Comment by Quicksaver** [comment]
> I tried your suggestion of setting TMP to open the "new tab" instead of the homepage but still the behavior is the same; i.e. I get to to "Manage my groups" page.

Only if you close that "new tab" that opens after you close the last visible tab in that group, correct?

**Comment by valsamis-d** [comment]
> Only if you close that "new tab" that opens after you close the last visible tab in that group, correct?

No. Every time I close the last visible tab I get to the "Manage my groups" page. It is as if I had left that TMP setting to "Home Page"

**Comment by Quicksaver** [comment]
It's working as expected for me, could you export your TMP preferences and attach them here please?

**Comment by valsamis-d** [comment]
> It's working as expected for me, could you export your TMP preferences and attach them here please?

Sure. Here you go...

[TMPpref.txt](https://github.com/Quicksaver/Tab-Groups/files/567357/TMPpref.txt)

**Comment by Quicksaver** [comment]
To clarify, the TMP setting I mentioned before is in ```Events``` - ```New Tabs``` - ```Load on New Tab```: ```New Tab Page```. Is this what you tried changing? Because if I change that, with the settings you gave me, it works as expected.

**Comment by valsamis-d** [comment]
You're absolutely right QuickSaver! I was changing the option in `Events - Tab Closing - When I close last tab replace it with... `. Thanks for looking it this!

**Comment by Quicksaver** [comment]
Alright. It seems like things are working as expected now. :) Please let me know if you have any other issues with it.
