### ISSUE TITLE
Session restore crashes since 2.1

### ISSUE THREAD

**Issue by slinkp** [Quicksaver/Tab-Groups#467]
Don't know if this is the same issue as #462 , but since upgrading to Tab Groups 2.1, I find that session restore doesn't work anymore.

If I shut down my computer before Firefox has fully stopped (which I sometimes do by accident because something (Lastpass) makes Firefox shutdown take a long time), then the next time I start, I normally get the "Well, this is embarassing" window with the option to restore tabs.  This has always worked flawlessly before - I get back all my tabs and groups.

But ever since 2.1, every time this happens, I see the session restore tab very briefly and then before I do anything it's quickly replaced with "Bad news first. This tab has crashed."  There is a button to restart the tab, but I've never got that to work - I just get the same "Bad news" message.

Fortunately, I can go into Tab Groups preferences and restore from a backup.  But it might be worth looking into whether Tab Groups is having a problem with session restore more generally.

In the attached screenshot, note that none of  the middle three options from 2016-11-01 will work - "Current Session Recovery",  "Session Recovery Backup", or "Previous Session" will not load.  The latest one that I was able to load was "Tab Groups Update Backup - 10/28/2016, 10:40:32 AM".
(I just added the manual backup from 11/01 at top, have not tried that one yet.)

![screenshot from 2016-11-01 10-49-29](https://cloud.githubusercontent.com/assets/98610/19893822/ef7ebad8-a020-11e6-8219-ebe885e9b64a.png)

**Comment by Quicksaver** [comment]
When this happens, you likely have a corrupted session. Restoring from backups is almost definitely the only choice you have at that point. Although if it keeps happening at startup, then your Firefox is either corrupting the session on shutdown, or those backups themselves are corrupted as well.

Note that if you have a corrupted session, those automated session recovery options you mentioned will likely be corrupted as well, so it's no surprise they don't work. 

The session-related functions in Tab Groups haven't changed at all since the last version. It doesn't actually save or restore the session (it never did), that's all Firefox's doing, the add-on merely appends the groups info to the tabs in order to be saved together with them.

You could try creating a new backup (**don't check** the "Backup session data" box!), then clearing your session and restarting Firefox, then import back from that newly created backup and see if that still happens. Please let me know if doing that helps at all.

**Comment by slinkp** [comment]
Thanks. By "clear session", you mean what - destroy all groups and close all tabs?

**Comment by Quicksaver** [comment]
Yeah, that's one way to do it. It may simpler to open a new window, close your existing one, and close Firefox and re-open it. Only the new (empty) window should be restored and everything else should be gone, although it's possible that either won't resolve the problem (for instance if it fails to clear whatever corrupted data your session has).

If that doesn't help, a more sure way to start a new session is to go to your Firefox's options, and set "When Firefox starts" to "Show my homepage" (or anything else other than show your previous tabs and windows). Then after closing and re-opening Firefox, your session should be completely new. After that, importing back your tabs and groups from a backup is the same, just don't forget to set "When Firefox starts" back to "Show my windows and tabs from last time".

**Comment by slinkp** [comment]
I followed your second paragraph and that seems to have cleared up the issue...  I've restored tabs a couple times without crashes.

**Comment by Quicksaver** [comment]
Alright, that's good to hear. Please let me know if it starts happening again.
