### ISSUE TITLE
default shortcut for "Switch to the previous group"

### ISSUE THREAD

**Issue by piem** [Quicksaver/Tab-Groups#475]
Hi,

The default shortcut to switch to the previous group is set to Ctrl+Shift+"\`", but when using a US keymap on my system (debian stable), I can not access this combination of keys, since hitting "\`" with the Shift modifier sends a "~".

Changing the shortcut to Ctrl+Shift+"~" did the trick.

The default shortcut is defined in [resource/defaults.js](https://github.com/Quicksaver/Tab-Groups/blob/master/resource/defaults.js#L57), but I'm not sure how other systems and keymaps behave.

Cheers, piem

**Comment by Quicksaver** [comment]
That's expected, if by pressing shift the keyboard sends another character, that's the character you need to define when using the shift key. That's been the default keyboard shortcut since groups were built-in Firefox, so I don't expect I'll be changing the defaults any time soon, as it could break the workflow of many users already used to it, and it's pretty much impossible to find a key that works fine in all layouts. It's easy to change as you've seen though. :)

**Comment by piem** [comment]
True. It took me some time to figure it out though, so hopefully this report will help someone ;-)

An option to 'learn' the shortcut by pressing the combination of keys would also help.

**Comment by Quicksaver** [comment]
I changed my mind on this. It was a recent change in the add-on code that caused the default key to stop working. I'll change the default to <kbd>~</kbd> so that it works exactly like before (for US keyboards, I wish I had a better alternative for setting a default for more keyboard layouts...).
