### ISSUE TITLE
Shortcut ctrl + spacebar not working

### ISSUE THREAD

**Issue by ZTHawk** [Quicksaver/Tab-Groups#492]
When using the shortcut ctrl + space to enter/exit the groups view then exiting does not work. No other combination which has spacebar included is working for exiting the groups view.

Tested it with a clean profile.

**Comment by Quicksaver** [comment]
This should be fixed in [beta version 2.1.2b3](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1.2b3). Please give it a try and let me know how it works for you.

Also note that <kbd>Ctrl</kbd>+<kbd>Spacebar</kbd> will not work at all in Firefox 52 and above (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Spacebar</kbd> will work just fine though). I have tried investigating and it seems it's likely due to a change in how keypresses are processed by the core of the browser. I haven't found a way to get it to work at all there, I will try again at a later time, but I can't make any promises on it, as it seems that combination is not received at all by the add-on.

Just thought I'd let you know, as it might be better for you to start getting used to another combination, just in case.

**Comment by ZTHawk** [comment]
Just tested with FF52 and different TabGroups versions.
Ctrl + Spacebar is working fine with: v1.0.2, v2.0 and v2.0.1 So it has to do with the v2.1.x versions.
