### ISSUE TITLE
Thumbnail icon threshold (size) [feature request]

### ISSUE THREAD

**Issue by ZTHawk** [Quicksaver/Tab-Groups#496]
The threshold before thumbnails switch to icons is at about 80px. In v1.0.2 this value was much lower so I could have smaller groups but still see the content and not the icon.
Thumbnails are helpful if having different pages of the same site.
My request would be to have this threshold adjustable. (or at least is it defined somewhere in code so I could patch it locally?)

**Comment by Quicksaver** [comment]
That threshold is actually 90 pixels.

Showing smaller thumbnails would occlude them behind the page's icon, and the tab's close button and other buttons (the sound playing / mute button). Even if that wasn't the case, the current smallest thumbnail is already next to useless, there is barely any detail already to be able to distinguish between even somewhat similar pages.

Both of these were also problems in v1. Yes, the value was much lower there, and you wouldn't really see the thumbnail at all, because once again both the page's icon and the close button would occlude it almost entirely. The new icons mode and the different limits for the thumbnails attempt to help with that, while still providing as much visual information as possible. And the new lower limit for icons-only tabs is even smaller than it was for v1..

> Thumbnails are helpful if having different pages of the same site.

My point. Most pages of the same site are meant to be similar. The very few differences in all of those would barely be visible (if at all) in so small thumbnails. There is no gain to be had by decreasing the thumbs lower limit.
