### ISSUE TITLE
Question ?

### ISSUE THREAD

**Issue by mikhoul** [Quicksaver/Tab-Groups#500]
Hi @Quicksaver ,

I know I'm not really at the right place to ask my question about FindBar-Tweak but I don't see any activity in the Issues in https://github.com/Quicksaver/FindBar-Tweak/issues since the Nov 17 2016 at least ;-) .

With Firefox 50.0 a strange bug happen the button of FindBar-Tweak, once you click on to search for some words the button stay in the "open position" forever, the only way to close it is to restart Firefox which is pretty annoying.  Screenshot: http://i.imgur.com/YzxlKIP.png

When I switch to another tab the search panel from FindBar-Tweak is always there since it is "stuck" on the "on" position.

I have open an issue and even another user opened one before me with no reply or acknowledgement ? 

 I'm almost sure something is wrong with Github and you are not notified of those issue cause usually you are pretty quick to at least acknowledge or not the Issues when they are opened, that's why I write here in the hope you will see it  😊

Here's the link to the issue: https://github.com/Quicksaver/FindBar-Tweak/issues/281

Have a great day ! :octocat:

**Comment by Quicksaver** [comment]
I do still see all the activity there, please don't open bugs here about it as well.

I haven't been active there because I haven't gotten to FBT yet. All my add-ons needs to be updated for the latest versions of Firefox, and I can only do one at a time, that's why it's taking me so long. I will get to it, and I do see all the posts and e-mails, I just don't respond because I really have nothing to add at the moment besides what I've said already. :wink:

**Comment by mikhoul** [comment]
Thanks for the quick reply, 

I was not sure you were receiving it, sorry for the disturbance.
