### ISSUE TITLE
Feature request: rename current tab group by right-click on title bar

### ISSUE THREAD

**Issue by ruda-almeida** [Quicksaver/Tab-Groups#505]
Hi, I wish it was possible to rename the current tab group by right-clicking the "Group xyz" label on the title bar.

Currently, I have to click the label, then click "manage my groups", then visually find the group, then click the label, then edit it.

I think my suggestion would greatly improve the work-flow of the users who rely on this great add-on, what do you say?

Thanks!

**Comment by Quicksaver** [comment]
If you mean the actual window's titlebar, that's just not possible. Specifically, I don't believe the titlebar can be given actions, or react with custom functions to clicks like that. But more than that, even if it could, the titlebar is part of the window as "a thing of the operating system", I don't believe it should act for such a specific feature like groups titles, not to mention titlebars aren't visible equally for every user on every system.

> I wish it was possible to rename the current tab group by right-clicking the "Group xyz" label on the title bar.
> Currently, I have to click the label, then click "manage my groups", then visually find the group, then click the label, then edit it.

I don't fully understand your request though. You should only see the group's name in the titlebar when you're already in groups view, so half of those steps have already been done by the time you'd want to change it.

When you're not in groups view, it's the current web page title that's visible there, so there's not any information at all about the current group to change even. (And right-clicking the current web page title to change the group's title is very counter-intuitive, so that's not happening.)

I'm closing this only because this is something I don't believe can or should be done. But feel free to continue the discussion if you believe I misunderstood you or if you still feel strongly about it.

**Comment by ruda-almeida** [comment]
Sorry, I think I didn't make myself really clear.  +_+"

When I mentioned "title bar" I actually meant the button / label / element where the "Group xyz" text is written. I want to be able to quickly change the current group name from there. 

I'm adding screenshots (they're in Portuguese but as you're based in Portugal I'm not providing translations) ;P

In the screen below, if I left-click, I can see a list of other tab groups, a "manage my groups" and a settings button.

![tela01](https://cloud.githubusercontent.com/assets/4602525/21084976/63c60f40-bff2-11e6-859b-9fe46a397de2.jpg)

If I right-click, I see a menu that, I assume, is part of the Firefox interface

![tela02](https://cloud.githubusercontent.com/assets/4602525/21084977/63c9f38a-bff2-11e6-8fc6-09b25d8c679a.jpg)

This same menu shows up if I click icons for other addons, such as uBlock Origin and a few others I tested. However, I assume it can be overridden, since for QuickJava it shows a custom menu:

![captura de tela de 2016-12-11 22-43-58](https://cloud.githubusercontent.com/assets/4602525/21085024/7b9624d8-bff3-11e6-9347-ad0507412897.png)

Well, my suggestion is, either by a right-click or by some other quickly accessible way, allowing the users to easily rename the current group name in one or two clicks. :D 

Thanks for your time and patience and your quick reply :)

**Comment by Quicksaver** [comment]
Ah, in that case, I already plan to add many group management capabilities to the quick access panel, including changing a group's name, to that quick access panel, so that you don't have to enter the main groups view to do it. I just don't know when I'll be able to get to it. It will probably happen as part of #5.
