### ISSUE TITLE
"New Tab" button disappeared in Group View

### ISSUE THREAD

**Issue by GJRobert** [Quicksaver/Tab-Groups#508]
![2016-12-14_10-46-11](https://cloud.githubusercontent.com/assets/655584/21168041/f8e564f4-c1eb-11e6-8c8e-f0b7ef40dff9.png)
There used to be a button on the last position of the Group View, to add a new tab. However this button disappeared on my MacBook since... a certain update (maybe 2.1)

I'm not sure if this was a feature or a bug 😨

**Comment by Quicksaver** [comment]
It was explained in the release notes for version 2.1. This is expected, the new tab button was removed because it caused more of a bother than it was worth (in hindsight, I probably should have never created it in the first place).

Now that button only appears in empty groups. And you can still right-click the empty area of a group to open its context open which lets you open a new tab in it. Or press Command+T as usual (works both when in a tab or in groups view).

**Comment by GJRobert** [comment]
Thanks for your explanation! I must have missed this part in the changelog...
