### ISSUE TITLE
lose all groups when I close firefox with X

### ISSUE THREAD

**Issue by summaries** [Quicksaver/Tab-Groups#512]
all my groups are being lost when I closeout firefox ( v50.1.0 )by pressing X 
in the upper right hand corner.

**Comment by Quicksaver** [comment]
That's expected in some systems (Mac OS X, some Linux environments), because hitting the X button only closes the window but doesn't quit the application (terminate the session). You have to actually quit Firefox (File - Exit, or Application Button (three bars button on the top right) - Exit Firefox) if you want it to restore the window properly the next time you open it.

In the cases where you may still click the X button by accident, sometimes you may still recover the previous window, by going to the History menu and restore a recently closed window from there. Other times you can restore the previous session from the same place. And yet other times neither will help you and you'll have to either create the window from scratch or import from a recent automated backup.
