### ISSUE TITLE
Allow for styling of Tab Group Helper tabs

### ISSUE THREAD

**Issue by Hebgbs** [Quicksaver/Tab-Groups#54]
I wonder, since the author of Tab Groups Helper decided to mention your addon, maybe you can return the favour by beautifying his tabs?

Implementation for this would be relatively easy for an experienced coder; Add a check for some popular addons that alter tabs, and apply their preferences for the TGH tabs as well. Two I can think off right off the bat are Tab Groups Helper (which comes with its own set of tab styles) and Glass My Fox (which has a variety of glass styles).

If you wanted to do Stylish compatibility, maybe you could have in your documentation a special comment that Tab Groups looks for in stylish.sqlite to style TGH tabs the same way as defined for Firefox's tabs.

To prevent strange issues from multiple addons styling the same element at-once, maybe there could also be a preference check for each supported addon, and only apply the style to TGH tabs when one or more other settings are default.

**Comment by Quicksaver** [comment]
As a rule of thumb, anything that "styles" something should be done by that same thing (whether it's an add-on, theme, userstyle, etc), not by other add-ons trying to mimic the same style, which is what I'd have to do.

I.e., I can't style TGH's tabs from within my add-on because... Well that makes no sense, since this is not an add-on that styles anything. It implements the groups and adds a screen to customize it, which is completely independent from any of the things you mentioned.

And FWIW, it's not as simple as "checking for things that style tabs and reapply that same style". Styles aren't just read and adapted like that. Almost always they have to be applied in order for them to do anything. and you can't just "infer" from one style automatically into another, you have to actually write the new style in order for it to work correctly.
