### ISSUE TITLE
List or other views instead of thumbnail view

### ISSUE THREAD

**Issue by mzso** [Quicksaver/Tab-Groups#56]
Hi!

I found that I mostly just pay attention to the icons and webpage titles (Which are severly truncated) because when you have a lot of tabs the thumbnails convey little usable information. Not to mention the fact I usually have several tabs open from the same website which because of the identical styling tend to look indistinct from each other.
(Also the unloaded tabs which are always empty...)

So to me a view that shows the tabs as  Icon/page title lists or similar would be more useful.

**Comment by tengwar** [comment]
See https://addons.mozilla.org/en-US/firefox/addon/tabgroups-menu/ and https://addons.mozilla.org/en-US/firefox/addon/tab-groups/

**Comment by mzso** [comment]
[**@tengwar**](https://github.com/tengwar) commented on [2016. jan. 19. 20:43 CET](https://github.com/Quicksaver/Tab-Groups/issues/56#issuecomment-172964014 "2016-01-19T19:43:52Z - Replied by Github Comment Enhancer"):
> See [https://addons.mozilla.org/en-US/firefox/addon/tabgroups-menu/](https://addons.mozilla.org/en-US/firefox/addon/tabgroups-menu/) and [https://addons.mozilla.org/en-US/firefox/addon/tab-groups/](https://addons.mozilla.org/en-US/firefox/addon/tab-groups/)

Thanks. Though I wasn't looking for a menu. They don't have the spacial orientation or the available area compared to panorama for starters.

**Comment by Quicksaver** [comment]
[Beta version 2b3](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b3) has the ground work for this. In the preferences, you can choose whether you'd like to stack groups (current behavior) or scroll groups when they have too many tabs to fit.

Right now, overflowing groups that can't fit at least three columns of tabs will list the tabs without thumbnails. I still plan to add equivalent per-group options so you can pick which groups should be stacked or scrolled, and also define which groups should always list tabs without thumbnails, regardless of how many it has.

**Comment by mzso** [comment]
Cool! The views look interesting.

However closing the issue might be premature. This issue in particular is manly about providing something other than thumbnails, such as a list view.

After a bit of tinkering I see that if I compress a group enough with "scroll the group" enabled It switches into a sort of list view. So if the groups could be set to always appear like that, then would be this issue actually closed.

A small bug: When the group is too small the scrollbar appears even when the tabs are set to be stacked, but it's not usable. (Or remains after I switch back from scroll mode. Uncertain.)
It's also quite narrow and easy to miss. And is mostly overlapped by the resize-corner thing when it is very small.

(BTW did the minimum size increase? Some groups in free arrange mode became stacked, I don't believe I left them like that)

**Comment by iShyboy** [comment]
@mzso 
![tg](http://i.imgur.com/JVp8Isr.png)
That was what he did in the change, I think it is exactly what you want. Even if a bit incomplete to my taste, but thats not 2b4.

**Comment by Quicksaver** [comment]
> So if the groups could be set to always appear like that, then would be this issue actually closed.

I closed the issue with a commit precisely for this. I will upload a new beta in a couple of days, as I want to finish something else for it as well.

> A small bug: When the group is too small the scrollbar appears even when the tabs are set to be stacked, but it's not usable. (Or remains after I switch back from scroll mode. Uncertain.)

Already fixed as well for the next beta. ;)

> (BTW did the minimum size increase? Some groups in free arrange mode became stacked, I don't believe I left them like that)

A little, yes, basically to make the thumbnails at least marginally useful; before the tabs could be compressed so much that the favicon and the close button could cover the thumbnail almost completely. I'm still not done in that front, I plan to try and give a more dynamic size to the tabs, so that the thumbnails more closely resemble your screen's aspect ratio; so it's entirely possible those groups that are stacking now could "unstack" when I do that.

**Comment by mzso** [comment]
[**@Quicksaver**](https://github.com/Quicksaver) commented on [2016. ápr. 11. 20:26 CEST](https://github.com/Quicksaver/Tab-Groups/issues/56#issuecomment-208487306 "2016-04-11T18:26:42Z - Replied by Github Comment Enhancer"):
> > So if the groups could be set to always appear like that, then would be this issue actually closed.
> 
> I closed the issue with a commit precisely for this. I will upload a new beta in a couple of days, as I want to finish something else for it as well.
 
My bad. Didn't pay attention to the commits.

[**@iShyboy**](https://github.com/iShyboy) commented on [2016. ápr. 11. 20:12 CEST](https://github.com/Quicksaver/Tab-Groups/issues/56#issuecomment-208482533 "2016-04-11T18:12:44Z - Replied by Github Comment Enhancer"):
> [@mzso](https://github.com/mzso)   
> 
> https://camo.githubusercontent.com/1222c371524ed4b8036211b6772f954cf1203cc0/687474703a2f2f692e696d6775722e636f6d2f4a5670384973722e706e67
> That was what he did in the change, I think it is exactly what you want. Even if a bit incomplete to my taste, but thats not 2b4.

Cool. There's an enermous amount of emtpy space though.
@Quicksaver  Maybe the tab url can be added after the titles? It's otherwise unusable space anyway.

**Comment by Quicksaver** [comment]
> @Quicksaver Maybe the tab url can be added after the titles? It's otherwise unusable space anyway. 

I would imagine this option is better suited for grid layout or free arrange mode, where groups are physically smaller. But it's not a bad suggestion.

**Comment by iShyboy** [comment]
+1 to the url thing.

**Comment by PR0PH3T** [comment]
I don't want to make a new issue just for this so i'll post my idea here. Hope you don't mind.

While the list view is a neat idea i don't find it very helpful. What i would like to propose instead is an option that would let you chose to use the website's favicon and the most representative color instead of thumbnails.

Basically this: [http://blog.margaretleibovic.com/2011/06/09/dominant-favicon-color.html](http://blog.margaretleibovic.com/2011/06/09/dominant-favicon-color.html)

I think it could be a nice little feature but i could be wrong, just an idea i would like you to consider.
Either way thanks for your time and for developing this addon.

**Comment by mzso** [comment]
[**@PR0PH3T**](https://github.com/PR0PH3T) commented on [2016. ápr. 12. 01:04 CEST](https://github.com/Quicksaver/Tab-Groups/issues/56#issuecomment-208604345 "2016-04-11T23:04:12Z - Replied by Github Comment Enhancer"):
> I don't want to make a new issue just for this so i'll post my idea here. Hope you don't mind.
> 
> While the list view is a neat idea i don't find it very helpful. What i would like to propose instead is an option that would let you chose to use the website's favicon and the most representative color instead of thumbnails.
> 
> Basically this: [http://blog.margaretleibovic.com/2011/06/09/dominant-favicon-color.html](http://blog.margaretleibovic.com/2011/06/09/dominant-favicon-color.html)
> 
> I think it could be a nice little feature but i could be wrong, just an idea i would like you to consider.  
> 
> Either way thanks for your time and for developing this addon.

So a big flat colored rectangle? I don't think that's of much use.
However if that color (or perhaps one that's generated from the webpage content) was used to color the background of the the text in list view, it might be of some assistance in identifying tabs.

**Comment by Quicksaver** [comment]
> I don't want to make a new issue just for this so i'll post my idea here.

Wouldn't have hurt, better for keeping track of different things like this.

> an option that would let you chose to use the website's favicon and the most representative color instead of thumbnails.

I agree with mzso, that wouldn't be of much use by itself, since the favicon is already there regardless (which is the biggest point). Tiling only the favicons would hurt more actually, since most of them have a small size, which means small tab items in group view, which means not a lot of space to show the tab title. At most, its dominant color could be used as the background of the items (in list mode or with thumbs, it does work for both).

But regardless, there's one main reason I'm not implementing this. While it would work just fine for half a dozen tabs, it would lag the hell out of your browser if you had lots of tags. I have worked with dominant colors from images before, it takes a lot of processing to figure out the color (it has to pretty much comb the image pixel by pixel). It won't matter how effective the algorithm is, unless there's something miraculous out there, there's no way this can be done in a useful time for applying in all tabs in groups mode.

**Comment by mzso** [comment]
[**@Quicksaver**](https://github.com/Quicksaver) commented on [2016. ápr. 12. 10:54 CEST](https://github.com/Quicksaver/Tab-Groups/issues/56#issuecomment-208799732 "2016-04-12T08:54:17Z - Replied by Github Comment Enhancer"):
> it takes a lot of processing to figure out the color (it has to pretty much comb the image pixel by pixel). It won't matter how effective the algorithm is, unless there's something miraculous out there, there's no way this can be done in a useful time for applying in all tabs in groups mode.

It takes more processing time than generating a preview for the thumbnails?

**Comment by Quicksaver** [comment]
> It takes more processing time than generating a preview for the **thumbnails?

That's a good question, one for which I honestly don't have an answer. It's definitely worth investigating to see how much of a difference there actually is. If you (or anyone else) know how to create a basic system to do this comparison, you're welcome to do some testing and let me know of the results. Personally there's just so much left to do in the add-on I have no choice but to leave this for much later, especially because of what I said before, the gain is not that great, I hope you understand.

My (uneducated) guess would be: yes. The web page is already rendered by the time the thumbnail is taken, which is done by the rendering engine; all it does is snap a picture of what is already in the viewport. Calculating the most common color of a favicon would have to be done in javascript, and it would have to go pixel by pixel (the absolute lowest ones would be 16x16 so that's at the very least 256 cycles per favicon). Granted it obviously wouldn't do all favicons at the same time, it would still be something, every little cycle counts in javascript when it's multiplied by hundreds and thousands like that. It's not something that I would be willing to just write and put out there without some serious testing and optimizing.

**Comment by mzso** [comment]
[**@Quicksaver**](https://github.com/Quicksaver) commented on [2016. ápr. 12. 16:46 CEST](https://github.com/Quicksaver/Tab-Groups/issues/56#issuecomment-208942635 "2016-04-12T14:46:47Z - Replied by Github Comment Enhancer"):
> > It takes more processing time than generating a preview for the **thumbnails?
> 
> That's a good question, one for which I honestly don't have an answer. It's definitely worth investigating to see how much of a difference there actually is. If you (or anyone else) know how to create a basic system to do this comparison, you're welcome to do some testing and let me know of the results. Personally there's just so much left to do in the add-on I have no choice but to leave this for much later, especially because of what I said before, the gain is not that great, I hope you understand.
> 
> My (uneducated) guess would be: yes. The web page is already rendered by the time the thumbnail is taken, which is done by the rendering engine; all it does is snap a picture of what is already in the viewport. Calculating the most common color of a favicon would have to be done in javascript, and it would have to go pixel by pixel (the absolute lowest ones would be 16x16 so that's at the very least 256 cycles per favicon). Granted it obviously wouldn't do all favicons at the same time, it would still be something, every little cycle counts in javascript when it's multiplied by hundreds and thousands like that. It's not something that I would be willing to just write and put out there without some serious testing and optimizing.

That's okay. I was only asking because of curiosisty. It didn't feel heavier, because for the thumbnails also all the pixels are used for  downscaling the image to a miniature one. And the result is more complicated than a simple color value. Plus if we're going with favicons, they're much smaller than the almost total visible are the thumbnails use.

**Comment by Quicksaver** [comment]
> for the thumbnails also all the pixels are used for downscaling the image to a miniature one

Can't argue this point, other than I have no idea how downscaling works behind the scenes. ;)

**Comment by Quicksaver** [comment]
I think I've added to [beta version 2b4](https://github.com/Quicksaver/Tab-Groups/releases/tag/2b4) everything we discussed here so far. Please re-open if you find any issues with it.

About the favicons idea, I do like the concept, but the more I think about it, the more I think it's not very useful. Tiling them up as if they were thumbnails, they would either be too small to show the tab title even partially, or they would have to be scaled up to allow for bigger tiles, and that would mean almost all of them would be harshly pixelated.

Showing the most common color of favicons in listed mode (no thumbnails), there's very little gain there, and they would have to be solid colors (or very close to it) in order to be easily seen; there's no point in doing it if the effect wouldn't be visible after all.

Hmm... Based on all that and everything before, I'm closing this for now and moving on to other things. Of course you're welcome to continue discussing it to try to change my mind. :)

**Comment by mzso** [comment]
[**@Quicksaver**](https://github.com/Quicksaver) commented on [2016. ápr. 13. 20:14 CEST](https://github.com/Quicksaver/Tab-Groups/issues/56#issuecomment-209575520 "2016-04-13T18:14:41Z - Replied by Github Comment Enhancer"):
> I think I've added to [beta version 2b4](https://github.com/Quicksaver/Tab-Groups/releases/tag/2b4) everything we discussed here so far. Please re-open if you find any issues with it.
> 
> About the favicons idea, I do like the concept, but the more I think about it, the more I think it's not very useful. Tiling them up as if they were thumbnails, they would either be too small to show the tab title even partially, or they would have to be scaled up to allow for bigger tiles, and that would mean almost all of them would be harshly pixelated.
> 
> Showing the most common color of favicons in listed mode (no thumbnails), there's very little gain there, and they would have to be solid colors (or very close to it) in order to be easily seen; there's no point in doing it if the effect wouldn't be visible after all.
> 
> Hmm... Based on all that and everything before, I'm closing this for now and moving on to other things. Of course you're welcome to continue discussing it to try to change my mind. :)

I thought list view was one of the global views, or at least a global setting. But I only see options for it per group, to hide thumbnails. It'd be nice if I could do this globally.

Maybe you could take into the consideration some sort of preview when hovering over a tab. (Not necessarily just for list view.) Maybe even as a full size transparent overlay.

**Comment by Quicksaver** [comment]
> I thought list view was one of the global views, or at least a global setting. But I only see options for it per group, to hide thumbnails. It'd be nice if I could do this globally.

True.

> Maybe you could take into the consideration some sort of preview when hovering over a tab. (Not necessarily just for list view.) Maybe even as a full size transparent overlay.

What do you mean? Show the thumbnail when hovering a tab?

**Comment by iShyboy** [comment]
Preview as with TabScope in FF, or as big as Opera?
FF
![Scope](http://i.imgur.com/K8t39vC.png)
Opera
![Opera](http://i.imgur.com/2xmtMsc.png)

**Comment by Quicksaver** [comment]
I like that, but it won't make it in version 2 as there's far too much to do still. ;) BTW can you open a new issue for that? It's just to track it properly, it might get lost in here.

**Comment by mzso** [comment]
[**@Quicksaver**](https://github.com/Quicksaver) commented on [2016. ápr. 13. 20:41 CEST](https://github.com/Quicksaver/Tab-Groups/issues/56#issuecomment-209588788 "2016-04-13T18:41:13Z - Replied by Github Comment Enhancer"):
> > I thought list view was one of the global views, or at least a global setting. But I only see options for it per group, to hide thumbnails. It'd be nice if I could do this globally.
> 
> True.

Cool. 
> > Maybe you could take into the consideration some sort of preview when hovering over a tab. (Not necessarily just for list view.) Maybe even as a full size transparent overlay.
> 
> What do you mean? Show the thumbnail when hovering a tab?

Something a lot bigger and more usable. For exaple what @iShyboy showed. Those might be complicated, with sizing and positioning issues. But I think, what I suggested might be rather simpler: Just showing the page content for that tab with a high degree of transparency over the whole tab groups area.

**Comment by Quicksaver** [comment]
Added ability to set group options globally in [beta version 2b5](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b5). This is pretty much all that will happen for version 2 in this front. Please open new issues for separate suggestions for extra enhancements, such as the most common favicon colors, or the preview on hovering tabs.

**Comment by mzso** [comment]
Okay, I opened #199

**Comment by Quicksaver** [comment]
Anyone who was interested in tiling the page icons, please see #256 and give [beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) a try.
