### ISSUE TITLE
Rationale for cessation of development absent.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [Quicksaver/Tab-Groups#567]
http://fasezero.com/lastnotice.html doesn't exist anymore.

**Comment by BenjamenMeyer** [comment]
@rokejulianlockhart the issue is that Mozilla removed the XUL API Support and there would be too much work required to port it over to the WebExtensions API. There was actually a long discussion in several of this issues, see #535 for one example.

Simple matter is that Mozilla/Firefox didn't really care for supporting Tab Groups going forward (their discussions shows less than 4% of their users using it at all, and even a small fraction of that using the more advanced functionality) but kind of got forced into doing something because of extension writers that wanted to support it. Sadly, the manner in which WebExtensions work doesn't allow for the same kind of integration that Firefox use to have under their XUL API so things ended up in a very poor state all around, just like Tab Groups are in Chrome.

**Comment by dgutov** [comment]
> so things ended up in a very poor state all around, just like Tab Groups are in Chrome

I don't know if that's true, though. Simple Tab Groups (a newer extension) is working rather well for me, at least.

**Comment by BenjamenMeyer** [comment]
> > so things ended up in a very poor state all around, just like Tab Groups are in Chrome
> 
> I don't know if that's true, though. Simple Tab Groups (a newer extension) is working rather well for me, at least.

kind of - it still doesn't provide the same kind of access that the older XUL based ones did where you could have a whole page to see preview icons, organize groups, etc. Now it has to be done via a menu or the tab bar.

And yes, I've been using Simple Tab Groups in FF...but as the experience isn't really any different from Chrome I've been seeing less and less reason to use FF. The old XUL-based Panorama Tab Group interface was one of my main draws to keep with FF and WebExtensions has yet to provide anything to match it for either browser.

**Comment by 117649** [comment]
@BenjamenMeyer For what you're complaining I have something to show.

> > > so things ended up in a very poor state all around, just like Tab Groups are in Chrome
> > 
> > 
> > I don't know if that's true, though. Simple Tab Groups (a newer extension) is working rather well for me, at least.
> 
> kind of - it still doesn't provide the same kind of access that the older XUL based ones did where you could have a whole page to see preview icons, organize groups, etc. Now it has to be done via a menu or the tab bar.
> 
> And yes, I've been using Simple Tab Groups in FF...but as the experience isn't really any different from Chrome I've been seeing less and less reason to use FF. The old XUL-based Panorama Tab Group interface was one of my main draws to keep with FF and WebExtensions has yet to provide anything to match it for either browser.

You mean this?:
![image](https://github.com/Quicksaver/Tab-Groups/assets/8281345/ae4e30d1-d6a9-4649-9e53-76d8b950ac71)

The old XUL-based Panorama Tab Group interface turned into H5 and running on FF devEd 114.0b6. And of course, it can also run on Release and WaterFox.

**Comment by RokeJulianLockhart** [comment]
Rationale provided in https://github.com/Quicksaver/Tab-Groups/issues/567#issuecomment-1462425725, so this issue is closed as resolved. I'm not trying to prevent discussion, though.

**Comment by BenjamenMeyer** [comment]
@117649 considering that (a) the FF devs haven't made the APIs available and (b) that extension doesn't show up on https://addons.mozilla.org/en-US/firefox/search/?q=H5&type=extension I'm going to assume that it's something (1) not generally available and (2) reliant on some new features that are in the pipeline, especially since you're referencing a beta release of FF and a dev build at that. Would love to see that come back, but right now there's it's not in mainstream FF.

**Comment by 117649** [comment]
> @117649 considering that (a) the FF devs haven't made the APIs available and (b) that extension doesn't show up on https://addons.mozilla.org/en-US/firefox/search/?q=H5&type=extension I'm going to assume that it's something (1) not generally available and (2) reliant on some new features that are in the pipeline, especially since you're referencing a beta release of FF and a dev build at that. Would love to see that come back, but right now there's it's not in mainstream FF.

I'm using it daily on release channel FF, I put a screenshot of dev because privacy reason.

If you really love to see it what can stop you from learn how to do it? Rather then making assumption here why don't you try run it yourself? I have some links in the readme on my fork of this repo should point you to a start.
