### ISSUE TITLE
Not able to install onto FF ESR latest version (38.5.2)

### ISSUE THREAD

**Issue by areimunde** [Quicksaver/Tab-Groups#61]
There is problem and I'm sure I'm not alone. Using Firefox ESR version​
​ 38.5.2 which is the latest (and is based on FF 38), the add-on does not install. The big problem​
​ is, next major ESR release will be based on FF 45 ​​ so all ESR users will not be able to seamless upgrade to next major FF ESR version...

Why can't we install your add-on into current FF ESR v 38.5.2? I there a technical reason for not doing so? Or is just lack of testing so far?

**Comment by Quicksaver** [comment]
I *just* replied to your e-mail. ;)

> Unfortunately you're right that the add-on requires at least Firefox 41 to work, so it won't work with the current ESR, but it will definitely work with the next ESR 45.
When your Firefox updates, it will create a backup of your session (which includes all your groups and tabs). After this, when you install the add-on, you can go to its preferences, and in the Backup / Restore pane there will be a button called "Load Migration Backup", which will let you easily import back those groups and tabs.
Even if the "Load Migration Backup" in the add-on fails (it never did in my testing), you can always manually restore the backup file in your profile folder. There are instructions somewhere on how to do this too which I don't have at hand, but if you ever run into any trouble just let me know and I'll help. As long as you don't manually delete that backup file, you'll always have your tabs and groups safe.

**Comment by areimunde** [comment]
Whoa, that was fast ;-)
Thank you.

**Comment by Quicksaver** [comment]
A good option as you suggested is updating to FIrefox 43 or 44 and installing the add-on before updating to ESR 45.

Or on alternative you can also install Firefox 43 now in another folder (so you don't replace ESR), open it, install the add-on, close it (you can also uninstall it now). Then when you next open ESR 38 it will disable the add-on because it's incompatible and ask you to look for updates to the add-on (don't, it won't find any), but it won't remove it. So when Firefox updates to 45 the add-on will be there already, it will be enabled because it is now compatible, and you'll have a "seamless" transition.

I'll leave this open for now in case others come looking for the same thing.
