### ISSUE TITLE
Custom Colors/Apearance Settings

### ISSUE THREAD

**Issue by darth62969** [Quicksaver/Tab-Groups#67]
TabGroups with FT DeepDark looks Atrocious.

![http://i.imgur.com/ZJ7RS5c.png](http://i.imgur.com/ZJ7RS5c.png)

Fix it! I want some theme support transparency or some sort of personalization options sooner rather than later... 

That really should have been thought of... I don't want to have to force a Firefox to downgrade to 42, wait i do... I hate Firefox not having tab groups... so fix it! 

:P

**Comment by Quicksaver** [comment]
I can't tell if you're being playful or simply assume I'm here at the mercy of your whim... I'll give you the benefit of the doubt on that one and hope that's just because it's incredibly difficult to convey tone over text.

As a rule of thumb, themes really should take care of implementing themselves over whatever elements an add-on inserts, since the add-on can't just assume what the theme wants/needs to look like. The best start in these matters is contacting the theme developer first.

Having said that, I know that Stefano (FT DeepDark's developer) has very limited availability to work on his theme lately, so I'll take a look at what I can do from my side.

**Comment by darth62969** [comment]
playfull... but i really want it fixed.

i think i would be more satisfied if we could change the default colors and
alpha channel of the tab groups page anyway.

and thanks i really hate that Firefox decided to abandon the "tab whores."
you have done us all a favor.

(: Jonathan :)

**Comment by advcomp2019** [comment]
I was wondering about this too. I have tried emailing FT DeepDark's developer about another issue with your Findbar Tweak, but the email that I got back did not sounds too good. It sounded like he did not have the time to fix for these other addons that people are starting to like.

**Comment by Quicksaver** [comment]
> changing the title to something not as specific as i am not complaining about FT Deepdark's compatibility, more like the inability to personalize it one way or another

I changed the title because I will look into tweaking its appearance for FT DeepDark, but I will not add any sort of colors/transparency/borders/sizes/whatever customization options, those are just too much work to maintain for too little gain. You're better off writing your own stylish scripts to tweak whichever aspects you want (with which I'll more than gladly help if you need).

> **edit2:** i still think i sound pretty demanding... not trying to be, but...

Don't worry about it of course. ;)

> I have tried emailing FT DeepDark's developer about another issue with your Findbar Tweak, but the email that I got back did not sounds too good. It sounded like he did not have the time to fix for these other addons that people are starting to like.

I have already included a fix for FT DeepDark that will be in the next version of FBT, similar to how I will do here.

**Comment by darth62969** [comment]
>I changed the title because I will look into tweaking its appearance for FT DeepDark, but I will not add any sort of colors/transparency/borders/sizes/whatever customization options, those are just too much work to maintain for too little gain. You're better off writing your own stylish scripts to tweak whichever aspects you want (with which I'll more than gladly help if you need).

fine works, but like i said originally, i don't want a specific fix for FT DeepDark but, I get that writing a way to change things is more hassle than it is worth... Ren'py isn't exactly the easiest thing to script something like that into either. however it would be nice if the feature could still be implemented... i have no clue how to use stylish and don't really want ANOTHER add-on slowing down Firebox. especially one i will only use once, and on a specific element.

**Comment by johngraciliano** [comment]
@darth62969:
For ***Stylish*** (_Add-ons - User Styles_) a write a new style with only one line:
```
@import url(chrome://browser/skin/tabview/tabview.css);
```
(You will need to give it a name and save it!)
That seems to solve most of the issue.
To further fix a few more icons for FT DeepDark you could write:
```
@import url(chrome://browser/skin/tabview/tabview.css);
toolbar #tabGroups-tabview-button > .toolbarbutton-icon{filter:invert(.2)}
@-moz-document url(chrome://tabgroups/content/tabview.xhtml){
  #optionsbutton,#helpbutton{filter:invert(1.0)}
}
```

**Comment by darth62969** [comment]
i don't want another addon that slows FireFox down... i really don't like
having to have this one... but i need it.

(: Jonathan :)

**Comment by johngraciliano** [comment]
Are you implying ***Stylish*** slows down **Firefox**?  I am sure the solution will be in the ***Tab Groups*** extension. (I have not tried the pre-releases, so it may already be there!)

**Comment by darth62969** [comment]
I'm not implying, i am saying that i don't want more than i need, i have
tried stylish before and didn't like it for one, for 2 i didn't find it
that great. Extensions also slow down browsers regardless of what the
browser is. Firefox is no exception. just saying.

(: Jonathan :)

**Comment by johngraciliano** [comment]
I cannot argue.  Anyway, I proposed a solution for (most of) this problem in #86.
