### ISSUE TITLE
Show group name near the toolbar button

### ISSUE THREAD

**Issue by davidmach14** [Quicksaver/Tab-Groups#72]
For better user orientation will be useful if there will be place for showing current group name. For example right of the toolbar button...

**Comment by fabianvf** [comment]
+1, This would be hugely helpful

**Comment by Kasijjuf** [comment]
I support this idea

**Comment by Quicksaver** [comment]
In [beta version 2b5](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b5). Please give it a try and let me know if you find any problems.

Also note that there were a lot of changes in that beta since the last released version, so it's definitely worth it giving the "How To Use" page in the add-on's preferences a read, to get reacquainted with the basics.
