### ISSUE TITLE
Compatibility with FireGestures

### ISSUE THREAD

**Issue by Espyo** [Quicksaver/Tab-Groups#78]
I use FireGestures daily, and it's quite spectacular pairing it up with Tab Groups. I just do a simple gesture, and it opens up the tab groups so I can quickly and efficiently swap between "workspaces".

FireGestures has a builtin function that calls Firefox's native Tab Group open functionality. Unfortunately, now that I've installed the Tab Groups addon, this no longer works.

Of course asking you to specifically code in a way for FireGestures to interact with Tab Groups is not my idea. My question is: is there currently any way to communicate with Tab Groups and issue a "open tab groups" command via Javascript? FireGestures allows one to write their own scripts, and appears to refer to gBrowser quite often on most of the custom scripts out there. If there is any API call like gBrowser.addons.tab_groups.open() or something, that would solve my problem instantly. Instead of requesting such a feature, I am asking if it exists, or if there is any other alternative.

Thanks!

**Comment by Quicksaver** [comment]
Firegestures entry for Tab Groups apparently it loses its label in Firefox 45 as well, probably because it relies on the strings that will be removed then.

You should create a new user script and bind that one. Use the following one line in the script field:
```Javascript
TabView.toggle();
```

You might want to bring all of this up with Firegesture's developers too. All of its users will have the same problem as you, and this is not something I can fix within my add-on because of the way the original groups gesture is implemented (it's looking for a command that doesn't exist anymore, the add-on implements its own but it must do so with a different id).

**Comment by Espyo** [comment]
Thank you! That works wonderfully.

I agree. I'll try to get in contact with the devs.

I will leave the issue open, because you tagged it as a bug, so I'm not sure if you want to follow the issue up with anything. If not, feel free to close it.

**Comment by Quicksaver** [comment]
If you hear back from them please let me know, that's mostly why I left it open. And so that others can find the solution more easily as well. ;)

**Comment by Espyo** [comment]
Well thought!

Seem as though @vkapovit already [opened an issue](https://github.com/gomita/firegestures/issues/115). From that issue, it also seems that you had previously mentioned the "TabView.toggle()" trick somewhere else. I apologize for not finding it before opening this issue.

**Comment by Quicksaver** [comment]
You have nothing to apologize for. You couldn't have found it because I spoke with that user by e-mail. ;) And thanks for the link!

**Comment by Jellby** [comment]
I had configured FireGestures to switch to prev/next tab group with right-click+wheel (I don't remember if this was available from the start or I had to fiddle elsewhere). This worked and still works with this addon with FF 44. Will it stop working with 45?

The only trick is that I have to open the groups first, then it works for the rest of the session. Pre-44 I could simply show the list of groups and that was enough, now I have to actually show all the tab groups. Would it be possible to "fix" this, so that it works from the beginning?

**Comment by Quicksaver** [comment]
> This worked and still works with this addon with FF 44. Will it stop working with 45?

If it works now it will keep working.

> Pre-44 I could simply show the list of groups and that was enough, now I have to actually show all the tab groups.

What list? I'm guessing that list comes from another add-on because this add-on has no such thing (yet) so no.

You can skip that all by binding whatever gestures you want to the following scripts:
Next group: ```TabView.switchGroup(false);```
Previous group: ```TabView.switchGroup(true);```
That should work even without having to show the groups for, or showing whatever list it is you meant.

**Comment by Jellby** [comment]
> What list? I'm guessing that list comes from another add-on because this add-on has no such thing (yet) so no.

I mean with the built-in tab groups in FF.

OK. I see now that I had defined a user script in FireGestures. I've replaced those with your suggestions. So far it's working, I'll see at the next restart. Sorry for the noise :)

**Comment by Quicksaver** [comment]
> I mean with the built-in tab groups in FF.

There is no built-in list. Again, you must have an add-on like TabGroups Menu that's giving you that.

**Comment by Jellby** [comment]
OK. Then I don't know which addon was giving me the dropdown list :D I have "Tab Utilities Fixed", "Classic Theme Restorer", nothing else that looks related.

**Comment by ilpssun** [comment]
The solution of adding a custom script containing `TabView.toggle();` works perfectly.  I can understand that the addon itself cannot do anything about the issue but why not document this issue and the solution briefly in a more prominent spot than this git issue? I think that would help a whole bunch of people :-)

**Comment by Griffinhart** [comment]
I'm on Firefox 45.0.1 and adding a new script with ``TabView.toggle()`` does *not* work to invoke tab group Panorama view. I get a ``Reference error: TabView is not defined`` pop-up.

**Comment by Quicksaver** [comment]
> e: Looks like it's some kind of compatibility problem with Classic Theme Restorer - disabling CTR lets me use TabView.toggle() without issue.

That's weird, I'll investigate.

**Comment by Quicksaver** [comment]
There is absolutely no ```TabView``` reference in CTR code that I can see. Is this still happening for you?

**Comment by Griffinhart** [comment]
I haven't enabled CTR in a while, and am AFK right now. I'll check when I can.

**Comment by Quicksaver** [comment]
If this ever happens again please let me know. And with FireGestures adding that notice about the custom scripts, I believe this can be closed now.
