### ISSUE TITLE
Compatibility with FT DeepDark

### ISSUE THREAD

**Issue by ThoDHa** [Quicksaver/Tab-Groups#86]
The color for tab groups are not changed when I use FT DeepDark, The theme did set the colors correctly before I installed the addon.

**Comment by Quicksaver** [comment]
I was already planning on working on FT DeepDark compatibility (#67). Having said that, it's possible that FT DeepDark already has some styling code for groups that just needs to be enabled for the add-on. While that could work now, I'm planning a fair share of changes to the structure of the groups view which will probably render it all useless.

I'll have to take a look when I get to it.

**Comment by morganw62** [comment]
Awesome! I was just about to ask about this. I'm happy that this is in the works. Thank you.

**Comment by johngraciliano** [comment]
I wrote this patch with ***Stylish***:
```
@import url(chrome://browser/skin/tabview/tabview.css);
toolbar #tabGroups-tabview-button > .toolbarbutton-icon{filter:invert(.2)}
@-moz-document url(chrome://tabgroups/content/tabview.xhtml){
  #optionsbutton,#helpbutton{filter:invert(1.0)}
}
```
It seems to fix the issue for ***FT DeepDark***.

**Comment by johngraciliano** [comment]
@Quicksaver:
I strongly believe the file _chrome/content/tabview.xhtml_ needs the line:
```
  <link rel="stylesheet" href="chrome://browser/skin/tabview/tabview.css" type="text/css"/>
```
just before ```</head>```.  This would make the skin rules from the theme take precedence over the extension rules.  This solves mostly the issue with FT Deepdark.  Yet any affected theme may need new rules for the toolbar button because it has a different id, and for the preferences and the "how to use..." buttons that are new. Other particular rules may be needed for the preferences section.

**Comment by Quicksaver** [comment]
I can't include references to files that aren't built directly for the add-on. Case in point, the very next version will have some deep changes to the groups structure that the original statement in that file, either in the native Firefox theme or from other themes, are simply is not prepared to handle.

Even if for the current version that would (mostly) work, I can't make changes to those files from the add-on, and thus If I can't assure that those files work correctly with the add-on then they simply shouldn't be referenced by the add-on. For example, users using older (not updated) themes will be faced with some serious visual bugs that I won't be able to control from within the add-on in future updates.

> As a theme writer, I insist you should apply my suggested change because it will ease greatly the work on us to provide better support for you extension.

It really won't, you will still need to prepare for (major!) differences from the native groups. And as a theme writer it is much easier to control which files are loaded for what, using ```@-moz-document``` blocks in the CSS code.

**Comment by Quicksaver** [comment]
Unless you have no way, from within the theme, to load an unreferenced stylesheet into the tabview window. Is this the case?

**Comment by Quicksaver** [comment]
Oh, that should be possible through chrome.manifest at least.

**Comment by johngraciliano** [comment]
[**@Quicksaver**](https://github.com/Quicksaver) commented on [Feb 26, 2016, 11:13 AM EST](https://github.com/Quicksaver/Tab-Groups/issues/86#issuecomment-189348417 "2016-02-26T16:13:40Z - Replied by Github Comment Enhancer"):
> Unless you have no way, from within the theme, to load an unreferenced stylesheet into the tabview window. Is this the case?

Style sheets have to be referenced (as far as I know).  Yet you use rules from style sheets that are loaded (implicitly).  In particular, I added rules to my theme's file ```global/skin/in-content/common.css``` to correct how the options were displayed for this and a few other of your extensions.  But setting rules like that has a cost in more than one way.  Also the use of ```@-moz-document``` may not be possible now or in the near future because its availability is being limited for security reasons (see [bug (1035091)](https://bugzilla.mozilla.org/show_bug.cgi?id=1035091))*.  There may be limitations to what can be done through the ```chrome.manifest``` too.

I understand how external references present a security risk and how this link may be forbidden for extensions published at A.M.O.  I was yet hoping this css reference could be allowed.  After all, the browser code has theme references such as:
```   <?xml-stylesheet href="chrome://browser/skin/browser-lightweightTheme.css" type="text/css"?>```
These references will link the code from a complete theme, which should be validated by A.M.O.
_____
*I eliminated any use of ```@-moz-document``` in my theme once I found it was not working in a try-out version for testing the planned limitation.

**Comment by Quicksaver** [comment]
> Style sheets have to be referenced (as far as I know).

You can use [style rules in chrome.manifest](https://developer.mozilla.org/docs/Chrome_Registration#style) to load a stylesheet for a particular uri, which actually allows you a higher degree of control of what/where/when to load than I can achieve with the blind use of a link or xml-stylesheet element.

> Yet you use rules from style sheets that are loaded (implicitly). In particular, I added rules to my theme's file global/skin/in-content/common.css to correct how the options were displayed for this and a few other of your extensions.

That's a completely different case. The preferences tab is specifically meant to have the same look as Firefox's options tab, so the same style rules should definitely be applied there with as little changes as possible (none at all in most cases).

Here we're speaking about the groups dialog, something that is still structured in the same way as the original feature only because I haven't coded all the changes in yet. As I said, it will drastically change in the future, so I can't link to stylesheets that may exist and be incompatible with these changes. I **could** create a link to a new stylesheet, but I don't see how it's not better for the theme to load it itself.

> Also the use of @-moz-document may not be possible now or in the near future because its availability is being limited for security reasons (see bug (1035091))

That was originally meant for unsecure stylesheets from the web, it was not meant for stylesheets from themes for instance. It did break them (or at least it broke a few add-ons, I don't remember reports of a theme breaking from it) but that was unintentional, which is the reason for why it was backed out. When it is worked on again, it's highly doubtful it will affect either themes or add-ons.

> I understand how external references present a security risk and how this link may be forbidden for extensions published at A.M.O.

That's not my point. That's not external even, it would be perfectly fine by AMO's policies. What I meant was I am changing the groups view profoundly in the next few versions. If I add a link to stylesheets that are meant for the old layout, then I can't guarantee it will look correctly, then users will contact me about it and there will be nothing I can do because I can't make changes to that stylesheet from the add-on, I can only either reference it or not.

This way, I can ensure it will at least look "as expected", even if it doesn't fit in with the theme, since all the referenced sheets are in the add-on itself, and any needed changes can be done by the theme specifically or even by the add-on if necessary to help fit in.

**Comment by Quicksaver** [comment]
Added tweaks for compatibility with FT DeepDark in [beta version 2b6](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b6). Please give it a try and let me know if you have any problems with it.

Also, remember to disable any possibly conflicting custom styles, like the one posted above, as they will likely conflict, and they may not even work at all anyway, since FT DeepDark seems to no longer include its TabView-related code.

By the way, as you'll notice, there are a lot of changes in that beta, so it's definitely worth it giving the "How to use" section a once-through in the add-on's preferences, to get acquainted with the new and changed features.

**Comment by ThoDHa** [comment]
Took a quick look before work. Everything looks great! But it seems that the "new tab" window in the grid layout isn't consistent, In one group it shows area to create a new tab in that group all the time, but in my other group it only shows when the mouse is over that side of the box. In "Free Arrange' and in Autosize the area to create the new tab is always highlighted.


Thanks for implementing it though :D

**Comment by Quicksaver** [comment]
It always show the open new tab button in the current active group, to be more touchscreen friendly. In other groups it will only show if the mouse is over them.
