### ISSUE TITLE
Icon Submission: Tab Groups

### ISSUE THREAD

**Issue by MichaelTunnell** [Quicksaver/Tab-Groups#9]
![tab-groups-icon](https://cloud.githubusercontent.com/assets/1056731/11550662/7d0645fc-9937-11e5-82bb-5485113ea14c.jpg)

I just made this, feel free to use it if you want. I'll release this icon as CC so you can use it however you want.

**Comment by poke** [comment]
The inconsistent spacing is putting me off, even though it is meant to be there to make that “G” (which took me a while to notice). I prefer the simple one we have that is based on the original Panorama button icon.

**Comment by Quicksaver** [comment]
It's an interesting concept, thanks. But I'm with poke on this, I prefer the current "classical" icon. And to be honest, I wouldn't have noticed the G if he hadn't mentioned it either.

**Comment by AndrewFlet** [comment]
I agree with Poke & Quicksaver too, but am impressed by the effort of Michael to make this. Maybe it could be offered as an alternative, with the present one as the default?

**Comment by MichaelTunnell** [comment]
> The inconsistent spacing is putting me off, even though it is meant to be there to make that “G”

It's not inconsistent. The top two sections of the G are the same, the space between each box is exactly the same pixels, the only thing that isn't consistent is the middle horizontal box.

> I prefer the simple one we have that is based on the original Panorama button icon.

> But I'm with poke on this, I prefer the current "classical" icon.

That's fine, I'm not committed to the icon or anything. I'll just make a more modern version of the classic icon.

> am impressed by the effort of Michael to make this. Maybe it could be offered as an alternative, with the present one as the default?

Thanks but I'd rather it not be used if not the main one just because the feature needs focused branding to gain more users.

My goal was to address the flawed mindset of the Mozilla team thinking the feature failed when really it was Mozilla that failed the feature.

**Comment by Quicksaver** [comment]
> the feature needs focused branding to gain more users.

It does? Remember you can't think of this as a "feature" anymore, it's now an "extension". And it has/had quite enough branding in my opinion: at least three names (Tab Groups, Panorama, TabView) and a very recognizable logo. It may have lacked exposure, but definitely not branding.

> My goal was to address the flawed mindset of the Mozilla team thinking the feature failed when really it was Mozilla that failed the feature.

That goal is flawed in itself. The feature was not removed because it failed (otherwise we wouldn't be here discussing an add-on of it right now), it just became too much of a burden to maintain and to evolve together with the rest of the browser, for the little gain it would bring. (That's not failing, that's... prioritizing I guess.)

Also I don't agree with "Mozilla failed the feature". Mozilla's product goals (if we can speak of them as such) are towards Firefox, not towards Tab Groups; in that way it was Tab Groups that failed Mozilla/Firefox. My view of things is, each division in a project (each feature in the browser) is a separate entity that grows and evolves on its own, it is its own responsibility to keep doing so without overburdening the rest of development. That was not happening and so something had to be done. It was not flawed judgement or ill-will on anyone's part, it just ran its course.

Note that the feature still exists even if in the form of an add-on not maintained by Mozilla, but the same principle still applies: I will stop working on it when it stops being worth it. Same goes for everything I do in my life, otherwise I'd run out of life pretty quickly. And let me say, one of the things that most demotivates me as a coder is going through Classic Theme Restorer's user reviews and seeing all the MozHate in there... I'm willing to bet that's not why Aris created that add-on, and that is not why I'm doing any of this either.

That all to say, I do appreciate everyone's support, that's awesome, keep it coming! Suggestions, help with code, whatever, I'm all open to it! But if you're doing it just to "show up Mozilla", you're doing it for the wrong reasons and it won't work at all. Not here. :)

> Maybe it could be offered as an alternative, with the present one as the default?

It's not impossible, but I don't see the gain there. If you mean an alternative to the logo itself, then it wouldn't really make a difference other than in its listing in the add-ons manager. If you mean to the toolbar button as well, it would be hardly distinguishable from the current one, and would only increase the size of the add-on just for the sake of a novelty feature.

I already get far too many complaints that my add-ons are too big (500kb... Come on, systems where that would make a difference can't really run Firefox anyway.) so I'd rather not add to that uselessly. I don't think I'd be doing this.

**Comment by MichaelTunnell** [comment]
> It does? . . . And it has/had quite enough branding in my opinion: at least three names (Tab Groups, Panorama, TabView) and a very recognizable logo. It may have lacked exposure, but definitely not branding.

Yes, it has had a lot of branding but none of it has been Focused Branding. I just wanted to offer the idea I had in my head, whether it would be used or not doesn't matter to me. Focused Branding does matter though.

Tab Groups has suffered a LOT due to the bad branding of Mozilla calling it so many things with no concise message.

> That goal is flawed in itself. The feature was not removed because it failed (otherwise we wouldn't be here discussing an add-on of it right now), it just became too much of a burden to maintain and to evolve together with the rest of the browser, for the little gain it would bring. (That's not failing, that's... prioritizing I guess.)

Of the 3 reasons provided on the bug report / announcement 2 of them were about the lack of users and the quality of the feature. I'd say my previous comment was fair in terms of why they wanted to remove it. It wasn't just about the maintenance burden.

> from bug report: "We're removing panorama/tab groups/tabview, because it's mostly unused (estimates around 0.01% of users, see bug 1210773 comment 6), because its quality is not exactly great, and because it incurs comparably (very) high costs in terms of maintenance"

> Also I don't agree with "Mozilla failed the feature". Mozilla's product goals (if we can speak of them as such) are towards Firefox, not towards Tab Groups; in that way it was Tab Groups that failed Mozilla/Firefox.

If they put legitimate effort into making Tab Groups successful then that perspective would be fair but they didn't. They hid it behind 8 layers of steps before offering the ability to try the feature. They didn't provide any instructions in the feature at all for usage. The feature had basically no GUI to work with and required everyone who used it to figure it all out on their own. I didn't even know about the Ctrl+` shortcut mentioned in another issue here until I saw that issue. I have been using Tab Groups for 5 years and it is such a failure in UX that I didn't even know about a pretty cool functionality of it in that shortcut.

In the beginning, Tab Groups was pushed a bit but it has been ignored for years so for them to be say it is being removed for lack of users rather than they just don't want to handle it is disingenuous to me. Their lack of effort to present it to people is what created the lack of people using it.

> And let me say, one of the things that most demotivates me as a coder is going through Classic Theme Restorer's user reviews and seeing all the MozHate in there... I'm willing to bet that's not why Aris created that add-on, and that is not why I'm doing any of this either.

That is a good point and I respect that opinion but I'm not trying to hate on Mozilla. I want to prove that they are wrong. I am not trying to prove that they suck or spread hate about them but I think Tab Groups is a great feature and if people were aware of it then they would use it. The reason I say Mozilla failed this feature was because they didn't tell people it existed.

I'm a Firefox fan and also a Mozilla fan for years. I don't agree with everything they do but that doesn't mean I hate them for things. I actually like Australis and your Beyond Australis addon is pretty freaking cool, by the way. My point is that I believe they are fundamentally wrong with how they handled Tab Groups and the fact that the lack of users was due to their poor implementation of UX and discoverability not the feature itself.

I don't care if they re-implement it, because you ported it to this addon, but I do want them to realize how great Tab Groups is and that it can be popular.

**Comment by Quicksaver** [comment]
Before anything, I want to make it clear that I'm not implying that you are blowing something out of proportion, at all! In fact if anyone is, I am. ;) I do appreciate the effort in trying some focused branding for the add-on, and I still want to see if something does come out of it. I also appreciate the discussion, if anything it forces everyone (myself included) to really put some thought into their opinions, that's always good.

The following is more for other passers-by that stumble onto this and turn your "My goal was to address the flawed mindset of the Mozilla..." into an excuse to go nuts; I've seen it happen for much less (my CTR example) and it's just very counter-productive and demotivating. So I hope you don't mind I keep addressing it in this way.

> I believe they are fundamentally wrong with how they handled Tab Groups and the fact that the lack of users was due to their poor implementation of UX and discoverability not the feature itself.

Lack of exposure as you said is definitely a big reason for the under-use of groups, true.

When you have to prioritize inside a big project, something always has to suffer. If someone had worked on tab groups, they might not have done it for, I don't know, let's say the current customization mode (which is awesome for users and devs alike!). And now someone would be saying the same things about the "kinda hidden and under-developed customization window".

What I mean is they didn't simply choose to not develop Tab Groups all this time, the choice was to focus on something(s) else; I don't see that as bad handling at all. It's of course disagreeable, but I guess we're not going to convince each other by reusing the same points over and over again. :)

That said, Tab Groups did suffer from lack of development for a while there, so they did what they had to: "we can't keep it like this, lets take it out, let someone else handle it if they want". And here we are. Honestly, if I were to consider anything about this as bad handling, it would be that it took this long to happen.

> I do want them to realize how great Tab Groups is and that it can be popular.

That's fair, although personally at this point I'd rather do that for users and not for Mozilla. ;)

**Comment by MichaelTunnell** [comment]
> Before anything, I want to make it clear that I'm not implying that you are blowing something out of proportion, at all! In fact if anyone is, I am. ;)

I see, I just wanted to make sure it was clear that I wasn't bashing Mozilla or Firefox so now that I know that's clear I'm fine with your previous comments.

>The following is more for other passers-by that stumble onto this . . . So I hope you don't mind I keep addressing it in this way.

Yea, that is fine by me.

> What I mean is they didn't simply choose to not develop Tab Groups all this time, the choice was to focus on something(s) else;

This is part where we have a miscommunication. I have no issue with their lack of development, my issue is their lack of presentation of it.

By default there is no indication it exists. When installing the add-on the button gets added to the tabsbar in a place that is completely unused by default. Before the add-on, that button was not displayed there, instead in was hidden inside of the Customization section of the hamburger menu. So it took people to know about it, to know where it was to get it, to manually move it to the tabsbar and exit customization to use it. The discoverability was atrocious.

Yes, it would have been nice for the development to continue but the issue was not that it didn't receive development but it didn't even receive any presentation to users at all. The functionality is very useful and has high potential for adoption but it does need for people to know of its existence for it to be adopted.

> That's fair, although personally at this point I'd rather do that for users and not for Mozilla. ;)

I agree, I wasn't the add-on to exist for my users and I want to make people more aware of it so they too can use it. I don't care if Mozilla provides or not. I just want the functionality, add-on, to get a fair share because if users knew of it then most would use it.

I believe that potential so strongly that I'm writing an article about this add-on that will be publish on howtogeek.com :)

**Comment by Quicksaver** [comment]
> By default there is no indication it exists. When installing the add-on the button gets added to the tabsbar in a place that is completely unused by default. Before the add-on, that button was not displayed there, instead in was hidden inside of the Customization section of the hamburger menu.

I'm almost sure this wasn't always the case. I can remember having the groups button placed on the tabs bar by default in the early days of Firefox 4, and then being moved out of there automatically some time later... I think. I could be wrong! Maybe I moved it there myself? Anyway...

> Yes, it would have been nice for the development to continue but the issue was not that it didn't receive development but it didn't even receive any presentation to users at all.

I understand your point of course. Development without presentation doesn't really count for much, but then again you can't have presentation without development (as in, you need to develop it in order to present it better). I think in the end they're the same thing, which is why I don't really separate them in relation to "amount of work or dedication put into it".

> I believe that potential so strongly that I'm writing an article about this add-on that will be publish on howtogeek.com :)

That's awesome! Let's see if in the coming months I'll be able to give you a few extra reasons to not call it a "replacement only" as well. :)
