### ISSUE TITLE
Feature request: Allow the deactivation of the "your tabs will not be restored" warning

### ISSUE THREAD

**Issue by wpost** [Quicksaver/Tab-Groups#99]
Current behavior is to display a warning in the tab groups view if Firefox is not set to show previous windows and tabs upon restart. This is reasonable default behavior. 

However, I would like to suggest that there be a way to deactivate this warning. I (and perhaps some other users) prefer Tab Groups to start each session with a clean slate, and I would like to be able to deactivate what for me is a needless (and needlessly distracting) warning. Perhaps a checkbox for this could be added to the preferences?

**Comment by Quicksaver** [comment]
I've been thinking about adding this, but only because many users are asking for the same thing. I don't personally agree this is good behavior, it's very easy to forget (even if you know it's going to happen) that your tabs won't be saved for the next session, you set up 300 tabs and then gone.

Also, at most I will make this a preference in about:config which you'll have to toggle directly, I won't add a checkbox in the add-on's preferences tab precisely because of that; it would be far too easy for a user to check it without really knowing what it does.

**Comment by Quicksaver** [comment]
Well I suck. I already added this and completely forgot when I replied here. :)

Just go to about:config and enable "extensions.tabgroups.noWarningAboutSession".

**Comment by wpost** [comment]
The easiest feature request to implement is the one that's already been implemented. ;-)

I agree that doing it via about:config is sensible. There is no need to expose advanced settings to users that aren't advanced. Indeed, it should have occurred to me to see what was available in about:config before even opening this request. In any case, it works great and thanks!
